package com.dometic.SDB.qa.Pages;

public class Constant_power {
    // ------------Accessibility_id------------------//
    public static final String Powerpage_power_text_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String Powerpage_power_text_expected="POWER";
    public static final String Powerpage_houseBattery_text_access_id="com.dometicapp:id/powerScreen-houseBatteryText";
    public static final String Powerpage_houseBattery_expected="HOUSE BATTERY";
    public static final String Powerpage_batteryVoltageText_access_id="com.dometicapp:id/powerScreen-batteryVoltageText";
    public static final String Powerpage_batteryVoltageText_expected="Battery Voltage";
    public static final String Powerpage_batteryVoltageValue_access_id="com.dometicapp:id/powerScreen-batteryVoltageValue";
    public static final String Powerpage_batteryVoltagevoltText_access_id="com.dometicapp:id/powerScreen-batteryVoltagevoltText";
    public static final String Powerpage_currentText_access_id="com.dometicapp:id/powerScreen-currentText";
    public static final String Powerpage_currentText_expected="Current";
    public static final String Powerpage_currentValue_access_id="com.dometicapp:id/powerScreen-currentValue";
    public static final String Powerpage_ampereText_access_id="com.dometicapp:id/powerScreen-ampereText";
    public static final String Powerpage_timeText_access_id="com.dometicapp:id/powerScreen-timeText";
    public static final String Powerpage_timeText_expected="Time";
    public static final String Powerpage_timeValue_access_id="com.dometicapp:id/powerScreen-timeValue";
    public static final String Powerpage_hourText_access_id="com.dometicapp:id/powerScreen-hourText";
    public static final String Powerpage_powerSourceText_access_id="com.dometicapp:id/powerScreen-powerSourceText";
    public static final String Powerpage_powerSourceText_expected="Power Source";
    public static final String Powerpage_powerSourceValue_access_id="com.dometicapp:id/powerScreen-powerSourceValue";
    public static final String Powerpage_powerSourcevoltText_access_id="com.dometicapp:id/powerScreen-powerSourcevoltText";
    public static final String L2Powerpagepower_percentage_access_id="com.dometicapp:id/powerScreen-progressBar";
    public static final String L2Powerpagepower_Inverter_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle";
    public static final String L2Powerpagepower_Inverter_switchText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchText";
    public static final String L2Powerpagepower_Inverter_switchComponent_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchComponent";
    public static final String L2Powerpagepower_Operating_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle";
    public static final String L2Powerpagepower_Operating_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText";
    public static final String L2Powerpagepower_House_Battery_Voltage_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardTitle";
    public static final String L2Powerpagepower_House_Battery_Voltage_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardSubText\n";
    public static final String L2Powerpagepower_Load_Wattage_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-4-cardTitle";
    public static final String L2Powerpagepower_Load_Wattage_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-4-cardSubText";
    public static final String L2Powerpagepower_Chassis_Battery_Voltage_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-6-cardTitle";
    public static final String L2Powerpagepower_Chassis_Battery_Voltage_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-6-cardSubText";
    public static final String L2Powerpagepower_Generator_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-8-cardTitle";
    public static final String L2Powerpagepower_Generator_cardIcon_access_id="om.dometicapp:id/powerScreen-flatListItem-undefined-8-cardIcon";
    public static final String L2Powerpagepower_Charger_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-9-cardTitle";
    public static final String L2Powerpagepower_Charger_cardIcon_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-9-cardIcon";
    public static final String L2Powerpagepower_AGS_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-10-cardTitle";
    public static final String L2Powerpagepower_AGS_cardIcon_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-10-cardIcon";
    public static final String L2Powerpagepower_Prdictive_Data_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-11-cardTitle";
    public static final String L2Powerpagepower_Prdictive_Data_cardIcon_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-11-cardIcon";
    public static final String L2Powerpagepower_Generator_inside_text_access_id="com.dometicapp:id/powerScreen-houseBatteryText";
    public static final String L2Powerpagepower_Generator_Control_text_access_id="com.dometicapp:id/powerScreen-controller";
    public static final String L2Powerpagepower_Generator_Control_switchText_access_id= "com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchText";
    public static final String L2Powerpagepower_Generator_Control_switchComponent_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchComponent";
    public static final String L2Powerpagepower_Status_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle";
    public static final String L2Powerpagepower_Status_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText";
    public static final String L2Powerpagepower_Run_Time_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardTitle";
    public static final String L2Powerpagepower_Run_Time_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardSubText";
    public static final String L2Powerpagepower_Charger_inside_text_access_id="com.dometicapp:id/powerScreen-houseBatteryText";
    public static final String L2Powerpagepower_Charger_state_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle";
    public static final String L2Powerpagepower_Charger_statecardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardSubText";
    public static final String L2Powerpagepower_Charger_Current_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle";
    public static final String L2Powerpagepower_Charger_Current_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText";
    public static final String L2Powerpagepower_Charger_AC_Input_Current_Text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardTitle";
    public static final String L2Powerpagepower_Charger_AC_Input_Current_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardSubText";
    public static final String L2Powerpagepower_Charger_AC_Load_Current_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardTitle";
    public static final String L2Powerpagepower_Charger_AC_Load_Current_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardSubText";
    public static final String L2Powerpagepower_AGS_Inside_text_access_id="com.dometicapp:id/powerScreen-houseBatteryText";
    public static final String L2Powerpagepower_AGS_Clear_AGS_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle";
    public static final String L2Powerpagepower_AGS_Clear_AGS_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardSubText";
    public static final String L2Powerpagepower_AGS_Status_text_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle";
    public static final String L2Powerpagepower_AGS_Status_cardSubText_access_id="com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText";
    public static final String L2Powerpagepower_Predicitive_data_inside_access_id="";
    public static final String L2Powerpagepower_Predicitive_data_Battery_remaining_access_id="";
    public static final String L2Powerpagepower_Predicitive_data_Battery_Graph_access_id="";
    public static final String L2Powerpagepower_Predicitive_data_Week_access_id="";
    public static final String L2Powerpagepower_start_button_access_id="com.dometicapp:id/powerScreen-startButton";
    public static final String L2Powerpagepower_stop_button_access_id="com.dometicapp:id/powerScreen-stopButton";

    //Version 103 Access_id and data
    public static final String BATTERIES_header_text_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String BATTERIES_header_text="BATTERIES";
    public static final String powerScreen_batteryCarousel_circle_Engine1_access_id="com.dometicapp:id/powerScreen-batteryCarousel-circle-0";
    public static final String powerScreen_batteryCarousel_circle_Engine1_text="Engine-1";
    public static final String powerScreen_batteryCarousel_circle_STBD_access_id="com.dometicapp:id/powerScreen-batteryCarousel-circle-1";
    public static final String powerScreen_batteryCarousel_circle_STBD_text="STBD";
    public static final String powerScreen_batteryCarousel_circle_House_access_id="com.dometicapp:id/powerScreen-batteryCarousel-circle-2";
    public static final String powerScreen_batteryCarousel_circle_House_text="House";
    public static final String powerScreen_batteryCarousel_circle_Engine1_text_access_id="com.dometicapp:id/powerScreen-batteryCarousel-batteryName-0";
    public static final String powerScreen_batteryCarousel_circle_STBD_text_access_id="com.dometicapp:id/powerScreen-batteryCarousel-batteryName-1";
    public static final String powerScreen_batteryCarousel_circle_House_text_access_id="com.dometicapp:id/powerScreen-batteryCarousel-batteryName-2";
    public static final String powerScreen_Measured_Voltage_text="Measured Voltage";
    public static final String powerScreen_Measured_Voltage_access_id="com.dometicapp:id/powerScreen-measuredVoltage-cardTitle";
    public static final String powerScreen_Measured_Voltage_cardSubText_access_id="com.dometicapp:id/powerScreen-measuredVoltage-cardSubText";
    public static final String powerScreen_status_text="Status";
    public static final String powerScreen_status_access_id="com.dometicapp:id/powerScreen-status-cardTitle";
    public static final String powerScreen_status_cardSubText_access_id="com.dometicapp:id/powerScreen-status-cardSubText";
    public static final String powerScreen_usage_text="Usage Analysis";
    public static final String powerScreen_usage_access_id="com.dometicapp:id/powerScreen-usage-cardTitle";
    public static final String powerScreen_usage_expandIcon_access_id="com.dometicapp:id/powerScreen-usage-expandIcon";
    public static final String powerScreen_alert_text="Alert";
    public static final String powerScreen_alert_access_id="com.dometicapp:id/powerScreen-alert-cardTitle";
    public static final String powerScreen_alert_switchText_access_id="com.dometicapp:id/powerScreen-alert-switchText";
    public static final String powerScreen_alert_switchComponent_access_id="com.dometicapp:id/powerScreen-alert-switchComponent";
    public static final String powerScreen_notify_text="Notify Me";
    public static final String powerScreen_notify_access_id="com.dometicapp:id/powerScreen-notify-cardTitle";
    public static final String powerScreen_notify_switchText_access_id="com.dometicapp:id/powerScreen-notify-switchText";
    public static final String powerScreen_notify_switchComponent_access_id="com.dometicapp:id/powerScreen-notify-switchComponent";
    public static final String powerScreen_batteryVoltage_text="Battery Voltage";
    public static final String powerScreen_batteryVoltage_access_id="com.dometicapp:id/powerScreen-batteryVoltage-cardTitle";
    public static final String powerScreen_batteryVoltage_textButton_access_id="com.dometicapp:id/powerScreen-batteryVoltage-textButton";

    // Power Main screen Text
    public static final String L2_powerHeader="POWER";
    public static final String L2_House_Battery="HOUSE BATTERY";
    public static final String L2_Inverter="Inverter";
    public static final String L2_OperatingMode="Operating Mode";
    public static final String L2_HouseBatteryVoltage="House Battery Voltage";
    public static final String L2_ChassisBatteryVoltage="Chassis Battery Voltage";
    public static final String L2_LoadWattage="Load Wattage";
    public static final String L2_Generator="Generator";
    public static final String L2_Charger="Charger";
    public static final String L2_AGS="AGS";
    public static final String L2_PredictiveData="Predictive Data";


    //Generator Main screen Text
    public static final String L2_Control_Generator="Controller";
    public static final String L2_Status_Generator="Status";
    public static final String L2_RunTime_Generator="Run Time";


    //Charger Main screen Text
    public static final String L2_Charger_state="Charger State";
    public static final String L2_Charger_current="Charger Current";
    public static final String L2_AC_Input_current="AC Input Current";
    public static final String L2_AC_Load_current="AC Load Current";

    //power AGS Main Screen
    public static final String L2_clear_AGS="Clear AGS";
    public static final String L2_status_AGS="Status";


    // ------------X Path------------------//
    public static final String L2_Control_xpath="//*[@text='Controller']";
    public static final String L2_Charger_state_xpath="//*[@text='Charger State']";
    public static final String L2_clear_AGS_xpath="//*[@text='Clear AGS']";
    public static final String L2_Water_Heater_Truma="//*[@text='Water Heater']";
    public static final String L2_power_percentage_xpath="(//*[@content-desc='com.dometicapp:id/tile-mainCardText'])[3]";
    public static final String CAC_M_power_percentage_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-container']/android.view.ViewGroup";
    public static final String Powerpage_power_text_xpath="//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']";
    public static final String Powerpage_houseBattery_text_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-container']/android.view.ViewGroup";
    public static final String Powerpage_batteryVoltageText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-houseBatteryText']";
    public static final String Powerpage_batteryVoltageValue_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-batteryVoltageValue']";
    public static final String Powerpage_batteryVoltagevoltText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-batteryVoltagevoltText']";
    public static final String Powerpage_currentText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-currentText']";
    public static final String Powerpage_currentValue_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-currentValue']";
    public static final String Powerpage_ampereText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-ampereText']";
    public static final String Powerpage_timeText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-timeText']";
    public static final String Powerpage_timeValue_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-timeValue']";
    public static final String Powerpage_hourText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-hourText']";
    public static final String Powerpage_powerSourceText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-powerSourceText']";
    public static final String Powerpage_powerSourceValue_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-powerSourceValue']";
    public static final String Powerpage_powerSourcevoltText_xpath="//*[@content-desc='com.dometicapp:id/powerScreen-powerSourcevoltText']";
    public static final String Powerpage_Back_Button_xpath="//*[@content-desc='com.dometicapp:id/tiles-backImage']";
    public static final String L2Powerpagepower_percentage_xpath="//android.widget.ScrollView[@content-desc=\"com.dometicapp:id/powerScreen-scrollView\"]/android.view.ViewGroup/android.view.ViewGroup";
    public static final String L2Powerpagepower_Inverter_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle\"]";
    public static final String L2Powerpagepower_Inverter_switchText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchText\"]";
    public static final String L2Powerpagepower_Inverter_switchComponent_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchComponent\"]";
    public static final String L2Powerpagepower_Operating_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle\"]";
    public static final String L2Powerpagepower_Operating_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText\"]";
    public static final String L2Powerpagepower_House_Battery_Voltage_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardTitle\"]";
    public static final String L2Powerpagepower_House_Battery_Voltage_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardSubText\"]";
    public static final String L2Powerpagepower_Load_Wattage_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-4-cardTitle\"]";
    public static final String L2Powerpagepower_Load_Wattage_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-4-cardSubText\"]";
    public static final String L2Powerpagepower_Chassis_Battery_Voltage_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-6-cardTitle\"]";
    public static final String L2Powerpagepower_Chassis_Battery_Voltage_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-6-cardSubText\"]";
    public static final String L2Powerpagepower_Generator_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-8-cardTitle\"]";
    public static final String L2Powerpagepower_Generator_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-8-cardIcon\"]";
    public static final String L2Powerpagepower_Charger_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-9-cardTitle\"]";
    public static final String L2Powerpagepower_Charger_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-9-cardIcon\"]";
    public static final String L2Powerpagepower_AGS_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-10-cardTitle\"]";
    public static final String L2Powerpagepower_AGS_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-10-cardIcon\"]";
    public static final String L2Powerpagepower_Prdictive_Data_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-11-cardTitle\"]";
    public static final String L2Powerpagepower_Prdictive_Data_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-11-cardIcon\"]";
    public static final String L2Powerpagepower_Generator_inside_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-houseBatteryText\"]";
    public static final String L2Powerpagepower_Generator_Control_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle\"]";
    public static final String L2Powerpagepower_Generator_Control_switchText_xpath= "//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchText\"]";
    public static final String L2Powerpagepower_Generator_Control_switchComponent_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-switchComponent\"]";
    public static final String L2Powerpagepower_Status_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle\"]";
    public static final String L2Powerpagepower_Status_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText\"]";
    public static final String L2Powerpagepower_Run_Time_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardTitle\"]";
    public static final String L2Powerpagepower_Run_Time_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardSubText\"]";
    public static final String L2Powerpagepower_Charger_inside_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-houseBatteryText\"]";
    public static final String L2Powerpagepower_Charger_state_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle\"]";
    public static final String L2Powerpagepower_Charger_statecardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardSubText\"]";
    public static final String L2Powerpagepower_Charger_Current_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle\"]";
    public static final String L2Powerpagepower_Charger_Current_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText\"]";
    public static final String L2Powerpagepower_Charger_AC_Input_Current_Text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardTitle\"]";
    public static final String L2Powerpagepower_Charger_AC_Input_Current_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-2-cardSubText\"]";
    public static final String L2Powerpagepower_Charger_AC_Load_Current_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardTitle\"]";
    public static final String L2Powerpagepower_Charger_AC_Load_Current_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-3-cardSubText\"]";
    public static final String L2Powerpagepower_AGS_Inside_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-houseBatteryText\"]";
    public static final String L2Powerpagepower_AGS_Clear_AGS_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardTitle\"]";
    public static final String L2Powerpagepower_AGS_Clear_AGS_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-0-cardSubText\"]";
    public static final String L2Powerpagepower_AGS_Status_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardTitle\"]";
    public static final String L2Powerpagepower_AGS_Status_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-flatListItem-undefined-1-cardSubText\"]";
    public static final String L2Powerpagepower_Predicitive_data_inside_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-houseBatteryText\"])[1]";
    public static final String L2Powerpagepower_Predicitive_data_Battery_remaining_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-houseBatteryText\"])[2]";
    public static final String L2Powerpagepower_Predicitive_data_Battery_Graph_xpath="//android.view.ViewGroup[@content-desc=\"undefined-com.dometicapp:id/BarChart-barChartContainer\"]/android.view.ViewGroup[2]/android.view.ViewGroup";
    public static final String L2Powerpagepower_Predicitive_data_Week_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/powerScreen-houseBatteryText\"])[3]";
    public static final String powerScreen_batteryCarousel_circle_Engine1_text_xpath="(//*[@content-desc='com.dometicapp:id/powerScreen-batteryCarousel-batteryName-0']//following::android.widget.TextView)[1]";
    public static final String powerScreen_batteryCarousel_circle_STBD_text_xpath="(//*[@content-desc='com.dometicapp:id/powerScreen-batteryCarousel-batteryName-1']//following::android.widget.TextView)[1]";
    public static final String powerScreen_batteryCarousel_circle_House_text_xpath="(//*[@content-desc='com.dometicapp:id/powerScreen-batteryCarousel-batteryName-2']//following::android.widget.TextView)[1]";

}
