package com.dometic.SDB.qa.Pages;

public class Constant_settings {
    // --------------Accessibility_id-------------------//
    public static final String Settings_Back_Button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_languageContainer_access_id="com.dometicapp:id/setting-languageContainer";
    public static final String Settings_versionContainer_access_id="com.dometicapp:id/setting-versionContainer";
    public static final String Settings_language_text_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_language_text_expected="Sprache";
    public static final String Settings_AccountSettings_Subscription_text_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'Subscriptions') or@content-desc='com.dometicapp:id/userSettings-subscriptions-cardTitle']";
    public static final String Settings_AccountSettings_Subscription_text="Subscriptions";
    public static final String Settings_language_Spanish_text_expected="Idioma";
    public static final String Settings_temperature_Spanish_text_expected="Unidad de temperatura";
    public static final String Settings_version_Spanish_text_expected="Versión 1.3";
    public static final String Settings_logout_Spanish_text_expected="Cerrar sesión";
    public static final String Settings_language_French_text_expected="Langue";
    public static final String Settings_temperature_French_text_expected="Unité de température";
    public static final String Settings_version_French_text_expected="Version 1.3";
    public static final String Settings_logout_French_text_expected="Déconnexion";
    public static final String Settings_language_selectedName_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String Settings_languages_navigation_button_access_id="com.dometicapp:id/setting-languageiconCollapse";
    public static final String Settings_Language_English_tick_access_id="com.dometicapp:id/language-iconTickEnglish";
    public static final String Settings_language_German_access_id="com.dometicapp:id/language-germanText";
    public static final String Settings_Language_German_tick_access_id="com.dometicapp:id/language-iconTickGerman";
    public static final String Settings_Temperature_text_access_id="com.dometicapp:id/setting-temperatureContainer";
    public static final String Settings_Temperature_text_expected="Temperatureinheit";
    public static final String Settings_version_text_access_id="com.dometicapp:id/setting-versionText";
    public static final String Settings_logout_text_access_id="com.dometicapp:id/setting-logOutText";
    public static final String Settings_logout_expected="Abmelden";
    public static final String Settings_fahrenheit_access_id="com.dometicapp:id/setting-fahrenheitText";
    public static final String Settings_Temperature_unit_access_id="com.dometicapp:id/setting-temperatureButtons";
    public static final String Settings_Zone_Management_expected="Zone Management";
    public static final String Settings_Zone_Management_ALL_ZONES_text="ALL ZONES";
    public static final String Settings_Zone_Management_edit_text="Edit";
    public static final String Settings_Zone_Management_LimitedZones_text="Limited to 4 Zones only";
    public static final String Settings_Zone_Management_addZoneIcon_access_id="com.dometicapp:id/zoneManagement-addZoneIcon";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_access_id="com.dometicapp:id/ZoneNumber-selectButton";
    public static final String Settings_Zone_Management_addZoneIcon_Select_text_access_id="com.dometicapp:id/ZoneNumber-selectZoneText";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_text="Zone Name can not be empty";
    public static final String Settings_Zone_Management_10_character_text="10/10 character";
    public static final String Settings_Zone_Management_value="Living Room";
    public static final String Settings_Zone_Management_Living_Room="LivingRoom";
    public static final String Settings_Zone_Management_NewZone_Room="StudyRoom";
    public static final String Settings_Zone_Management_deleteZoneAlert_cancelButton_access_id="com.dometicapp:id/zoneManagement-deleteZoneAlert-saveButton";
    public static final String Settings_Zone_Management_deleteZoneAlert_YES_DELETE_ITButton_access_id="com.dometicapp:id/zoneManagement-deleteZoneAlert-cancelButton";
    public static final String Settings_Zone_Management_new_Zone_access_id="com.dometicapp:id/ZoneNumber-dialog-undefined";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_access_id="com.dometicapp:id/ZoneNumber-dialog-saveButton";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_access_id="com.dometicapp:id/ZoneNumber-dialog-cancelButton";
    public static final String Settings_headerBackButtonIcon_access_id="com.dometicapp:id/sidemenu-headerBackButtonIcon";
    public static final String Settings_userProfilePhoto_access_id="com.dometicapp:id/sidemenu-userProfilePhoto";
    public static final String Settings_userName_access_id="com.dometicapp:id/sidemenu-userName";
    public static final String Settings_userEmail_access_id="com.dometicapp:id/sidemenu-userEmail";
    public static final String Settings_viewEditButtonText_access_id="com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String Settings_home_text_access_id="com.dometicapp:id/sidemenu-home-text";
    public static final String Settings_notificationSettings_text_access_id="com.dometicapp:id/sidemenu-notificationSettings-text";
    public static final String Settings_deviceMangagement_text_access_id="com.dometicapp:id/sidemenu-deviceMangagement-text";
    public static final String Device_Management_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'Device Management') or @content-desc='com.dometicapp:id/sidemenu-deviceMangagement-text']";
    public static final String Device_Management_back_button_accessid ="com.dometicapp:id/sidemenu-deviceMangagement-text";
    public static final String Settings_appSettings_text_access_id="com.dometicapp:id/sidemenu-appSettings-text";
    public static final String Settings_Logout_text_access_id="com.dometicapp:id/sidemenu-logout-text";
    public static final String Settings_Version_16_text_access_id="com.dometicapp:id/sidemenu-versionText";



    //-------------------Needed Accessibility Id-----------------//
    public static final String Settings_Language_Page_title_access_id="";
    public static final String Settings_language_Back_button_access_id="";
    public static final String Settings_Language_English_access_id="";
    public static final String Settings_back_button_access_id="";
    public static final String Settings_page_title_access_id="";
    public static final String Settings_temperature_unit_C_access_id="";
    public static final String Settings_temperature_unit_F_access_id="";

    // ----------------------xpath-----------------------------//
    public static final String Settings_text_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage'])[1]";
    public static final String Settings_Language_select_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[1]";
    public static final String Settings_Temperature_unit_xpath="(//*[@class='android.view.ViewGroup'])[17]";
    public static final String Settings_Upgrade_Firmware_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[2]";
    public static final String Settings_Version_xpath="//*[@content-desc='com.dometicapp:id/setting-versionContainer']";
    public static final String Settings_Logout_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/setting-logOutContainer']/android.view.ViewGroup";
    public static final String Settings_Language_Page_title_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_language_Back_button_xpath="//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup/android.widget.ImageView";
    public static final String Settings_Language_English_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/language-englishContainer\"]";
    public static final String Settings_back_button_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]";
    public static final String Settings_page_title_xpath= "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_temperature_unit_C_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[1]/android.view.ViewGroup/android.widget.TextView";
    public static final String Settings_temperature_unit_F_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.TextView\n";
    public static final String Settings_language_Spanish_xpath="//*[@text='Spanish (US)']";
    public static final String Settings_language_French_xpath="//*[@text='French']";
    public static final String Settings_language_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageText'])[1]";
    public static final String Settings_Zone_Management_xpath="(//*[@content-desc='com.dometicapp:id/setting-scrollView']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_edit_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_LimitedZones_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_xpath="(//*[@content-desc='com.dometicapp:id/zoneManagement-flatList']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_value_xpath="//android.widget.EditText[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_SAVE_Button_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_CANCEL_Button_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_flatListItem_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-flatListItem-')]//following::android.view.ViewGroup)[2]";
    public static final String Settings_Zone_Management_deleteZoneAlert_description_xpath="//*[@content-desc='com.dometicapp:id/zoneManagement-deleteZoneAlert-description']";
    public static final String Settings_Zone_Management_deleteZone_xpath="//*[@text='YES, DELETE IT']";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-selectButton']";
    public static final String Settings_Zone_Management_new_Zone_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-undefined']";
    public static final String Settings_Zone_Management_Zone_name_already_present_xpath="//*[@text='Zone name already present']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-saveButton']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-cancelButton']";
    public static final String Device_Management_edit_close_button_xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/header-rightButton']/android.widget.TextView";
    public static final String Device_Management_Edit_screen_device_name_access_id =  "com.dometicapp:id/editVessel-vesselNameValue";
    public static final String Device_Management_Edit_Screen_Save_button_access_id = "com.dometicapp:id/editVessel-saveButton";
    public static final String Device_Management_vessel_name_special_character_error_msg_Xpath = "//android.widget.ScrollView[@content-desc='com.dometicapp:id/editVessel-scrollview']/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.TextView[2]";
    public static final String Device_Management_vessel_name_error_msg_Xpath=                    "//android.widget.ScrollView[@content-desc='com.dometicapp:id/editVessel-scrollview']/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.TextView[2]";
    public static final String Device_Management_Name_Section_device_name_access_id ="com.dometicapp:id/DeviceManagementDetailsScreen-NameLabel-Title";
    public static final String Device_Management_device_label_name_access_id ="com.dometicapp:id/DeviceManagementScreen-DeviceManagementButton-Title";
    public static final String Device_Management_gallery_device_name_Access_id ="com.dometicapp:id/Dashboard-cardText";
    public static final String Temperature_settings_back_buttion_icon_accessid="com.dometicapp:id/tiles-backImage";
    public static final String Temperature_settings_header_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Device_management_Temperature_settings_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardTitle";
    public static final String Temperature_settings_temperature_control_access_id="-Temperaturecontrol-cardTitle";
    public static final String Temperature_settings_temperature_scheduler_access_id="-Scheduler-cardTitle";
    public static final String Temperature_settings_current_temperature_xpath="//*[@text='CURRENT TEMPERATURE']";
    public static final String Temperature_settings_outside_xpath="//*[@text='Outside']";
    public static final String Temperature_settings_lower_compartment_xpath="//*[@text='Lower compartment']";
    public static final String Temperature_settings_temperature_alert_xpath="//*[@text='TEMPERATURE ALERT']";
    public static final String Temperature_settings_temperature_threshold_xpath="//*[@text='Temperature threshold']";
    public static final String Temperature_settings_scheduler_header_xpath="//*[@text='SCHEDULER']";

    // --------------Accessibility_id SDB Device management-------------------//
    public static final String hamburger_button_selection_access_id="com.dometicapp:id/header-menuButton";
    public static final String Device_management_hamburger_selection_access_id= "com.dometicapp:id/sidemenu-deviceMangagement-text";
    public static final String Device_management_header_text_tile_access_id="com.dometicapp:id/header-TitleText";
    public static final String Device_management_right_icon_xpath="(//*[@content-desc='com.dometicapp:id/DeviceManagement-rightIcon'])[1]";
    public static final String Device_management_product_information_text_tile_access_id="com.dometicapp:id/deviceManagement-vesseltitleLabel";
    public static final String Device_management_vessel_name_lable_access_id="com.dometicapp:id/deviceManagement-vesselNameLabel";
    public static final String Device_management_edit_vessel_card_title_text_access_id="com.dometicapp:id/deviceManagement-editVessel-cardTitle";
    public static final String Device_management_edit_vessel_card_right_icon_access_id="com.dometicapp:id/deviceManagement-editVessel-cardIcon";
    public static final String Device_management_pin_codes_card_title_access_id="com.dometicapp:id/deviceManagement-pinCodeTitleText";
    public static final String Device_management_master_pin_card_title_text_access_id="com.dometicapp:id/deviceManagement-masterPin-cardTitle";
    public static final String Device_management_master_pin_card_right_icon_access_id="com.dometicapp:id/deviceManagement-masterPin-cardIcon";
    public static final String Device_management_Get_pin_list_card_title_access_id="com.dometicapp:id/deviceManagement-guestPin-cardTitle";
    public static final String Device_management_Get_pin_list_right_icon_access_id="com.dometicapp:id/deviceManagement-guestPin-cardIcon";
    public static final String Device_management_advanced_title_text_access_id="com.dometicapp:id/deviceManagement-advancedTitleText";
    public static final String Device_management_cooler_setting_card__title_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardTitle";
    public static final String Device_management_cooler_setting_text_right_icon_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardIcon";
    public static final String Device_management_check_updates_card_title_access_id="com.dometicapp:id/deviceManagement-checkForUpdates-cardTitle";
    public static final String Device_management_check_updates_right_icon_access_id="com.dometicapp:id/deviceManagement-checkForUpdates-cardIcon";
    public static final String Device_management_Unregister_delete_off_boards_text_access_id="com.dometicapp:id/deviceManagement-unregisterDelete-cardTitle";
    public static final String Device_management_Unregister_delete_off_boards_right_icon_access_id="com.dometicapp:id/deviceManagement-unregisterDelete-cardIcon";
    public static final String Device_management_Edit_vessel_Edit_text_tile_access_id="com.dometicapp:id/header-TitleText";
    public static final String Device_management_Edit_vessel_name_text_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'Name') or @content-desc='com.dometicapp:id/editVessel-vesselNameLabel']";
    public static final String Device_management_Edit_header_text_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'EDIT') or @content-desc='com.dometicapp:id/header-TitleText']";
    public static final String Device_management_Edit_vessel_save_button_access_id="com.dometicapp:id/editVessel-saveButtonText";
    public static final String Device_management_Edit_vessel_image_access_id="com.dometicapp:id/deviceManagement-deviceImage";
    public static final String Device_management_Edit_page_back_button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Device_management_screen_back_button_accessid="com.dometicapp:id/tiles-backImage";
    public static final String Device_management_device_selection_back_button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Device_management_device_selection_something="com.dometicapp:id/editVessel-vesselNameValue";
    public static final String Device_manegement_cooler_setting_right_back_button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Device_manegement_cooler_setting_temperature__right_icon_access_id="com.dometicapp:id/sdbCoolerSettings-temperature-cardIcon";
    public static final String Device_manegement_cooler_setting_temperature_card_title_access_id="com.dometicapp:id/sdbCoolerSettings-temperature-cardTitle";
    public static final String Device_manegement_cooler_setting_scheduled_at_right_icon_access_id="com.dometicapp:id/sdbCoolerSettings-scheduledAt-cardIcon";
    public static final String Device_manegement_cooler_setting_scheduled_at_card_title_access_id="com.dometicapp:id/sdbCoolerSettings-scheduledAt-cardTitle";
    public static final String Device_manegement_cooler_setting_scheduler_toggel_button_access_id="com.dometicapp:id/sdbCoolerSettings-scheduler-switchComponent";
    public static final String Device_manegement_cooler_setting_scheduler_card_title_access_id="com.dometicapp:id/sdbCoolerSettings-scheduler-cardTitle";
    public static final String Device_manegement_cooler_setting_cooler_Status_toggel_button_access_id="com.dometicapp:id/sdbCoolerSettings-coolerStatus-switchComponent";
    public static final String Device_manegement_cooler_setting_cooler_Status_name_access_id="com.dometicapp:id/sdbCoolerSettings-coolerStatus-cardTitle";
    public static final String Device_manegement_cooler_setting_page_header_text="com.dometicapp:id/header-TitleText";
    public static final String Device_manegement_cooler_setting_right_icon_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardIcon";
    public static final String Device_manegement_cooler_setting_main_text_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardTitle";


    public static final String ManageNotifications_Advanced_Temperature_Alerts_Push_notifications_toggle_access_id = "TemperatureAlertsElement0-Switch";
    public static final String ManageNotifications_Advanced_Temperature_Alerts_Push_notifications_text_access_id = "TemperatureAlertsElement0-Text";
    public static final String ManageNotifications_Advanced_Batteries_Alerts_Push_notifications_toggle_access_id = "BatteriesAlertsElement0-Switch";
    public static final String ManageNotifications_Advanced_Batteries_Alerts_Push_notifications_text_access_id = "BatteriesAlertsElement0-Text";
    public static final String ManageNotifications_PushNotifications_Toggle_Xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/notification-pushNotificationContainer-Switch']";
    public static final String ManageNotifications_PushNotifications_Toggle_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Switch";
    public static final String ManageNotifications_Advanced_Tank_show_less_access_id = "ELEMENT-cardTitle";
    public static final String ManageNotifications_Advanced_Tanks_Alerts_Push_notifications_toggle_access_id = "TanksAlertsElement0-Switch";
    public static final String ManageNotifications_Advanced_Tanks_Alerts_Push_notifications_text_access_id = "TanksAlertsElement0-Text";
    public static final String ManageNotifications_Advanced_push_Email_access_id = "deviceEmailNotifications0Element0-Text";
    public static final String ManageNotifications_Advanced_push_notifications_toggle_button_access_id = "devicePushNotificationsElement-Switch";
    public static final String ManageNotifications_Advanced_push_notifications_access_id = "devicePushNotificationsElement-Text";
    public static final String ManageNotifications_Advanced_logo_access_id = "DeviceNotifications.Header-logo";
    public static final String ManageNotifications_Advanced_back_button_access_id = "com.dometicapp:id/tiles-backImage";
    public static final String ManageNotifications_Advanced_header_text_access_id = "com.dometicapp:id/header-TitleText";
    public static final String ManageNotifications_Advanced_Device_SDB_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-Dometic1234-name";
    public static final String ManageNotifications_Advanced_Device_SDB_navigation_button_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-Dometic1234-iconCollapse";
    public static final String ManageNotifications_Advanced_Device_SDB_icon_access_id = "AdvancedNotificationSetings-Dometic1234-icon";
    public static final String ManageNotifications_Advanced_text_access_id = "com.dometicapp:id/notification-advanceText";
    public static final String ManageNotifications_Advanced_Email_toggle_button_access_id = "deviceEmailNotifications0Element0-Switch";
    public static final String ManageNotifications_Advanced_device_name_access_id = "DeviceNotifications.Header-text";
    public static final String Device_management_edit__save_button_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'Save') or@content-desc='com.dometicapp:id/editVessel-saveButtonText']";
    public static final String Settings_english_language_text_selection="com.dometicapp:id/language-english-cardTitle";
    public static final String Settings_english_language_LANGUAGE_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_version_german_language="com.dometicapp:id/language-german-cardTitle";
    public static final String App_setting_main_text_access_id="com.dometicapp:id/sidemenu-appSettings-text";
    public static final String profile_renew_card_icon_access_id = "com.dometicapp:id/userProfile-renew-cardIcon";
    public static final String Profile_Back_button_access_id = ", back";
    public static final String Profile_Back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]";
    public static final String cancel_image_access_id = "com.dometicapp:id/header-leftButtonImage";
    public static final String profile_renew_card_icon_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/userProfile-renew-cardIcon\"]";
    public static final String profile_setting_renew_xpath_or_operator = "//android.widget.TextView[contains(@text,'Renew') or @content-desc='com.dometicapp:id/userProfile-renew-cardTitle']";
    public static final String profile_setting_password_name_xpath_or_operator = "//android.widget.TextView[contains(@text,'Password') or @content-desc='com.dometicapp:id/userProfile-resetPasswordText']\n";
    public static final String profile_setting_security_name_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SECURITY') or @content-desc='com.dometicapp:id/userProfile-securityText']\n";
    public static final String profile_setting_edit_profile_right_icon_access_id="com.dometicapp:id/userProfile-EditProfileButton-cardIcon";
    public static final String profile_setting_edit_profile_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Edit Profile') or @content-desc='com.dometicapp:id/userProfile-EditProfileButton-cardTitle']\n";
    public static final String profile_setting_address_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Address') or @content-desc='com.dometicapp:id/userProfile-addressLabel']\n";
    public static final String profile_setting_mobile_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Mobile') or @content-desc='com.dometicapp:id/userProfile-phoneLabel']\n";
    public static final String profile_setting_email_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-mail') or @content-desc='com.dometicapp:id/userProfile-emailLabel']\n";
    public static final String profile_setting_name_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Name') or @content-desc='com.dometicapp:id/userProfile-nameLabel']\n";
    public static final String profile_setting_personal_information_text_xpath_or_operator =" //android.widget.TextView[contains(@text,'PERSONAL INFORMATION') or @content-desc='com.dometicapp:id/userProfile-personalInfoText']";
    public static final String profile_settings_right_icon_access_id = "com.dometicapp:id/userSettings-profile-cardIcon";
    public static final String Profile_header_text_expected = "PROFILE";
    public static final String Profile_profile_header_Text_xpath_or_operator = "//android.widget.TextView[contains(@text,'PROFILE') or @content-desc='com.dometicapp:id/header-TitleText']\n";
    public static final String Profile_photo_image_access_id = "com.dometicapp:id/userProfile-photo";
    public static final String view_and_edit_setting_access_id = "com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String App_setting_app_verion_name_card_title="com.dometicapp:id/setting-versionText";
    public static final String App_setting_app_right_icon_access_id="com.dometicapp:id/setting-languageExpandIcon";
    public static final String App_setting_app_setting_main_page_card_title_access_id="com.dometicapp:id/header-TitleText";
    public static final String App_setting_app_setting_language_card_title_access_id="com.dometicapp:id/setting-languageText";

    public static final String Subscriptions_Navigation_icon_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/userSettings-subscriptions-cardIcon\"]\n";
    public static final String Subscriptions_Navigation_icon_access_id = "com.dometicapp:id/userSettings-subscriptions-cardIcon";
    public static final String Subscriptions_title_text_expected = "SUBSCRIPTIONS";
    public static final String Subscriptions_title_text_xpath_or_operator = " //android.widget.TextView[contains(@text,'SUBSCRIPTIONS') or @content-desc='com.dometicapp:id/header-TitleText']\n";
    public static final String Subscriptions_Back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";

    public static final String ManageNotifications_title_xpath_or_operator = "//android.widget.TextView[contains(@text,'MANAGE NOTIFICATIONS') or @content-desc='com.dometicapp:id/NotificationScreen-header-centerTitleText']\n";
    public static final String ManageNotifications_back_button_access_id = "com.dometicapp:id/NotificationScreen-leftButtonImage";
    public static final String ManageNotifications_logo_access_id = "com.dometicapp:id/notification-header-icon";
    public static final String ManageNotifications_Global_settings_xpath_or_operator = "//android.widget.TextView[contains(@text,'Global settings') or\t @content-desc='com.dometicapp:id/notification-header-text']\n";
    public static final String ManageNotifications_Push_Notifications_access_id = "";
    public static final String ManageNotifications_PushNotifications_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Push notifications') or @content-desc='com.dometicapp:id/notification-pushNotificationContainer-Container']\n";
    public static final String ManageNotifications_PushNotifications_toggle_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-pushNotificationContainer-Switch\"]";
    public static final String Manage_Notifications_Email_show_less_text_xpath="//android.widget.TextView[@content-desc='com.dometicapp:id/notification-pushNotificationContainer-Expandable-label']";
    public static final String Manage_Notifications_Email_Alerts_text_xpath="";
    public static final String push_notifications_show_more_text_expected = "Show more";
    public static final String push_notifications_show_more_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show more') or @content-desc='com.dometicapp:id/notification-pushNotificationContainer-Expandable-label']";
    public static final String push_notifications_show_more_text_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Expandable-label";
    public static final String ManageNotifications_push_show_more_text_access_id =  "com.dometicapp:id/notification-pushNotificationShowMore-cardTitle";
    public static final String ManageNotifications_push_show_more_text_navigation_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Expandable-icon";
    public static final String ManageNotifications_push_show_more_text_navigation_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-pushNotificationContainer-Expandable-icon\"]";
    public static final String ManageNotifications_push_show_less_text_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-cardTitle";
    public static final String ManageNotifications_push_show_less_navigation_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Expandable-icon";
    public static final String ManageNotifications_push_alerts_text_access_id = "com.dometicapp:id/notification-pushNotificationAlertText";
    public static final String ManageNotifications_push_warnings_text_access_id = "com.dometicapp:id/notification-pushNotificationWarningText";
    public static final String ManageNotifications_push_warnings_toggle_access_id =  "com.dometicapp:id/notification-pushNotificationWarningSwitch";
    public static final String ManageNotifications_push_alerts_text_xpath_or_operator =  "//*[contains(@text,'Alerts') or  @content-desc='com.dometicapp:id/notification-pushNotificationAlertText']\n";
    public static final String ManageNotifications_push_alerts_toggle_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-pushNotificationAlertSwitch\"]";
    public static final String ManageNotifications_push_alerts_toggle_access_id="com.dometicapp:id/notification-pushNotificationAlertSwitch";
    public static final String ManageNotifications_push_warnings_text_xpath_or_operator = "//*[contains(@text,'Warnings') or  @content-desc='com.dometicapp:id/notification-pushNotificationWarningText']\n";
    public static final String ManageNotifications_push_warnings_toggle_xpath =  "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-pushNotificationWarningSwitch\"]";
    public static final String ManageNotifications_Email_list_header_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-MAIL LIST') or  @content-desc='com.dometicapp:id/editList-header-header-centerTitleText']\n";
    public static final String ManageNotifications_Email_account_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-MAIL (ACCOUNT)') or  @content-desc='com.dometicapp:id/editList-mainAccount-title-text']";
    public static final String ManageNotifications_Additional_email_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'ADDITIONAL E-MAILS') or  @content-desc='com.dometicapp:id/editList-aditionalAccounts-title-text']\n";
    public static final String ManageNotifications_SMS_list_Mobile_account_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'MOBILE (ACCOUNT)') or  @content-desc='com.dometicapp:id/editList-mainAccount-title-text']\n";
    public static final String ManageNotifications_SMS_Additional_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'ADDITIONAL SMS') or  @content-desc='com.dometicapp:id/editList-aditionalAccounts-title-text']";
    public static final String ManageNotifications_SMS_List_title_text_xpath_or_operator = " //android.widget.TextView[contains(@text,'SMS LIST') or  @content-desc='com.dometicapp:id/editList-header-header-centerTitleText']\n";
    public static final String ManageNotifications_SMS_List_close_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-header-rightButtonIcon\"]\n";
    public static final String ManageNotifications_Edit_Email_add_new_button_access_id = "com.dometicapp:id/editList-addElement-icon";
    public static final String ManageNotifications_Edit_Email_element_1_access_id = "com.dometicapp:id/editListElement1-subtitleInput";
    public static final String ManageNotifcations_Edit_Email_label_1_access_id = "com.dometicapp:id/editListElement1-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_2_access_id = "com.dometicapp:id/editListElement2-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_2_access_id = "com.dometicapp:id/editListElement2-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_3_access_id = "com.dometicapp:id/editListElement3-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_3_access_id = "com.dometicapp:id/editListElement3-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_4_access_id = "com.dometicapp:id/editListElement4-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_4_access_id = "com.dometicapp:id/editListElement4-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_5_access_id = "com.dometicapp:id/editListElement5-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_5_access_id = "com.dometicapp:id/editListElement5-titleInput";
    public static final String ManageNotifications_Edit_Email_valid_input = "srinidi98@yopmail.com";
    public static final String ManageNotifications_Edit_Email_label_valid_input = "Srinidi";
    public static final String ManageNotifications_Edit_Email_invalid_input = "$%&*()@";
    public static final String ManageNotifications_Edit_Email_label_invalid_input = "^^^^^";
    public static final String ManageNotifications_edit_smslist_add_button_access_id = "com.dometicapp:id/editList-addElement-icon";
    public static final String ManageNotifications_edit_smslist_add_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-addElement-icon\"]";
    public static final String ManageNotifications_edit_smslist_save_button_text_xpath_or_operator =  "//android.widget.TextView[contains(@text,'Save') or  @content-desc='com.dometicapp:id/editList-save-button-text']\n";
    public static final String ManageNotifications_Invalid_error_message_access_id = "com.dometicapp:id/editListElement2-subtitleValidation";
    public static final String ManageNotifications_Mobile_number_1_value_access_id = "com.dometicapp:id/editListElement1-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_1_access_id = "com.dometicapp:id/editListElement1-titleInput";
    public static final String ManageNotifications_Mobile_number_2_value_access_id = "com.dometicapp:id/editListElement2-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_2_access_id = "com.dometicapp:id/editListElement2-titleInput";
    public static final String ManageNotifications_Mobile_number_3_value_access_id = "com.dometicapp:id/editListElement3-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_3_access_id = "com.dometicapp:id/editListElement3-titleInput";
    public static final String ManageNotifications_Mobile_number_4_value_access_id = "com.dometicapp:id/editListElement4-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_4_access_id = "com.dometicapp:id/editListElement4-titleInput";
    public static final String ManageNotifications_Mobile_number_5_value_access_id = "com.dometicapp:id/editListElement5-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_5_access_id = "com.dometicapp:id/editListElement5-titleInput";

    //-----------------manage notifications-advanced-xpath-------------------------//
    public static final String ManageNotifications_Advanced_Temperature_Alerts_text_xpath = "//android.view.ViewGroup[@content-desc=\"TemperatureAlerts\"]/android.view.ViewGroup[1]/android.widget.TextView";
    public static final String ManageNotifications_Advanced_Temperature_show_more_text_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-cardTitle\"])[3]";
    public static final String ManageNotifications_Advanced_Temperature_show_more_navigation_button_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-expandIcon\"])[3]";
    public static final String ManageNotifications_Advanced_Temperature_toggle_button_xpath = "(//android.view.ViewGroup[@content-desc=\"undefined-switchComponent\"])[3]";
    public static final String ManageNotifications_Advanced_Temperature_text_xpath = "(//android.widget.TextView[@content-desc=\"undefined-cardTitle\"])[3]";
    public static final String ManageNotifications_Advanced_Batteries_Alerts_text_xpath = "//android.view.ViewGroup[@content-desc=\"BatteriesAlerts\"]/android.view.ViewGroup[1]/android.widget.TextView";
    public static final String ManageNotifications_Advanced_Batteries_show_less_navigation_button_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-expandIcon\"])[2]";
    public static final String ManageNotifications_Advanced_Batteries_show_less_text_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-cardTitle\"])[2]";
    public static final String ManageNotifications_Advanced_Batteries_show_more_text_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-cardTitle\"])[2]";
    public static final String ManageNotifications_Advanced_Batteries_show_more_navigation_button_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-expandIcon\"])[2]";
    public static final String ManageNotifications_Advanced_Batteries_toggle_button_xpath = "(//android.view.ViewGroup[@content-desc=\"undefined-switchComponent\"])[2]";
    public static final String ManageNotifications_Advanced_Batteries_text_xpath = "(//android.widget.TextView[@content-desc=\"undefined-cardTitle\"])[2]";
    public static final String ManageNotifications_Advanced_Tanks_Alerts_xpath = "//android.view.ViewGroup[@content-desc=\"TanksAlerts\"]/android.view.ViewGroup[1]/android.widget.TextView";
    public static final String ManageNotifications_Advanced_Tank_show_more_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-cardTitle\"])[1]";
    public static final String ManageNotifications_Advanced_Tank_show_more_navigation_button_xpath = "(//android.widget.TextView[@content-desc=\"ELEMENT-expandIcon\"])[1]";
    public static final String ManageNotifications_Advanced_Tank_toggle_xpath = "(//android.view.ViewGroup[@content-desc=\"undefined-switchComponent\"])[1]";
    public static final String ManageNotifications_Advanced_Tank_text_xpath = "(//android.widget.TextView[@content-desc=\"undefined-cardTitle\"])[1]";
    public static final String ManageNotifications_push_show_less_text_xpath_or_operator = "//*[contains(@text,'Show less') or @content-desc='com.dometicapp:id/notification-pushNotificationContainer-Expandable-label']";
    public static final String ManageNotifications_showless_dropdown_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-emailNotification-Expandable-icon\"]\n";
    public static final String ManageNotifications_EmailList_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-MAIL LIST') or  @content-desc='com.dometicapp:id/notification-emailList-listTitle']";
    public static final String ManageNotifications_showless_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show less') or  @content-desc='com.dometicapp:id/notification-emailNotification-Expandable-label']\n";
    //----------------------SDB Guest pin list-----------------//
    public static final String Device_management_guest_pin_list_header_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Device_management_guest_pin_list_edit_button_text_access_id="com.dometicapp:id/header-rightButtonText";
    public static final String Device_management_guest_pin_list_back_symbol_access_id="com.dometicapp:id/header-leftButtonImage";
    public static final String Device_management_Edit_Guest_list_header_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Device_management_Edit_Guest_list_close_button_text_access_id="com.dometicapp:id/header-leftButtonImage";
    public static final String Device_management_Edit_Guest_list_add_button_access_id="com.dometicapp:id/editGuestListScreen-addPinButtonImage";
    public static final String Device_management_Edit_Guest_list_add_new_text_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/editGuestListScreen-addPinButton]/android.widget.TextView'";
    public static final String Device_management_Edit_pin_header_text_tile_access_id="com.dometicapp:id/header-TitleText";
    public static final String Device_management_Edit_pin_close_button_access_id="com.dometicapp:id/header-leftButtonImage";
    public static final String Device_management_Edit_pin_Pin_name_access_id="com.dometicapp:id/addGuestPinScreen-pinNameLabel";
    public static final String Device_management_Edit_pin_code_access_id="com.dometicapp:id/addGuestPinScreen-pinCodeLabel";
    public static final String Device_management_mail_box_xpath="(//*[@content-desc='com.dometicapp:id/addGuestPinScreen-deviceName-0'])[1]";
    public static final String Device_management_mail_box_toggel_button_xpath="(//*[@content-desc='com.dometicapp:id/addGuestPinScreen-deviceName-0'])[2]";
    public static final String Device_manegement_refrigerated_text_xpth="(//*[@content-desc='com.dometicapp:id/addGuestPinScreen-deviceName-1'])[1]";
    public static final String Device_manegement_refrigerated_toggel_button_xpath="(//*[@content-desc='com.dometicapp:id/addGuestPinScreen-deviceName-1'])[2]";
    public static final String Device_manegement_edit_name_text_enter_access_id="com.dometicapp:id/addGuestPinScreen-pinNameValue";
    public static final String Device_manegement_edit_pin_code_enter_access_id="com.dometicapp:id/addGuestPinScreen-pinCodeValue";
    public static final String Device_manegement_edit_pin_page_save_button_access_id="com.dometicapp:id/addGuestPinScreen-saveButton";
    public static final String Device_manegement_first_guestpin_toggel_button="com.dometicapp:id/guestListScreen-deviceButton-0";
    public static final String Device_manegement_second_guestpin_toggel_button="com.dometicapp:id/guestListScreen-deviceButton-1";
    public static final String Device_Management_empty_error_message_xpath =  "//*[@text='Vessel name should not be empty']";
    public static final String ManageNotifications_Edit_Email_remove_access_id = "com.dometicapp:id/editListElement4-removeIcon";
    public static final String ManageNotifications_Edit_Email_save_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-save-button\"]";
    public static final String ManageNotifications_Edit_SMS_List_save_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-save-button\"]";
    public static final String ManageNotifications_Edit_Email_close_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-header-rightButtonIcon\"]";
    public static final String ManageNotifications_Edit_Email_delete_relative_xpath = "//*[contains(@content-desc,'-removeIcon')]";
    public static final String ManageNotifications_Email_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-mail') or  @content-desc='com.dometicapp:id/notification-emailNotification-Title']\n";
    public static final String ManageNotifications_Email_toggle_access_id =  "com.dometicapp:id/notification-emailNotification-Switch";
    public static final String ManageNotifications_Email_showmore_text_xpath_or_operator =   "//android.widget.TextView[contains(@text,'Show more') or  @content-desc='com.dometicapp:id/notification-emailNotification-Expandable-label']\n";
    public static final String ManageNotifications_email_showmore_navigation_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-emailNotification-Expandable-icon\"]";
    public static final String ManageNotifications_EmailList_text_access_id =  "//android.widget.ScrollView[@content-desc=\"com.dometicapp:id/notification-scrollView\"]/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup[1]/android.widget.TextView";
    public static final String ManageNotifications_EmailList_label_text_1_access_id = "undefinedElement0-Text";
    public static final String ManageNotifications_EmailList_Email_1_access_id =  "undefinedElement0-Subtext";
    public static final String ManageNotifications_EmailList_1_toggle_access_id = "undefinedElement0-Switch";
    public static final String ManageNotifications_EmailList_label_text_2_access_id = "undefinedElement1-Text";
    public static final String ManageNotifications_EmailList_Email_2_access_id = "undefinedElement1-Subtext";
    public static final String ManageNotifications_EmailList_2_toggle_access_id = "undefinedElement1-Switch";
    public static final String ManageNotifications_EmailList_3_toggle_access_id = "undefinedElement2-Switch";
    public static final String ManageNotifications_EmailList_Email_3_access_id = "undefinedElement2-Subtext";
    public static final String ManageNotifications_EmailList_label_text_3_access_id = "undefinedElement2-Text";
    public static final String ManageNotifications_EmailList_4_toggle_access_id = "undefinedElement3-Switch";
    public static final String ManageNotifications_EmailList_Email_4_access_id = "undefinedElement3-Subtext";
    public static final String ManageNotifications_EmailList_label_text_4_access_id =  "undefinedElement3-Text";
    public static final String ManageNotifications_EmailList_5_toggle_access_id = "undefinedElement4-Switch";
    public static final String ManageNotifications_EmailList_Email_5_access_id = "undefinedElement4-Subtext";
    public static final String ManageNotifications_EmailList_label_text_5_access_id = "undefinedElement4-Text";
    public static final String ManageNotifications_EmailList_email_text_access_id = "";
    public static final String ManageNotifications_editlist_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Edit list') or  @content-desc='com.dometicapp:id/notification-emailList-subTitle']\n";
    public static final String ManageNotifications_editlist_navigation_xpath = "//android.widget.TextView[@content-desc=\"com.dometicapp:id/notification-emailList-expandIcon\"]";
    public static final String ManageNotifications_editlist_text_access_id = "com.dometicapp:id/notification-emailList-subTitle";
    public static final String ManageNotifications_email_alerts_toggle_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-emailNotificationAlertSwitch\"]";
    public static final String ManageNotifications_email_warnings_toggle_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-emailNotificationWarningContainerSwitch\"]";
    public static final String ManageNotifications_email_alerts_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Alerts') or  @content-desc='com.dometicapp:id/notification-emailNotificationAlertText']\n";
    public static final String ManageNotifications_email_warnings_text_xpath_or_operator =  "//android.widget.TextView[contains(@text,'Warnings') or  @content-desc='com.dometicapp:id/notification-emailNotificationWarningContainerText']";
    public static final String ManageNotifications_Email_showless_text_xpath = "(//android.widget.TextView[@content-desc=\"undefined-cardTitle\"])[1]";
    public static final String ManageNotifications_Email_showless_navigation_xpath = "(//android.widget.TextView[@content-desc=\"undefined-expandIcon\"])[1]";
    public static final String ManageNotifications_Edit_sms_save_button_xpath = "(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-save-button\"])[2]";
    public static final String ManageNotifications_Email_edit_list_toggle_access_id = "com.dometicapp:id/notification-emailList0-Switch";
    public static final String ManageNotifications_Email_Alerts_toggle_access_id = "com.dometicapp:id/notification-emailNotificationAlertSwitch";
    public static final String ManageNotifications_Email_Warnings_toggle_access_id = "com.dometicapp:id/notification-emailNotificationWarningContainerSwitch";
    public static final String ManageNotifications_Email_show_less_text_access_id = "com.dometicapp:id/notification-emailNotification-Expandable-label";
    public static final String ManageNotifications_Email_show_more_text_access_id = "com.dometicapp:id/notification-emailNotification-Expandable-label";
    public static final String ManageNotifications_Email_edit_list_Add_new_access_id = "com.dometicapp:id/editList-addElement-icon";
    public static final String ManageNotifications_Email_edit_list_first_email_access_id = "com.dometicapp:id/editListElement0-subtitleInput";
    public static final String ManageNotifications_Email_edit_list_first_email_label_access_id = "com.dometicapp:id/editListElement0-titleInput";
    public static final String ManageNotifications_Email_edit_list_first_email_disclaimer_access_id = "com.dometicapp:id/editListElement0-subtitleValidation";
    public static final String ManageNotifications_Email_edit_list_first_email_label_disclaimer_access_id = "com.dometicapp:id/editListElement0-titleValidation";
    public static final String ManageNotifications_Email_edit_list_save_button_access_id = "com.dometicapp:id/editList-save-button";
    public static final String ManageNotifications_Email_edit_list_delete_button_access_id = "com.dometicapp:id/editListElement0-removeIcon";

    public static final String ManageNotifications_email1_label_text_access_id = "com.dometicapp:id/notification-emailList0-Subtitle";
    public static final String ManageNotifications_email1_text_access_id = "com.dometicapp:id/notification-emailList0-Title";

    public static final String ManageNotifications_sms_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SMS') or  @content-desc='com.dometicapp:id/notification-smsNotification-Title']\n";
    public static final String ManageNotifications_sms_toggle_access_id =  "com.dometicapp:id/notification-smsNotification-Switch";
    public static final String ManageNotifications_sms_showmore_text_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-icon";
    public static final String ManageNotifications_SMS_showmore_text_xpath_or_operator = " //android.widget.TextView[contains(@text,'Show more') or  @content-desc='com.dometicapp:id/notification-smsNotification-Expandable-label']\n";
    public static final String ManageNotifications_sms_showmore_dropdown_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-icon";
    public static final String ManageNotifications_sms_showless_text_xpath_or_operator =  "//android.widget.TextView[contains(@text,'Show less') or  @content-desc='com.dometicapp:id/notification-smsNotification-Expandable-label']\n";
    public static final String ManageNotifications_sms_showless_dropdown_xpath =   "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-smsNotification-Expandable-icon\"]\n";
    public static final String ManageNotifications_sms_showless_dropdown_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-icon";
    public static final String SMS_list_text_expected = "SMS LIST";
    public static final String SMS_list_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SMS LIST') or  @content-desc='com.dometicapp:id/notification-smsList-listTitle']";
    public static final String ManageNotifications_sms_show_less_text_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-label";
    public static final String ManageNotifications_sms_smslist_text_xpath =  "//android.widget.ScrollView[@content-desc=\"com.dometicapp:id/notification-scrollView\"]/android.view.ViewGroup/android.view.ViewGroup[8]/android.view.ViewGroup[1]/android.widget.TextView";
    public static final String ManageNotifications_sms_smslist_label_text_1_access_id =  "undefinedElement0-Text";
    public static final String ManageNotifications_sms_smslist_number_1_access_id = "undefinedElement0-Subtext";
    public static final String ManageNotifications_sms_smslist_1_toggle_access_id =  "undefinedElement0-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_2_access_id = "undefinedElement1-Text";
    public static final String ManageNotifications_sms_smslist_number_2_access_id = "undefinedElement1-Subtext";
    public static final String ManageNotifications_sms_smslist_2_toggle_access_id = "undefinedElement1-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_3_access_id = "undefinedElement2-Text";
    public static final String ManageNotifications_sms_smslist_number_3_access_id = "undefinedElement2-Subtext";
    public static final String ManageNotifications_sms_smslist_3_toggle_access_id = "undefinedElement2-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_4_access_id = "undefinedElement3-Text";
    public static final String ManageNotifications_sms_smslist_number_4_access_id = "undefinedElement3-Subtext";
    public static final String ManageNotifications_sms_smslist_4_toggle_access_id = "undefinedElement3-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_5_access_id = "undefinedElement4-Text";
    public static final String ManageNotifications_sms_smslist_number_5_access_id = "undefinedElement4-Subtext";
    public static final String ManageNotifications_sms_smslist_5_toggle_access_id = "undefinedElement4-Switch";
    public static final String ManageNotifications_sms_smslist_editlist_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Edit list') or  @content-desc='com.dometicapp:id/notification-smsList-subTitle']\n";
    public static final String ManageNotifications_sms_smslist_editlist_naviagtion_xpath = "//android.widget.TextView[@content-desc=\"com.dometicapp:id/notification-smsList-expandIcon\"]";
    public static final String ManageNotifications_sms_alerts_text_xpath_or_operator=  "//android.widget.TextView[contains(@text,'Alerts') or  @content-desc='com.dometicapp:id/notification-smsNotificationAlertText'] \n";
    public static final String ManageNotifications_sms_warnings_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Warnings') or  @content-desc='com.dometicapp:id/notification-smsNotificationWarningText']\n";
    public static final String ManageNotifications_sms_warnings_toggle_button_xpath =  "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-smsNotificationWarningSwitch\"]";
    public static final String ManageNotifications_sms_alerts_toggle_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-smsNotificationAlertSwitch\"]";
    public static final String ManageNotifications_sms_editlist_remove_icon_access_id = "com.dometicapp:id/editListElement1-removeIcon";
    public static final String Advanced_text_expected = "ADVANCED";
    public static final String Advanced_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'ADVANCED') or @content-desc='com.dometicapp:id/notification-advanceText']";
    public static final String SMS_Advanced_Notification_icon_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-AdvancedNotificationSettings-deviceicon-icon\"]\n";
    public static final String Advanced_SDB_text_expected = "SDB";
    public static final String Advanced_SDB_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SDB') or @content-desc='com.dometicapp:id/notification-AdvancedNotificationSettings--Title']";
    public static final String SMS_Advanced_navigation_icon_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-AdvancedNotificationSettings--Container\"]/android.view.ViewGroup[3]\n";

    public static final String ManageNotifications_sms_list_toggle_access_id = "com.dometicapp:id/notification-smsList0-Switch";
    public static final String ManageNotifications_sms_alerts_toggle_button_access_id = "com.dometicapp:id/notification-smsNotificationAlertSwitch";
    public static final String ManageNotifications_sms_warnings_toggle_button_access_id = "com.dometicapp:id/notification-smsNotificationWarningSwitch";
    public static final String ManageNotifications_sms_editlist_number1_input_access_id = "com.dometicapp:id/editListElement0-subtitleInput";
    public static final String ManageNotifications_sms_editlist_label1_input_access_id = "com.dometicapp:id/editListElement0-titleInput";
    public static final String ManageNotifications_sms_editlist_delete_button_access_id = "com.dometicapp:id/editListElement0-removeIcon";
    public static final String ManageNotifications_sms_show_more_text_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-label";
    public static final String ManageNotifications_sms_editlist_access_id = "com.dometicapp:id/notification-smsList-subTitle";
    public static final String SMS_edit_list_Mob_number_disclaimer_access_id = "com.dometicapp:id/editListElement0-subtitleValidation";
    public static final String SMS_edit_list_Label_disclaimer_access_id = "com.dometicapp:id/editListElement0-titleValidation";
    public static final String SMS_edit_list_close_button_access_id = "com.dometicapp:id/editList-header-rightButtonIcon";
    public static final String SMS_edit_list_save_button_access_id = "com.dometicapp:id/editList-save-button";

    public static final String ManageNotifications_SMS1_label_text_access_id = "com.dometicapp:id/notification-smsList0-Title";
    public static final String ManageNotifications_SMS1_number_access_id = "com.dometicapp:id/notification-smsList0-Subtitle";
    public static final String ManageNotifications_SMS1_toggle_access_id = "com.dometicapp:id/notification-smsList0-Switch";
    public static final String SMS_edit_list_delete_icon_access_id = "com.dometicapp:id/editListElement0-removeIcon";

    // -------------------Data-----------------------------//
    public static final String Settings_viewEditButtonText="View/Edit Account";
    public static final String Settings_home_text="Home";
    public static final String Settings_notificationSettings_text="Notification Settings";
    public static final String Settings_deviceMangagement_text="Device Management";
    public static final String Settings_appSettings_text="App Settings";
    public static final String Settings_Logout_text="Logout";
    public static final String Settings_Version_16_text="Version 1.7.4";
    public static final String Device_manegement_Mail_id="Upper compartment";
    public static final String Device_manegement_refrigerated="Lower compartment";
    public static final String Device_manegement_edit_name_text="Dometic1234";
    public static final String Device_manegement_edit_pin_name_text="Dometic";
    public static final String Device_manegement_edit_pin_number="12345";
    public static final String Device_management_edit_pin_name_special_charater="Dome@234##)";
    public static final String Device_manegement_edit_pin_combination="12345";
    public static final String Device_management_edit_pin_name_long_lenght_charater="Dome@234##124&8987teqqg787abcdefg)";
    public static final String Device_manegement_edit_pin_long_lenght_combination="34679";
    public static final String Device_management_edit_pin_name_short_lenght="Dome";
    public static final String Device_management_edit_pin_short_lenght="12345";
    public static final String Device_management_invalid_device_name = "&^%%$^%$";
    public static final String Device_management_valid_device_name = "SDB";
    public static final String Device_Management_Empty_string_message = "Vessel name should not be empty";
    public static final String Device_management_edit_save_button="Save";
    public static final String Device_Management_edit_save_option = "Save";
    public static final String Device_manegement_cooler_setting_header_main_text="Cooler settings";
    public static final String Device_manegement_cooler_setting_header_text="COOLER SETTINGS";
    public static final String Device_manegement_cooler_setting_scheduler_card_title="Cooler status";
    public static final String Device_manegement_cooler_setting_scheduler_card="Scheduler";
    public static final String Device_manegement_cooler_setting_scheduler_at="Scheduler at";
    public static final String Device_manegement_cooler_setting_Temperature="Temperature";
    public static final String Settings_english_language="English";
    public static final String ManageNotifications_text = "MANAGE NOTIFICATIONS";
    public static final String ManageNotifications_Global_settings_text = "Global settings";
    public static final String ManageNotifications_PushNotifications_text = "Push notifications";
    public static final String ManageNotifications_show_more_text = "Show more";
    public static final String ManageNotifications_show_less_text = "Show less";
    public static final String ManageNotifications_push_alerts_text = "Alerts";
    public static final String ManageNotifications_SMS_alerts_text = "Alerts";
    public static final String ManageNotifications_push_warnings_text = "Warnings";
    public static final String ManageNotifications_SMS_warnings_text = "Warnings";
    public static final String ManageNotifications_Email_warnings_text = "Warnings";
    public static final String ManageNotifications_Advanced_text = "ADVANCED";
    public static final String ManageNotifications_Email_text = "E-mail";
    public static final String ManageNotifications_Email_list_text = "E-MAIL LIST";
    public static final String ManageNotifications_Email_edit_list_text = "Edit list";
    public static final String ManageNotifications_Email_account_text = "E-MAIL (ACCOUNT)";
    public static final String ManageNotifications_Additional_Email_text = "ADDITIONAL E-MAILS";
    public static final String ManageNotifications_save_button_text = "Save";
    public static final String ManageNotifications_SMS_text = "SMS";
    public static final String ManageNotifications_SMS_list_text = "SMS LIST";
    public static final String ManageNotifications_SMS_list_Mobile_account_text = "MOBILE (ACCOUNT)";
    public static final String ManageNotifications_SMS_list_Additional_SMS_text = "ADDITIONAL SMS";
    public static final String ManageNotifications_SMS_invalid_number_toast_message = "The phone 2 must be a valid phone number.";

    public static final String ManageNotifications_Advanced_alerts_text = "ALERTS";
    public static final String ManageNotifications_Advanced_Batteries_text = "Batteries";
    public static final String ManageNotifications_Advanced_Tanks_text = "Tanks";
    public static final String ManageNotifications_Advanced_Temperature_text = "Temperature";

    public static final String Settings_english_language_LANGUAGE_text="Language";
    public static final String profile_main_screen_renew="Renew";
    public static final String profile_main_screen_Password="Password";
    public static final String profile_main_screen_SECURITY="SECURITY";
    public static final String profile_main_screen_Adderess="Address";
    public static final String profile_main_screen_Edit_profile="Edit Profile";
    public static final String profile_main_screen_PERSONAL_INFORMATION="PERSONAL INFORMATION";
    public static final String profile_main_screen_Name="Name";
    public static final String profile_main_screen_Email="E-mail";
    public static final String profile_main_screen_Mobile="Mobile";
    public static final String ManageNotifications_valid_mobile_number = "9842252955";
    public static final String ManageNotifications_sms_valid_label_name = "srinidi";
    public static final String ManageNotifications_invalid_mobile_number = "83560437586574865874567403984";
    public static final String ManageNotifications_sms_invalid_label_name = "#$%%^&^*^&";
    public static final String ManageNotifications_sms_unique_label_name = "contact";
    public static final String Temperature_settings_scheduler_header="SCHEDULER";
    public static final String Temperature_settings_temperature_threshold="Temperature threshold";
    public static final String Temperature_settings_temperature_alert="TEMPERATURE ALERT";
    public static final String Temperature_settings_lower_compartment="Lower compartment";
    public static final String Temperature_settings_current_temperature="CURRENT TEMPERATURE";
    public static final String Temperature_settings_outside="Outside";
    public static final String Temperature_settings_Temperature_header_TitleText="TEMPERATURE SETTINGS";
    public static final String Temperature_settings_scheduler="Scheduler";
    public static final String Temperature_settings_temperature_control="Temperature control";
    public static final String Device_Management_special_character_error_message ="Vessel name cannot include special characters";
    public static final String Device_Management_empty_error_message = "Vessel name should not be empty";

    public static final String Settings_viewEditButtonText_xpath_OR_operator ="//android.widget.TextView[contains(@text,'View/Edit Account') or @content-desc=\"com.dometicapp:id/sidemenu-viewEditButtonText\"]";
    public static final String Settings_home_text_xpath_OR_operator ="//android.widget.TextView[contains(@text,'Home') or @content-desc=\"com.dometicapp:id/sidemenu-home-text\"]";
    public static final String Settings_notificationSettings_text_xpath_OR_operator ="//android.widget.TextView[contains(@text,'Notification Settings') or @content-desc=\"com.dometicapp:id/sidemenu-notificationSettings-text\"]";
    public static final String Settings_deviceMangagement_text_xpath_OR_operator ="//android.widget.TextView[contains(@text,'Device Management') or @content-desc=\"com.dometicapp:id/sidemenu-deviceMangagement-text\"]";
    public static final String Settings_appSettings_text_xpath_OR_operator ="//android.widget.TextView[contains(@text,'App Settings') or @content-desc=\"com.dometicapp:id/sidemenu-appSettings-text\"]";
    public static final String Settings_Logout_text_xpath_OR_operator ="//android.widget.TextView[contains(@text,'Logout') or @content-desc=\"com.dometicapp:id/sidemenu-logout-text\"]";
    public static final String Settings_Version_16_text_xpath_OR_operator ="//android.widget.TextView[contains(@text,'Version 1.6') or @content-desc=\"com.dometicapp:id/sidemenu-versionText\"]";
    public static final String App_settings_header_xpath_OR_operator = "//android.widget.TextView[contains(@text,'APP SETTINGS') or @content-desc=\"com.dometicapp:id/header-TitleText\"]";
    public static final String Language_text_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/setting-languageText\"])[1]";
    public static final String Settings_AccountSettings_Settings_text="SETTINGS";
    public static final String Settings_AccountSettings_profile_Settings_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'SETTINGS') or @content-desc='com.dometicapp:id/userSettings-settingText']";
    public static final String Selected_Language_text_German_xpath_OR_operator = "//android.widget.TextView[contains(@text,'German') or @content-desc=\"com.dometicapp:id/setting-selectedLanguage\"]";
    public static final String Language_navigation_button_access_id = "com.dometicapp:id/setting-languageExpandIcon";
    public static final String Language_header_xpath_OR_operator = "//android.widget.TextView[contains(@text,'LANGUAGE') or @content-desc=\"com.dometicapp:id/header-TitleText\"]";
    public static final String Temperature_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Temperature') or @content-desc=\"com.dometicapp:id/setting-temperatureContainer\"]";
    public static final String Devicemanagement_back="com.dometicapp:id/DeviceManagementScreen-leftButtonImage";
    public static final String Temperature_Celsius_unit_access_id = "com.dometicapp:id/setting-celsiusText";
    public static final String Temperature_Fahrenheit_unit_access_id = "com.dometicapp:id/setting-fahrenheitText";
    public static final String Firmware_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Firmware')]";
    public static final String Firmware_text_access_id = "com.dometicapp:id/setting-languageText";
    public static final String App_version_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'App version') or @content-desc=\"com.dometicapp:id/setting-versionText\"]";
    public static final String Version_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Version 1.6') or @content-desc=\"com.dometicapp:id/setting-versionValue\"]";
    public static final String Language_English_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'English') or @content-desc=\"com.dometicapp:id/language-english-cardTitle\"]";
    public static final String Language_German_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'German') or @content-desc=\"com.dometicapp:id/language-german-cardTitle\"]";
    public static final String Language_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String Account_settings_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String App_settings_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String Manage_notifications_back_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/NotificationScreen-leftButtonImage\"]";
    public static final String Device_management_back_button_access_id = "com.dometicapp:id/DeviceManagementScreen-leftButtonImage";

    public static final String App_settings = "APP SETTINGS";
    public static final String Language_text = "Language";
    public static final String Language_header_text = "LANGUAGE";
    public static final String English_text = "English";
    public static final String German_text = "German";
    public static final String Temperature_text = "Temperature";
    public static final String Firmware_text = "Firmware";
    public static final String App_version_text = "App version";
    public static final String Email_warning_text = "com.dometicapp:id/editListElement0-subtitleValidation";
    public static final String Label_warning_text = "com.dometicapp:id/editListElement0-titleValidation";
    public static final String empty_string = "";
    public static final String empty_label = "";
    public static final String special_characters = "!@#$%%^&*(!*)";
    public static final String smileys = "\uD83E\uDD29\uD83E\uDD29\uD83E\uDD29\uD83D\uDC4C\uD83E\uDD29";
    public static final String Label_text = "Test";
    public static final String Valid_email = "testdom@gmail.com";
    public static final String Valid_number = "+441234567890";

    public static final String Settings_AccountSettings_profile_cardicon_accessid="com.dometicapp:id/userSettings-profile-cardIcon";
    public static final String Settings_AccountSettings_Subscription_cardicon_accessid="com.dometicapp:id/userSettings-subscriptions-cardIcon";
}
