package com.dometic.SDB.qa.Pages;

public class Constant_climate_ac {
    // ------------Accessibility_id------------------//
    public static final String CAC_M_Climate_Text_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String CAC_M_Climate_Text_expetecd="CLIMATE";
    public static final String CAC_M_Climate_0_mainContent="com.dometicapp:id/tiles-Climate-0-mainContent";
    public static final String CAC_M_Inside_Text_access_id =  "com.dometicapp:id/climate-insideTemp";
    public static final String CAC_M_Outside_Text_access_id = "com.dometicapp:id/climate-outsideTemp";
    public static final String CAC_M_Inside_Value_access_id = "com.dometicapp:id/climate-insideTempValue";
    public static final String CAC_M_Outside_Value_access_id = "com.dometicapp:id/climate-outsideTempValue";
    public static final String CAC_M_climate_powerContainer_access_id="com.dometicapp:id/climate-powerContainer";
    public static final String CAC_M_climate_apply_button_access_id="com.dometicapp:id/climate-applyTemperature";
    public static final String CAC_M_climate_temperatureContainer_access_id="com.dometicapp:id/climate-temperatureContainer";
    public static String CAC_M_climate_acModeContainer_access_id="com.dometicapp:id/climate-acModeContainer";
    public static String CAC_M_climate_fanSpeedContainer_access_id="com.dometicapp:id/climate-fanSpeedContainer";
    public static final String CAC_M_Inside_Units_access_id = " com.dometicapp:id/climate-insideTempUnit";
    public static final String CAC_M_Minimum_Temperature_access_id="com.dometicapp:id/climate-tempValue-16-0";
    public static final String CAC_M_Maximum_Temperature_access_id="com.dometicapp:id/climate-tempValue-31-0";
    public static final String CAC_M_Outside_Units_access_id = "com.dometicapp:id/climate-outsideTempUnit";
    public static String CAC_M_power_powerScreen_houseBattery_access_id="com.dometicapp:id/powerScreen-houseBatteryText";
    public static String CAC_M_power_Back_Button_access_id="com.dometicapp:id/tiles-backImage";
    public static String CAC_M_power_Back_Button_access_id1="com.dometicapp:id/tiles-container";
    public static String WHT_Back_Button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String CAC_FanSpeed_text_access_id="com.dometicapp:id/climate-FanSpeed";
    public static String CAC_FanSpeed_icon_access_id="com.dometicapp:id/climate-fanIcon";
    public static String CAC_M_AC_Text_access_id = "com.dometicapp:id/climate-acText";
    public static String CAC_M_AC_Text_expected="AC";
    public static String CAC_M_Heater_Text_access_id = "com.dometicapp:id/climate-heaterText";
    public static String CAC_M_Heater_Text_expected="Heater";
    // public static final String CAC_M_Fan_Symbol_access_id = "com.dometicapp:id/climate-container ";
    public static final String CAC_M_Power_Text_top_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String CAC_M_Power_Back_button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String CAC_M_Power_Text_access_id = "com.dometicapp:id/climate-powerText";
    public static final String CAC_M_Power_Text_expected="Power";
    public static final String fanspeed_text_climatescreen="Fan Speed";
    public static final String climatemode_text_climatescreen="Climate Mode";
    public static final String climateags_text_climatescreen="Climate AGS";
    public static final String airconditioner_text_climatescreen="Air Conditioner";
    public static final String scheduler_text_climatescreen="Scheduler";
    public static final String CAC_M_Power_Button_access_id ="com.dometicapp:id/climate-powerToggle";
    public static final String CAC_M_Temp_Text_access_id = "com.dometicapp:id/climate-temperature";
    public static final String CAC_M_Temp_Text_expected="Temperature";
    public static final String CAC_M_Temp_Value_access_id = "com.dometicapp:id/climate-temperatureValue";
    public static final String CAC_M_AC_Heater_Button_access_id = "com.dometicapp:id/climate-selectedClimate";
    public static final String CAC_M_AC_Mode_Text_access_id = "com.dometicapp:id/climate-acModeText";
    public static final String CAC_M_AC_Mode_Navigation_access_id = "com.dometicapp:id/climate-acModeiconCollapse ";
    public static final String CAC_M_AC_Mode_Value_access_id = "com.dometicapp:id/climate-selectedMode";
    public static final String CAC_M_AC_FanSpeed_Text_access_id = "com.dometicapp:id/climate-fanSpeedText";
    public static final String CAC_M_AC_FanSpeed_Navigation_access_id = "com.dometicapp:id/climate-fanSpeediconCollapse";
    public static final String CAC_AM_Inside_Text_expected="Inside";
    public static final String CAC_AM_Outside_Text_expected="Outside";
    public static final String CAC_AM_ACMODE_Text_expected="AC MODE";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Auto="com.dometicapp:id/acMode-acmodeItemValue-Auto";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Auto_expected="Auto";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Heat="com.dometicapp:id/acMode-acmodeItemValue-Heat";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Heat_expected="Heat";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Fan="com.dometicapp:id/acMode-acmodeItemValue-Fan";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Fan_expected="Fan";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Cool="com.dometicapp:id/acMode-acmodeItemValue-Cool";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Cool_expected="Cool";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Dry="com.dometicapp:id/acMode-acmodeItemValue-Dry";
    public static final String CAC_AM_ACMODE_acmodeItemValue_Dry_expected="Dry";
    public static final String CAC_AM_Fanspeed_fanSpeedItemValue_Low="com.dometicapp:id/fanSpeed-fanSpeedItemValue-Low";
    public static final String CAC_AM_Fanspeed_fanSpeedItemValue_Medium="com.dometicapp:id/fanSpeed-fanSpeedItemValue-Medium";
    public static final String CAC_AM_Fanspeed_fanSpeedItemValue_High="com.dometicapp:id/fanSpeed-fanSpeedItemValue-High";
    public static final String CAC_AM_fanSpeedItemValue_Max="com.dometicapp:id/fanSpeed-fanSpeedItemValue-Max";
    public static final String CAC_AM_Inside_Text_access_id = "com.dometicapp:id/acMode-insideTemp";
    public static final String CAC_AM_Inside_Value_access_id = "com.dometicapp:id/acMode-insideTempValue";
    public static final String CAC_AM_Inside_Units_access_id = "com.dometicapp:id/acMode-insideTempUnit";
    public static final String CAC_AM_Outside_Text_access_id = "com.dometicapp:id/acMode-outsideTemp";
    public static final String CAC_AM_Outside_Value_access_id = "com.dometicapp:id/acMode-outsideTempValue";
    public static final String CAC_AM_Outside_Units_access_id =  "com.dometicapp:id/acMode-outsideTempUnit";
    public static final String CAC_AM_Temp_Value_access_id = "com.dometicapp:id/acMode-temperature";
    public static final String CAC_AM_Fan_Symbol_access_id = "com.dometicapp:id/acMode-fanIcon";
    public static final String CAC_AM_Fan_Value_access_id ="com.dometicapp:id/acMode-getAcFanSpeed";
    public static final String CAC_AM_AC_Mode_Title_access_id = "com.dometicapp:id/acMode-acmodeText";
    public static final String CAC_AM_Apply_Button_access_id = "com.dometicapp:id/acMode-applyButton";
    public static final String CAC_AFS_Apply_Button_access_id="com.dometicapp:id/fanSpeed-applyButton";
    public static final String CAC_AM_fanSpeed_fanspeedText="com.dometicapp:id/fanSpeed-fanspeedText";
    public static final String TFW_Water_Pump_access_id="com.dometicapp:id/Tank-waterPump";
    public static final String TFW_Fresh_Button_access_Id="com.dometicapp:id/Buttons-buttonsList-freshWater";
    public static final String TFW_predictive_Analytics_access_id="com.dometicapp:id/Tank-predictiveAnalytics";
    public static final String TFW_Back_Button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String CAC_AFS_Inside_Text_access_id = "com.dometicapp:id/fanSpeed-insideTemp";
    public static final String CAC_AFS_Inside_Value_access_id = "com.dometicapp:id/fanSpeed-insideTempValue";
    public static final String CAC_AFS_Inside_Units_access_id = "com.dometicapp:id/fanSpeed-insideTempUnit";
    public static final String CAC_AFS_Outside_Text_access_id = "com.dometicapp:id/fanSpeed-outsideTemp";
    public static final String CAC_AFS_Outside_Value_access_id = "com.dometicapp:id/fanSpeed-outsideTempValue";
    public static final String CAC_AFS_Outside_Units_access_id = "com.dometicapp:id/fanSpeed-outsideTempUnit";
    public static final String CAC_AFS_Temp_Value_access_id ="com.dometicapp:id/fanSpeed-temperature";
    public static final String CAC_AFS_Fan_Symbol_access_id = "com.dometicapp:id/fanSpeed-fanIcon";
    public static final String CAC_AFS_Fan_Value_access_id = "com.dometicapp:id/fanSpeed-getAcFanSpeed";
    public static final String CAC_AFS_AC_Mode_Title_access_id = "com.dometicapp:id/fanSpeed-fanspeedText";
    public static final String CAC_AFS_AC_Mode_Title_expected="AC FAN SPEED";
    public static final String CAC_powerScreen_currentContainer="com.dometicapp:id/powerScreen-currentContainer";
    public static final String CAC_powerScreen_timeContainer="com.dometicapp:id/powerScreen-timeContainer";
    public static final String CAC_powerScreen_powerSourceContainer="com.dometicapp:id/powerScreen-powerSourceContainer";
    public static final String L2CAC_power_toggle_access_id="";
    public static final String L2CAC_fanspeed_text_access_id="";
    public static final String L2CAC_fanspeed_value_access_id="";
    public static final String L2CAC_fanspeed_cardIcon_access_id="";
    public static final String L2CAC_Climatemode_text_access_id="";
    public static final String L2CAC_Climatemode_value_access_id="";
    public static final String L2CAC_ClimateAGS_text_access_id="";
    public static final String L2CAC_ClimateAGS_toggle_access_id="";
    public static final String L2CAC_Airconditioner_text_access_id="";
    public static final String L2CAC_Airconditioner_value_access_id="";
    public static final String L2CAC_Scheduler_text_access_id="";
    public static final String L2CAC_Scheduler_toggle_access_id="";
    public static final String L2CAC_Sleep_text_access_id="";
    public static final String L2CAC_Wake_text_access_id="";
    public static final String L2CAC_Away_text_access_id="";
    public static final String L2CAC_Return_text_access_id="";
    public static final String L2CAC_Scheduled_At_text_access_id="";
    public static final String L2CAC_Scheduled_At_value_access_id="";
    public static final String L2CAC_Scheduled_At_inside_SCHEDULED_AT_text_access_id="";
    public static final String L2CAC_Scheduled_At_inside_Apply_Button="com.dometicapp:id/scheduler-applyButton";
    //-----------------Needed Accessibility Id------------------//
    public static final String CAC_M_Title_access_id ="";
    public static final String CAC_M_navigation_button_access_id ="";
    public static final String CAC_M_Center_Carousel_access_id = "";
    public static final String CAC_M_Right_Carousel_access_id = "";
    public static final String CAC_M_Left_Carousel_access_id = "";
    public static final String CAC_M_Fan_Symbol_Value_access_id ="";
    public static final String CAC_M_AC_FanSpeed_Value_access_id="" ;
    public static final String CAC_AM_Title_access_id ="";
    public static final String CAC_AM_Navigation_access_id =  "";
    public static final String CAC_AM_Top_Carousel_Value_access_id = "";
    public static final String CAC_AM_Middle_Carousel_Value_access_id ="";
    public static final String CAC_AM_Bottom_Carousel_Value_access_id = "";
    public static final String CAC_AFS_Title_access_id="";
    public static final String CAC_AFS_Top_Carousel_Value_access_id="" ;
    public static final String CAC_AFS_Middle_Carousel_Value_access_id = "";
    public static final String CAC_AFS_Bottom_Carousel_Value_access_id = "";
    public static final String CAC_M_Apply_Button_access_id=" ";
    public static final String CAC_AFS_Navigation_access_id = "";

    // ----------------------------xPath---------------------//
    public static final String CAC_M_Title_xpath ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup[2]/android.widget.TextView ";
    public static final String CAC_M_navigation_button_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup[1]\n ";
    public static final String CAC_M_Center_Carousel_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/climate-temperatureArrayValue\"])[2] ";
    public static final String CAC_M_Right_Carousel_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/climate-temperatureArrayValue\"])[1]\n ";
    public static final String CAC_M_Left_Carousel_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/climate-temperatureArrayValue\"])[3]\n ";
    public static final String CAC_M_Fan_Symbol_Value_xpath ="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/climate-getAcFanSpeed\"])[2] ";
    public static final String CAC_M_AC_FanSpeed_Value_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/climate-getAcFanSpeed\"])[1] ";
    public static final String CAC_AM_Title_xpath ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup[2]/android.widget.TextView ";
    public static final String CAC_AM_Navigation_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup/android.widget.ImageView " ;
    public static final String CAC_AM_Top_Carousel_Value_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/acMode-acmodeItemValue\"])[1] ";
    public static final String CAC_AM_Middle_Carousel_Value_xpath ="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/acMode-acmodeItemValue\"])[2] ";
    public static final String CAC_AM_Bottom_Carousel_Value_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/acMode-acmodeItemValue\"])[3] ";
    public static final String CAC_AFS_Title_xpath ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup[2]/android.widget.TextView ";
    public static final String CAC_AFS_Apply_Button_xpath = "//*[@content-desc='com.dometicapp:id/fanSpeed-applyButton']";
    public static final String CAC_AFS_Top_Carousel_Value_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/fanSpeed-fanSpeedItemValue\"])[1] ";
    public static final String CAC_AFS_Middle_Carousel_Value_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/fanSpeed-fanSpeedItemValue\"])[2] ";
    public static final String CAC_AFS_Bottom_Carousel_Value_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/fanSpeed-fanSpeedItemValue\"])[3] ";
    public static final String CAC_M_Apply_Button_xpath="//android.widget.HorizontalScrollView[@content-desc=\"com.dometicapp:id/climate-temperatureArray\"]/android.view.ViewGroup/android.view.ViewGroup[2] ";
    public static final String CAC_AFS_Navigation_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup/android.widget.ImageView ";
    public static String CAC_M_Back_Button_xpath="//android.widget.Button[@content-desc=' , back']";
    public static String CAC_M_Apply_button_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/climate-applyTemperature']";
    public static final String CAC_M_climate_temperatureArray_xpath="//*[@content-desc='com.dometicapp:id/climate-temperatureArray']";
    public static final String CAC_M_climate_powerContainer_xpath="//*[@content-desc='com.dometicapp:id/climate-powerContainer']";
    public static final String CAC_M_climate_AC_fanspeed_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/climate-fanSpeedContainer']/android.view.ViewGroup";
    public static final String CAC_M_AC_mode_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/climate-acModeContainer']/android.view.ViewGroup";
    public static final String CAC_M_climate_Heat_source_xpath="(//*[@content-desc='com.dometicapp:id/climate-flatListComponent']//android.view.ViewGroup)[11]";
    public static final String CAC_M_climate_AGS_xpath="(//*[@content-desc='com.dometicapp:id/climate-flatListComponent']//android.view.ViewGroup)[15]";
    public static final String CAC_M_power_percentage_xpath="//android.widget.ScrollView[@content-desc='com.dometicapp:id/powerScreen-scrollView']/android.view.ViewGroup/android.view.ViewGroup";
    public static final String CAC_M_power_house_battery_inverter_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-flatListItem-undefined-0']/android.view.ViewGroup";
    public static final String CAC_M_power_house_battery_Operating_Mode_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-flatListItem-undefined-1']";
    public static final String CAC_M_power_house_battery_voltage_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-flatListItem-undefined-3']/android.view.ViewGroup";
    public static final String CAC_M_power_house_battery_load_wattage="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-flatListItem-undefined-4']";
    public static final String TFW_Tanks_Text_xpath="//*[@text='TANKS']";
    public static final String TFW_Fresh_Water_Level_Text_xpath="//*[@text='FRESH WATER LEVEL']";
    public static final String TFW_percentage_xpath="(//*[@index='2'])[1]";
    public static final String WHT_Water_Heater_Text_xpath="//*[@text='WATER HEATER']";
    public static final String WHT_Heater_xpath="(//*[@class='android.view.ViewGroup'])[13]";
    public static final String WHT_Status_text_xpath="(//*[@content-desc='com.dometicapp:id/trumaWaterHeater-waterHeaterStatusText'])[1]";
    public static final String WHT_Decalcification_text_xpath="//*[@content-desc='com.dometicapp:id/trumaWaterHeater-waterHeaterStatusValue']";
    public static final String WHT_Temperature_text_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/climate-temperatureContainer']";
    public static final String WHT_Battery_Voltage_xpath="//android.widget.ScrollView[@content-desc='com.dometicapp:id/powerScreen-scrollView']/android.view.ViewGroup/android.view.ViewGroup[1]";
    public static final String WHT_Battery_Current_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-currentContainer']";
    public static final String WHT_Time_xpath= "//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-timeContainer']";
    public static final String WHT_PowerSource="//android.view.ViewGroup[@content-desc='com.dometicapp:id/powerScreen-powerSourceContainer']";
    public static final String CAC_FanSpeed_icon_xpath="//android.widget.ImageView[@content-desc='com.dometicapp:id/climate-fanIcon']";
    public static final String CAC_M_AC_FanSpeed_Text_xpath="//android.widget.TextView[@content-desc='com.dometicapp:id/climate-fanSpeedText']";
    public static final String L2CAC_power_toggle_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/climate-powerContainer\"]/android.view.ViewGroup/android.view.ViewGroup";
    public static final String L2CAC_fanspeed_text_xpath="//*[@text='Fan Speed']";
    public static final String L2CAC_fanspeed_value_xpath="(//*[@content-desc='undefined-cardSubText'])[1]";
    public static final String L2CAC_fanspeed_cardIcon_xpath="(//android.view.ViewGroup[@content-desc=\"undefined-cardIcon\"])[1]";
    public static final String L2CAC_Climatemode_text_xpath="//*[@text='Climate Mode']";
    public static final String L2CAC_Climatemode_value_xpath="(//*[@content-desc='undefined-cardSubText'])[2]";
    public static final String L2CAC_ClimateAGS_text_xpath="//*[@text='Climate AGS']";
    public static final String L2CAC_ClimateAGS_toggle_xpath="(//android.view.ViewGroup[@content-desc=\"undefined-switchComponent\"])[1]";
    public static final String L2CAC_Airconditioner_text_xpath="//*[@text='Air Conditioner']";
    public static final String L2CAC_Airconditioner_value_xpath="//*[@text='Idle']";
    public static final String L2CAC_Scheduler_text_xpath="//*[@text='Scheduler']";
    public static final String L2CAC_Scheduler_toggle_xpath="(//android.view.ViewGroup[@content-desc=\"undefined-switchComponent\"])[2]";
    public static final String L2CAC_Sleep_text_xpath="//*[@text='Sleep']";
    public static final String L2CAC_Wake_text_xpath="//*[@text='Wake']";
    public static final String L2CAC_Away_text_xpath="//*[@text='Away']";
    public static final String L2CAC_Return_text_xpath="//*[@text='Return']";
    public static final String L2CAC_Scheduled_At_text_xpath="//*[@text='Scheduled At']";
    public static final String L2CAC_Scheduled_At_inside_text_xpath="//*[@content-desc='com.dometicapp:id/scheduler-schedulerText']";
    public static final String L2CAC_Scheduled_At_value_xpath="(//*[@content-desc='undefined-cardSubText'])[4]";
    public static final String L2CAC_Scheduled_At_inside_SCHEDULED_AT_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/scheduler-schedulerText\"]";
    public static final String L2CAC_Apply_Button_xpath="//*[@content-desc='com.dometicapp:id/climate-applyTemperature']";
    public static final String CAC_AM_fanSpeed_fanspeedText_xpath="//*[@content-desc='com.dometicapp:id/fanSpeed-fanspeedText']";
}

