package com.dometic.MTC.qa.Pages;

public class Constant_AGS {
    // -------------------------Accesibility_Id---------------//
    public static final String AGSPage_AGS_title_text_access_id="";
    public static final String AGSPage_Auto_Charger_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-0-cardTitle";
    public static final String AGSPage_Auto_Charger_switchText_access_id="com.dometicapp:id/ags-flatListItem-undefined-0-switchText";
    public static final String AGSPage_Auto_Charger_switchComponent_access_id="com.dometicapp:id/ags-flatListItem-undefined-0-switchComponent";
    public static final String AGSPage_Quiet_Time_Start_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-2-cardTitle";
    public static final String AGSPage_Quiet_Time_Start_cardSubText_access_id="com.dometicapp:id/ags-flatListItem-undefined-2-cardSubText";
    public static final String AGSPage_Quiet_Time_Start_cardIcon_access_id="com.dometicapp:id/ags-flatListItem-undefined-2-cardIcon";
    public static final String AGSPage_Quiet_Time_Ends_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-3-cardTitle";
    public static final String AGSPage_Quiet_Time_Ends_cardSubText_access_id="com.dometicapp:id/ags-flatListItem-undefined-3-cardSubText";
    public static final String AGSPage_Quiet_Time_Ends_cardIcon_access_id="com.dometicapp:id/ags-flatListItem-undefined-3-cardIcon";
    public static final String AGSPage_Start_Voltage_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-4-cardTitle";
    public static final String AGSPage_Start_Voltage_cardSubText_access_id="com.dometicapp:id/ags-flatListItem-undefined-4-cardSubText";
    public static final String AGSPage_Start_Voltage_cardIcon_access_id="com.dometicapp:id/ags-flatListItem-undefined-4-cardIcon";
    public static final String AGSPage_Time_Under_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-5-cardTitle";
    public static final String AGSPage_Time_Under_tooltip_undefined_access_id="tooltip-undefined";
    public static final String AGSPage_Time_Under_cardSubText_access_id="com.dometicapp:id/ags-flatListItem-undefined-5-cardSubText";
    public static final String AGSPage_Time_Under_cardIcon_access_id="com.dometicapp:id/ags-flatListItem-undefined-5-cardIcon";
    public static final String AGSPage_Generator_Exerciser_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-7-cardTitle";
    public static final String AGSPage_Generator_Exerciser_switchText_access_id="com.dometicapp:id/ags-flatListItem-undefined-7-switchText";
    public static final String AGSPage_Generator_Exerciser_switchComponent_access_id="com.dometicapp:id/ags-flatListItem-undefined-7-switchComponent";
    public static final String AGSPage_Selected_Days_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-8-cardTitle";
    public static final String AGSPage_Start_Time_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-9-cardTitle";
    public static final String AGSPage_Start_Time_cardSubText_access_id="com.dometicapp:id/ags-flatListItem-undefined-9-cardSubText";
    public static final String AGSPage_Start_Time_cardIcon_access_id="com.dometicapp:id/ags-flatListItem-undefined-9-cardIcon";
    public static final String AGSPage_Run_Time_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-10-cardTitle";
    public static final String AGSPage_Run_Time_cardSubText_access_id="com.dometicapp:id/ags-flatListItem-undefined-10-cardSubText";
    public static final String AGSPage_Run_Time_cardIcon_access_id="com.dometicapp:id/ags-flatListItem-undefined-10-cardIcon";
    public static final String AGSPage_AGS_Climate_text_access_id="com.dometicapp:id/ags-flatListItem-undefined-12-cardTitle";
    public static final String AGSPage_AGS_Climate_switchText_access_id="com.dometicapp:id/ags-flatListItem-undefined-12-switchText";
    public static final String AGSPage_AGS_Climate_switchComponent_access_id="com.dometicapp:id/ags-flatListItem-undefined-12-switchComponent";
    public static final String AGSPage_quietTimeStart_headingText_access_id="com.dometicapp:id/quietTimeStart-headingText";
    public static final String AGSPage_quietTimeStart_hoursCarousel_access_id="com.dometicapp:id/quietTimeStart-hoursCarousel";
    public static final String AGSPage_quietTimeStart_minsCarousel_access_id="com.dometicapp:id/quietTimeStart-minsCarousel";
    public static final String AGSPage_quietTimeStart_leftText_access_id="com.dometicapp:id/quietTimeStart-leftButton";
    public static final String AGSPage_quietTimeStart_rightButton_access_id="com.dometicapp:id/quietTimeStart-rightButton";
    public static final String AGSPage_quietTimeEnds_leftText_access_id="com.dometicapp:id/quietTimeEnd-leftText";
    public static final String AGSPage_quietTimeEnds_rightButton_access_id="com.dometicapp:id/quietTimeEnd-rightButton";
    public static final String AGSPage_quietTimeStart_applyButton_access_id="com.dometicapp:id/quietTimeStart-applyButton";
    public static final String AGSPage_quietTimeEnd_headingText_access_id="com.dometicapp:id/quietTimeEnd-headingText";
    public static final String AGSPage_quietTimeEnd_leftButton_access_id="com.dometicapp:id/quietTimeEnd-leftButton";
    public static final String AGSPage_quietTimeEnd_rightButton_access_id="com.dometicapp:id/quietTimeEnd-rightButton";
    public static final String AGSPage_quietTimeEnd_applyButton_access_id="com.dometicapp:id/quietTimeEnd-applyButton";
    public static final String AGSPage_startVoltage_headingText_access_id="com.dometicapp:id/startVoltage-headingText";
    public static final String AGSPage_startVoltage_applyButton_access_id="com.dometicapp:id/startVoltage-applyButton";
    public static final String AGSPage_timeUnder_headingText_access_id="com.dometicapp:id/timeUnder-headingText";
    public static final String AGSPage_timeUnder_applyButton_access_id="com.dometicapp:id/timeUnder-applyButton";
    public static final String AGSPage_startTime_headingText_access_id="com.dometicapp:id/startTime-headingText";
    public static final String AGSPage_startTime_leftButton_access_id="com.dometicapp:id/startTime-leftButton";
    public static final String AGSPage_startTime_rightButton_access_id="com.dometicapp:id/startTime-rightButton";
    public static final String AGSPage_startTime_applyButton_access_id="com.dometicapp:id/startTime-applyButton";
    public static final String AGSPage_runTime_headingText_access_id="com.dometicapp:id/runTime-headingText";
    public static final String AGSPage_runTime_textInput_access_id="com.dometicapp:id/runTime-textInput";
    public static final String AGSPage_runTime_minText_access_id="com.dometicapp:id/runTime-minText";
    public static final String AGSPage_runTime_infoText_access_id="com.dometicapp:id/runTime-infoText";
    public static final String AGSPage_runTime_applyButton_access_id="com.dometicapp:id/runTime-applyButton";


    public static final String AGSPage_Auto_Charger_text="Auto Charger";
    public static final String AGSPage_Quiet_Time_Start_text="Quiet Time Start";
    public static final String AGSPage_Quiet_Time_Ends_text="Quiet Time Ends";
    public static final String AGSPage_Start_Voltage_text="Start Voltage";
    public static final String AGSPage_Time_Under_text="Time Under";
    public static final String AGSPage_Generator_Exerciser_text="Generator Exerciser";
    public static final String AGSPage_Selected_Days_text="Selected Days";
    public static final String AGSPage_Start_Time_text="Start Time";
    public static final String AGSPage_Run_Time_text="Run Time";
    public static final String AGSPage_AGS_Climate_text="Climate AGS";
    public static final String AGSPage_Quiet_Time_Start_Title_text="QUIET TIME START";
    public static final String AGSPage_quietTimeEnd_Title_text="QUIET TIME ENDS";
    public static final String AGSPage_startVoltage_Title_text="START VOLTAGE";
    public static final String AGSPage_timeUnder_Title_text="TIME UNDER";
    public static final String AGSPage_startTime_Title_text="START TIME";
    public static final String AGSPage_runTime_Title_text="RUN TIME";
    public static final String AGSPage_ON_State_text="ON";
    public static final String AGSPage_OFF_State_text="OFF";

    //-------------------Needed Accessibility Id-----------------//
    public static final String AGSPage_Selected_Days_Sunday_text_access_id="";
    public static final String AGSPage_Selected_Days_Monday_text_access_id="";
    public static final String AGSPage_Selected_Days_Tuesday_text_access_id="";
    public static final String AGSPage_Selected_Days_Wednesday_text_access_id="";
    public static final String AGSPage_Selected_Days_Thursday_text_access_id="";
    public static final String AGSPage_Selected_Days_Friday_text_access_id="";
    public static final String AGSPage_Selected_Days_Saturday_text_access_id="";
    //   --------------------xPath--------------//
    public static final String AGSPage_AGS_title_text_xpath="//*[@text='AGS']";
    public static final String AGSPage_AGS_Auto_Charger_OFF_State_xpath="(//*[@text='OFF'])[1]";
    public static final String AGSPage_AGS_Generator_Exerciser_OFF_State_xpath="(//*[@text='OFF'])[2]";
    public static final String AGSPage_OK_Button_xpath="//*[@resource-id='android:id/button1']";
    public static final String AGSPage_Auto_Charger_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-0-cardTitle\"]";
    public static final String AGSPage_Auto_Charger_switchText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-0-switchText\"]";
    public static final String AGSPage_Auto_Charger_switchComponent_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-0-switchComponent\"]";
    public static final String AGSPage_Quiet_Time_Start_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-1-cardSubText\"]";
    public static final String AGSPage_Quiet_Time_Start_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-1-cardSubText\"]";
    public static final String AGSPage_Quiet_Time_Start_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-1-cardIcon\"]";
    public static final String AGSPage_Quiet_Time_Ends_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-2-cardTitle\"]";
    public static final String AGSPage_Quiet_Time_Ends_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-2-cardSubText\"]";
    public static final String AGSPage_Quiet_Time_Ends_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-2-cardIcon\"]";
    public static final String AGSPage_Start_Voltage_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-3-cardTitle\"]";
    public static final String AGSPage_Start_Voltage_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-3-cardSubText\"]";
    public static final String AGSPage_Start_Voltage_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-3-cardIcon\"]";
    public static final String AGSPage_Time_Under_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-4-cardTitle\"]";
    public static final String AGSPage_Time_Under_tooltip_undefined_xpath="//android.view.ViewGroup[@content-desc=\"tooltip-undefined\"]";
    public static final String AGSPage_Time_Under_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-4-cardSubText\"]";
    public static final String AGSPage_Time_Under_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-4-cardIcon\"]";
    public static final String AGSPage_Generator_Exerciser_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-6-cardTitle\"]";
    public static final String AGSPage_Generator_Exerciser_switchText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-6-switchText\"]";
    public static final String AGSPage_Generator_Exerciser_switchComponent_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-6-switchComponent\"]";
    public static final String AGSPage_Selected_Days_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-cardTitle\"]";
    public static final String AGSPage_Selected_Days_Sunday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[1]";
    public static final String AGSPage_Selected_Days_Monday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[2]";
    public static final String AGSPage_Selected_Days_Tuesday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[3]";
    public static final String AGSPage_Selected_Days_Wednesday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[4]";
    public static final String AGSPage_Selected_Days_Thursday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[5]";
    public static final String AGSPage_Selected_Days_Friday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[6]";
    public static final String AGSPage_Selected_Days_Saturday_text_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-7-dayButton-buttonContainer\"])[7]";
    public static final String AGSPage_Start_Time_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-8-cardTitle\"]";
    public static final String AGSPage_Start_Time_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-8-cardSubText\"]";
    public static final String AGSPage_Start_Time_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-8-cardIcon\"]";
    public static final String AGSPage_Run_Time_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-9-cardTitle\"]";
    public static final String AGSPage_Run_Time_cardSubText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-9-cardSubText\"]";
    public static final String AGSPage_Run_Time_cardIcon_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-9-cardIcon\"]";
    public static final String AGSPage_AGS_Climate_text_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-11-cardTitle\"]";
    public static final String AGSPage_AGS_Climate_switchText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-11-switchText\"]";
    public static final String AGSPage_AGS_Climate_switchComponent_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/ags-flatListItem-undefined-11-switchComponent\"]";
    public static final String AGSPage_quietTimeStart_headingText_xpath="//*[@content-desc='com.dometicapp:id/quietTimeStart-headingText']";
    public static final String AGSPage_quietTimeStart_leftText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/quietTimeStart-leftText\"]";
    public static final String AGSPage_quietTimeStart_rightButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/quietTimeStart-rightButton\"]";
    public static final String AGSPage_quietTimeStart_applyButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/quietTimeStart-applyButton\"]";
    public static final String AGSPage_quietTimeEnd_headingText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/quietTimeEnd-headingText\"]";
    public static final String AGSPage_quietTimeEnd_leftButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/quietTimeEnd-leftButton\"]";
    public static final String AGSPage_quietTimeEnd_rightButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/quietTimeEnd-rightButton\"]";
    public static final String AGSPage_quietTimeEnd_applyButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/quietTimeEnd-applyButton\"]";
    public static final String AGSPage_startVoltage_headingText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/startVoltage-headingText\"]";
    public static final String AGSPage_startVoltage_applyButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/startVoltage-applyButton\"]";
    public static final String AGSPage_timeUnder_headingText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/timeUnder-headingText\"]";
    public static final String AGSPage_timeUnder_applyButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/timeUnder-applyButton\"]";
    public static final String AGSPage_startTime_headingText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/startTime-headingText\"]";
    public static final String AGSPage_startTime_leftButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/startTime-leftButton\"]";
    public static final String AGSPage_startTime_rightButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/startTime-rightButton\"]";
    public static final String AGSPage_startTime_applyButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/startTime-applyButton\"]";
    public static final String AGSPage_runTime_headingText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/runTime-headingText\"]";
    public static final String AGSPage_runTime_textInput_xpath="//android.widget.EditText[@content-desc=\"com.dometicapp:id/runTime-textInput\"]";
    public static final String AGSPage_runTime_minText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/runTime-minText\"]";
    public static final String AGSPage_runTime_infoText_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/runTime-infoText\"]";
    public static final String AGSPage_runTime_applyButton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/runTime-applyButton\"]";
    public static final String AGSPage_QuietTimeStart_xpath="//*[@content-desc='com.dometicapp:id/ags-flatListItem-undefined-2-cardTitle']";
    public static final String AGSPage_QuietTimeStart_1sthoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeStart-hoursCarouselItem'])[1]";
    public static final String AGSPage_QuietTimeStart_2ndthoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeStart-hoursCarouselItem'])[2]";
    public static final String AGSPage_QuietTimeStart_3rdhoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeStart-hoursCarouselItem'])[3]";
    public static final String AGSPage_QuietTimeStart_1stminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeStart-minsCarouselItem'])[1]";
    public static final String AGSPage_QuietTimeStart_2ndminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeStart-minsCarouselItem'])[2]";
    public static final String AGSPage_QuietTimeStart_3rdminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeStart-minsCarouselItem'])[3]";
    public static final String AGSPage_QuietTimeEnds_1sthoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeEnd-hoursCarouselItem'])[1]";
    public static final String AGSPage_QuietTimeEnds_2ndthoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeEnd-hoursCarouselItem'])[2]";
    public static final String AGSPage_QuietTimeEnds_3rdhoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeEnd-hoursCarouselItem'])[3]";
    public static final String AGSPage_QuietTimeEnds_1stminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeEnd-minsCarouselItem'])[1]";
    public static final String AGSPage_QuietTimeEnds_2ndminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeEnd-minsCarouselItem'])[2]";
    public static final String AGSPage_QuietTimeEnds_3rdminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/quietTimeEnd-minsCarouselItem'])[3]";
    public static final String AGSPage_startVoltage_1stCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[1]";
    public static final String AGSPage_startVoltage_2ndCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[2]";
    public static final String AGSPage_startVoltage_3rdCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[3]";
    public static final String AGSPage_startVoltage_voltage_xpath="((//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[3]//following::android.widget.TextView)[1]";
    public static final String AGSPage_timeUnder_1stCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[1]";
    public static final String AGSPage_timeUnder_2ndCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[2]";
    public static final String AGSPage_timeUnder_3rdCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[3]";
    public static final String AGSPage_timeUnder_voltage_xpath="((//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[3]//following::android.widget.TextView)[1]";
    public static final String AGSPage_startTime_1sthoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startTime-hoursCarouselItem'])[1]";
    public static final String AGSPage_startTime_2ndthoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startTime-hoursCarouselItem'])[2]";
    public static final String AGSPage_startTime_3rdhoursCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startTime-hoursCarouselItem'])[3]";
    public static final String AGSPage_startTime_1stminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startTime-minsCarouselItem'])[1]";
    public static final String AGSPage_startTime_2ndminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startTime-minsCarouselItem'])[2]";
    public static final String AGSPage_startTime_3rdminsCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startTime-minsCarouselItem'])[3]";
    public static final String AGSPage_runTime_1stCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[1]";
    public static final String AGSPage_runTime_2ndCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[2]";
    public static final String AGSPage_runTime_3rdCarousel_xpath="(//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[3]";
    public static final String AGSPage_runTime_voltage_xpath="((//*[@content-desc='com.dometicapp:id/startVoltage-voltageCarouselItem'])[3]//following::android.widget.TextView)[1]";
}
