package com.dometic.MTC.qa.Pages;

public class Constant_settings {
    // --------------Accessibility_id-------------------//
    public static final String Settings_Back_Button_access_id = "com.dometicapp:id/tiles-backImage";
    public static final String Settings_languageContainer_access_id = "com.dometicapp:id/setting-languageContainer";
    public static final String Settings_versionContainer_access_id = "com.dometicapp:id/setting-versionContainer";
    public static final String Settings_language_text_access_id = "com.dometicapp:id/setting-languageText";
    public static final String Settings_language_text_expected = "Sprachen";
    public static final String Settings_language_Spanish_text_expected = "Idioma";
    public static final String Settings_temperature_Spanish_text_expected = "Unidad de temperatura";
    public static final String Settings_version_Spanish_text_expected = "Versión 1.3";
    public static final String Settings_logout_Spanish_text_expected = "Cerrar sesión";
    public static final String Settings_language_French_text_expected = "Langue";
    public static final String Settings_temperature_French_text_expected = "Unité de température";
    public static final String Settings_version_French_text_expected = "Version 1.3";
    public static final String Settings_logout_French_text_expected = "Déconnexion";
    public static final String Settings_language_selectedName_access_id = "com.dometicapp:id/setting-selectedLanguage";
    public static final String Settings_languages_navigation_button_access_id = "com.dometicapp:id/setting-languageiconCollapse";
    public static final String Settings_Language_English_tick_access_id = "com.dometicapp:id/language-iconTickEnglish";
    public static final String Settings_language_German_access_id = "com.dometicapp:id/language-germanText";
    public static final String Settings_Language_German_tick_access_id = "com.dometicapp:id/language-iconTickGerman";
    public static final String Settings_Temperature_text_access_id = "com.dometicapp:id/setting-temperatureContainer";
    public static final String Settings_Temperature_text_expected = "Temperatureinheit";
    public static final String Settings_version_text_access_id = "com.dometicapp:id/setting-versionText";
    public static final String Settings_logout_text_access_id = "com.dometicapp:id/setting-logOutText";
    public static final String Settings_logout_expected = "Abmelden";
    public static final String Settings_fahrenheit_access_id = "com.dometicapp:id/setting-fahrenheitText";
    public static final String Settings_Temperature_unit_access_id = "com.dometicapp:id/setting-temperatureButtons";
    public static final String Settings_Zone_Management_expected = "Zone Management";
    public static final String Settings_Zone_Management_ALL_ZONES_text = "ALL ZONES";
    public static final String Settings_Zone_Management_edit_text = "Edit";
    public static final String Settings_Zone_Management_LimitedZones_text = "Limited to 4 Zones only";
    public static final String Settings_Zone_Management_addZoneIcon_access_id = "com.dometicapp:id/zoneManagement-addZoneIcon";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_access_id = "com.dometicapp:id/ZoneNumber-selectButton";
    public static final String Settings_Zone_Management_addZoneIcon_Select_text_access_id = "com.dometicapp:id/ZoneNumber-selectZoneText";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_text = "Zone Name can not be empty";
    public static final String Settings_Zone_Management_10_character_text = "10/10 character";
    public static final String Settings_Zone_Management_value = "Living Room";
    public static final String Settings_Zone_Management_Living_Room = "LivingRoom";
    public static final String Settings_Zone_Management_NewZone_Room = "StudyRoom";
    public static final String Settings_Zone_Management_deleteZoneAlert_cancelButton_access_id = "com.dometicapp:id/zoneManagement-deleteZoneAlert-saveButton";
    public static final String Settings_Zone_Management_deleteZoneAlert_YES_DELETE_ITButton_access_id = "com.dometicapp:id/zoneManagement-deleteZoneAlert-cancelButton";
    public static final String Settings_Zone_Management_new_Zone_access_id = "com.dometicapp:id/ZoneNumber-dialog-undefined";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_access_id = "com.dometicapp:id/ZoneNumber-dialog-saveButton";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_access_id = "com.dometicapp:id/ZoneNumber-dialog-cancelButton";
    public static final String Settings_headerBackButtonIcon_access_id = "com.dometicapp:id/sidemenu-headerBackButtonIcon";
    public static final String Settings_userProfilePhoto_access_id = "com.dometicapp:id/sidemenu-userProfilePhoto";
    public static final String Settings_userName_access_id = "com.dometicapp:id/sidemenu-userName";
    public static final String Settings_userEmail_access_id = "com.dometicapp:id/sidemenu-userEmail";
    public static final String Settings_viewEditButtonText_access_id = "com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String Settings_home_text_access_id = "com.dometicapp:id/sidemenu-home-text";
    public static final String Settings_notificationSettings_text_access_id = "com.dometicapp:id/sidemenu-notificationSettings-text";
    public static final String Settings_deviceMangagement_text_access_id = "com.dometicapp:id/sidemenu-deviceMangagement-text";
    public static final String Settings_appSettings_text_access_id = "com.dometicapp:id/sidemenu-appSettings-text";
    public static final String Settings_Logout_text_access_id = "com.dometicapp:id/sidemenu-logout-text";
    public static final String Settings_Version_16_text_access_id = "com.dometicapp:id/sidemenu-versionText";
    public static final String Device_management_header_text_tile = "com.dometicapp:id/header-TitleText";
    public static final String Device_management_slide_menu_right_icon_access_id = "com.dometicapp:id/DeviceManagement-deviceName";
    public static final String Device_management_Vessel_tile_lable_access_id = "com.dometicapp:id/deviceManagement-vesseltitleLabel";
    public static final String Device_management_Vessel_Name_lable_access_id = "com.dometicapp:id/deviceManagement-vesselNameLabel";
    public static final String Device_management_Hull_Id_Number_aceess_id = "com.dometicapp:id/deviceManagement-hullIdLabel";
    public static final String Device_management_Edit_vessel_title_access_id = "com.dometicapp:id/deviceManagement-editVessel-cardTitle";
    public static final String Device_management_Edit_vessel_card_icon_access_id = "com.dometicapp:id/deviceManagement-editVessel-cardIcon";
    public static final String Device_management_advanced_Title_Text_access_id = "com.dometicapp:id/deviceManagement-advancedTitleText";
    public static final String Device_management_check_updates_card_title_access_id = "com.dometicapp:id/deviceManagement-checkForUpdates-cardTitle";
    public static final String Device_management_check_updates_card_icon_access_id = "com.dometicapp:id/deviceManagement-checkForUpdates-cardIcon";
    public static final String Device_management_unregister_Delete_cardTitle_access_id = "com.dometicapp:id/deviceManagement-unregisterDelete-cardTitle";
    public static final String Device_management_unregister_Delete_right_icon_access_id = "com.dometicapp:id/deviceManagement-unregisterDelete-cardIcon";

    public static final String Device_management_edit_page_back_button_access_id = "com.dometicapp:id/tiles-backImage";
    public static final String Device_management_edit_page_header_text_tile_access_id = "com.dometicapp:id/header-TitleText";
    public static final String Device_management_edit_vessel_name_lable_access_id = "com.dometicapp:id/editVessel-vesselNameLabel";
    public static final String Device_management_edit_mac_address_access_id = "com.dometicapp:id/editVessel-hullIdLabel";
    public static final String Device_management_edit__save_button_access_id = "com.dometicapp:id/editVessel-saveButtonText";


    //-------------------Needed Accessibility Id-----------------//
    public static final String Settings_Language_Page_title_access_id = "";
    public static final String Settings_language_Back_button_access_id = "";
    public static final String Settings_Language_English_access_id = "";
    public static final String Settings_back_button_access_id = "";
    public static final String Settings_page_title_access_id = "";
    public static final String Settings_temperature_unit_C_access_id = "";
    public static final String Settings_temperature_unit_F_access_id = "";

    // ----------------------xpath-----------------------------//
    public static final String Settings_text_xpath = "(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage'])[1]";
    public static final String Settings_Language_select_xpath = "(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[1]";
    public static final String Settings_Temperature_unit_xpath = "(//*[@class='android.view.ViewGroup'])[17]";
    public static final String Settings_Upgrade_Firmware_xpath = "(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[2]";
    public static final String Settings_Version_xpath = "//*[@content-desc='com.dometicapp:id/setting-versionContainer']";
    public static final String Settings_Logout_xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/setting-logOutContainer']/android.view.ViewGroup";
    public static final String Settings_Language_Page_title_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_language_Back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup/android.widget.ImageView";
    public static final String Settings_Language_English_xpath = "//android.widget.TextView[@content-desc=\"com.dometicapp:id/language-englishContainer\"]";
    public static final String Settings_back_button_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]";
    public static final String Settings_page_title_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_temperature_unit_C_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[1]/android.view.ViewGroup/android.widget.TextView";
    public static final String Settings_temperature_unit_F_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.TextView\n";
    public static final String Settings_language_Spanish_xpath = "//*[@text='Spanish (US)']";
    public static final String Settings_language_French_xpath = "//*[@text='French']";
    public static final String Settings_language_xpath = "(//*[@content-desc='com.dometicapp:id/setting-languageText'])[1]";
    public static final String Settings_Zone_Management_xpath = "(//*[@content-desc='com.dometicapp:id/setting-scrollView']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_edit_xpath = "(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_LimitedZones_xpath = "(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_xpath = "(//*[@content-desc='com.dometicapp:id/zoneManagement-flatList']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_value_xpath = "//android.widget.EditText[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_xpath = "(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_SAVE_Button_xpath = "(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_CANCEL_Button_xpath = "(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_flatListItem_xpath = "(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-flatListItem-')]//following::android.view.ViewGroup)[2]";
    public static final String Settings_Zone_Management_deleteZoneAlert_description_xpath = "//*[@content-desc='com.dometicapp:id/zoneManagement-deleteZoneAlert-description']";
    public static final String Settings_Zone_Management_deleteZone_xpath = "//*[@text='YES, DELETE IT']";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_xpath = "//*[@content-desc='com.dometicapp:id/ZoneNumber-selectButton']";
    public static final String Settings_Zone_Management_new_Zone_xpath = "//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-undefined']";
    public static final String Settings_Zone_Management_Zone_name_already_present_xpath = "//*[@text='Zone name already present']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_xpath = "//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-saveButton']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_xpath = "//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-cancelButton']";
    public static final String Device_management_edit_page_Cancel_Button_Xpath = "//*[@content-desc='com.dometicapp:id/header-rightButton']";
    // ----------------------Data-----------------------------//
    public static final String Settings_viewEditButtonText = "View/Edit Account";
    public static final String Settings_home_text = "Home";
    public static final String Settings_notificationSettings_text = "Notification Settings";
    public static final String Settings_deviceMangagement_text = "Device Management";
    public static final String Settings_appSettings_text = "App Settings";
    public static final String Settings_Logout_text = "Logout";
    public static final String Settings_Version_16_text = "Version 1.6";
    public static final String Device_management_header_text = "DEVICE MANAGEMENT";
    public static final String Device_management_Vessel_tile_label = "VESSEL INFORMATION";
    public static final String Device_management_Vessel_Name_label = "Name";
    public static final String Device_management_Hull_Id_Number = "MAC Address";
    public static final String Device_management_Edit_vessel_title = "Edit vessel";
    public static final String Device_management_advanced_Title_Text = "ADVANCED";
    public static final String Device_management_check_updates_card_title = "Check updates";
    public static final String Device_management_unregister_Delete_cardTitle = "Unregister/Delete/Offboard";
    public static final String Device_management_edit_page_header_text = "EDIT";
    public static final String Device_management_edit_vessel_name_label = "Name";
    public static final String Device_management_edit_mac_address = "Mac Address";
    public static final String Device_management_edit_save_button = "Save";

}
