package com.dometic.MTC.qa.Pages;

public class Constant_ManagementNotifications {
    public static final String ManageNotifications_title_access_id = "com.dometicapp:id/header-TitleText";
    public static final String ManageNotifications_back_button_access_id = "com.dometicapp:id/tiles-backImage";
    public static final String ManageNotifications_logo_access_id = "com.dometicapp:id/notification-header-logo";
    public static final String ManageNotifications_Global_settings_access_id = "com.dometicapp:id/notification-header-text";
    public static final String ManageNotifications_Push_Notifications_access_id = "";
    public static final String ManageNotifications_PushNotifications_text_access_id = "com.dometicapp:id/notification-pushNotificationContainer-cardTitle";
    public static final String ManageNotifications_PushNotifications_toggle_access_id = "com.dometicapp:id/notification-pushNotificationContainer-switchComponent";
    public static final String ManageNotifications_push_show_more_text_access_id =  "com.dometicapp:id/notification-pushNotificationShowMore-cardTitle";
    public static final String ManageNotifications_push_show_more_text_navigation_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-expandIcon";
    public static final String ManageNotifications_push_show_less_text_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-cardTitle";
    public static final String ManageNotifications_push_show_less_navigation_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-expandIcon";
    public static final String ManageNotifications_push_alerts_text_access_id = "com.dometicapp:id/notification-pushNotificationAlertText";
    public static final String ManageNotifications_push_alerts_toggle_access_id =  "com.dometicapp:id/notification-pushNotificationAlertSwitch";
    public static final String ManageNotifications_push_warnings_text_access_id = "com.dometicapp:id/notification-pushNotificationWarningText";
    public static final String ManageNotifications_push_warnings_toggle_access_id =  "com.dometicapp:id/notification-pushNotificationWarningSwitch";
    public static final String ManageNotifications_Email_text_access_id = "com.dometicapp:id/notification-emailContainer-cardTitle";
    public static final String ManageNotifications_Email_toggle_access_id = "com.dometicapp:id/notification-emailContainer-switchComponent";
    public static final String ManageNotifications_showmore_text_access_id = "com.dometicapp:id/notification-emailShowMore-cardTitle";
    public static final String ManageNotifications_showmore_dropdown_access_id = "com.dometicapp:id/notification-emailShowMore-expandIcon";
    public static final String ManageNotifications_EmailList_text_access_id = "com.dometicapp:id/notification-emailList-title";
    public static final String ManageNotifications_EmailList_label_text_1_access_id = "com.dometicapp:id/notification-emailListElement0-Text";
    public static final String ManageNotifications_EmailList_Email_1_access_id = "com.dometicapp:id/notification-emailListElement0-Subtext";
    public static final String ManageNotifications_EmailList_1_toggle_access_id = "com.dometicapp:id/notification-emailListElement0-Switch";
    public static final String ManageNotifications_EmailList_label_text_2_access_id = "com.dometicapp:id/notification-emailListElement1-Text";
    public static final String ManageNotifications_EmailList_Email_2_access_id = "com.dometicapp:id/notification-emailListElement1-Subtext";
    public static final String ManageNotifications_EmailList_2_toggle_access_id = "com.dometicapp:id/notification-emailListElement1-Switch";
    public static final String ManageNotifications_EmailList_3_toggle_access_id = "com.dometicapp:id/notification-emailListElement2-Switch";
    public static final String ManageNotifications_EmailList_Email_3_access_id = "com.dometicapp:id/notification-emailListElement2-Subtext";
    public static final String ManageNotifications_EmailList_label_text_3_access_id = "com.dometicapp:id/notification-emailListElement2-Text";
    public static final String ManageNotifications_EmailList_4_toggle_access_id = "com.dometicapp:id/notification-emailListElement3-Switch";
    public static final String ManageNotifications_EmailList_Email_4_access_id = "com.dometicapp:id/notification-emailListElement3-Subtext";
    public static final String ManageNotifications_EmailList_label_text_4_access_id =  "com.dometicapp:id/notification-emailListElement3-Text";
    public static final String ManageNotifications_EmailList_5_toggle_access_id = "com.dometicapp:id/notification-emailListElement4-Switch";
    public static final String ManageNotifications_EmailList_Email_5_access_id = "com.dometicapp:id/notification-emailListElement4-Subtext";
    public static final String ManageNotifications_EmailList_label_text_5_access_id = "com.dometicapp:id/notification-emailListElement4-Text";
    public static final String ManageNotifications_EmailList_email_text_access_id = "";
    public static final String ManageNotifications_editlist_text_access_id = "com.dometicapp:id/notification-emailList-subTitle";
    public static final String ManageNotifications_editlist_navigation_access_id = "com.dometicapp:id/notification-emailList-expandIcon";
    public static final String ManageNotifications_email_alerts_toggle_button_access_id =  "com.dometicapp:id/notification-emailNotificationAlertSwitch";
    public static final String ManageNotifications_email_warnings_toggle_button_access_id = "com.dometicapp:id/notification-emailNotificationWarningContainerSwitch";
    public static final String ManageNotifications_email_alerts_text_access_id = "com.dometicapp:id/notification-emailNotificationAlertText";
    public static final String ManageNotifications_email_warnings_text_access_id = "com.dometicapp:id/notification-emailNotificationWarningContainerText";
    public static final String ManageNotifications_Email_showless_text_access_id = "com.dometicapp:id/notification-emailShowMore-cardTitle";
    public static final String ManageNotifications_Email_showless_navigation_access_id = "com.dometicapp:id/notification-emailShowMore-expandIcon";

    public static final String ManageNotifications_sms_text_access_id = "com.dometicapp:id/notification-smsContainer-cardTitle";
    public static final String ManageNotifications_sms_toggle_access_id = "com.dometicapp:id/notification-smsContainer-switchComponent";
    public static final String ManageNotifications_sms_showmore_text_access_id = "com.dometicapp:id/notification-smsShowMore-cardTitle";
    public static final String ManageNotifications_sms_showmore_dropdown_access_id = "com.dometicapp:id/notification-smsShowMore-expandIcon";
    public static final String ManageNotifications_sms_showless_text_access_id =  "com.dometicapp:id/notification-smsShowMore-cardTitle";
    public static final String ManageNotifications_sms_showless_dropdown_access_id = "com.dometicapp:id/notification-smsShowMore-expandIcon";
    public static final String ManageNotifications_sms_smslist_text_access_id = "com.dometicapp:id/notification-smsList-title";
    public static final String ManageNotifications_sms_smslist_label_text_1_access_id =  "com.dometicapp:id/notification-smsListElement0-Text";
    public static final String ManageNotifications_sms_smslist_number_1_access_id = "com.dometicapp:id/notification-smsListElement0-Subtext";
    public static final String ManageNotifications_sms_smslist_1_toggle_access_id =  "com.dometicapp:id/notification-smsListElement0-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_2_access_id = "com.dometicapp:id/notification-smsListElement1-Text";
    public static final String ManageNotifications_sms_smslist_number_2_access_id = "com.dometicapp:id/notification-smsListElement1-Subtext";
    public static final String ManageNotifications_sms_smslist_2_toggle_access_id = "com.dometicapp:id/notification-smsListElement1-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_3_access_id = "com.dometicapp:id/notification-smsListElement2-Text";
    public static final String ManageNotifications_sms_smslist_number_3_access_id = "com.dometicapp:id/notification-smsListElement2-Subtext";
    public static final String ManageNotifications_sms_smslist_3_toggle_access_id = "com.dometicapp:id/notification-smsListElement2-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_4_access_id = "com.dometicapp:id/notification-smsListElement3-Text";
    public static final String ManageNotifications_sms_smslist_number_4_access_id = "com.dometicapp:id/notification-smsListElement3-Subtext";
    public static final String ManageNotifications_sms_smslist_4_toggle_access_id = "com.dometicapp:id/notification-smsListElement3-Switch";
    public static final String ManageNotifications_sms_smslist_label_text_5_access_id = "com.dometicapp:id/notification-smsListElement4-Text";
    public static final String ManageNotifications_sms_smslist_number_5_access_id = "com.dometicapp:id/notification-smsListElement4-Subtext";
    public static final String ManageNotifications_sms_smslist_5_toggle_access_id = "com.dometicapp:id/notification-smsListElement4-Switch";
    public static final String ManageNotifications_sms_smslist_editlist_text_access_id = "com.dometicapp:id/notification-smsList-subTitle";
    public static final String ManageNotifications_sms_smslist_editlist_naviagtion_access_id = "com.dometicapp:id/notification-smsList-expandIcon";
    public static final String ManageNotifications_sms_alerts_text_access_id = "com.dometicapp:id/notification-smsNotificationAlertText";
    public static final String ManageNotifications_sms_warnings_text_access_id = "com.dometicapp:id/notification-smsNotificationWarningText";
    public static final String ManageNotifications_sms_warnings_toggle_button_access_id = "com.dometicapp:id/notification-smsNotificationWarningSwitch";
    public static final String ManageNotifications_sms_alerts_toggle_button_access_id = "com.dometicapp:id/notification-smsNotificationAlertSwitch";
    public static final String ManageNotifications_sms_editlist_remove_icon_access_id = "com.dometicapp:id/editListElement1-removeIcon";

    public static final String ManageNotifications_Mobile_number_1_value_access_id = "com.dometicapp:id/editListElement1-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_1_access_id = "com.dometicapp:id/editListElement1-titleInput";
    public static final String ManageNotifications_Mobile_number_2_value_access_id = "com.dometicapp:id/editListElement2-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_2_access_id = "com.dometicapp:id/editListElement2-titleInput";
    public static final String ManageNotifications_Mobile_number_3_value_access_id = "com.dometicapp:id/editListElement3-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_3_access_id = "com.dometicapp:id/editListElement3-titleInput";
    public static final String ManageNotifications_Mobile_number_4_value_access_id = "com.dometicapp:id/editListElement4-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_4_access_id = "com.dometicapp:id/editListElement4-titleInput";
    public static final String ManageNotifications_Mobile_number_5_value_access_id = "com.dometicapp:id/editListElement5-subtitleInput";
    public static final String ManageNotifications_Mobile_number_label_5_access_id = "com.dometicapp:id/editListElement5-titleInput";
    public static final String ManageNotifications_edit_smslist_add_button_access_id = "com.dometicapp:id/editList-addElement-icon";
    public static final String ManageNotifications_valid_mobile_number = "9842252955";
    public static final String ManageNotifications_sms_valid_label_name = "srinidi";
    public static final String ManageNotifications_invalid_mobile_number = "83560437586574865874567403984";
    public static final String ManageNotifications_sms_invalid_label_name = "#$%%^&^*^&";
    public static final String ManageNotifications_sms_unique_label_name = "contact";

    public static final String ManageNotifications_Advance_text_access_id = "com.dometicapp:id/notification-advanceText";
    public static final String ManageNotifications_advance_device_1_name_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-MTC_e247d0-name";
    public static final String ManageNotifications_advance_device_2_name_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-DSIM_e24878-name";
    public static final String ManageNotifications_advance_device_3_name_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-Vessel-name";
    public static final String ManageNotifications_advance_device_1_logo_access_id = "AdvancedNotificationSetings-MTC_e247d0-icon";
    public static final String ManageNotifications_advance_device_2_logo_access_id =  "AdvancedNotificationSetings-DSIM_e24878-icon";
    public static final String ManageNotifications_advance_device_3_logo_access_id = "AdvancedNotificationSetings-Vessel-icon";
    public static final String ManageNotifications_advance_device_1_navigation_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-MTC_e247d0-iconCollapse";
    public static final String ManageNotifications_advance_device_2_navigation_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-DSIM_e24878-iconCollapse";
    public static final String ManageNotifications_advance_device_3_navigation_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-Vessel-iconCollapse";
    public static final String ManageNotifications_Advanced_push_notifications_text_access_id = "devicePushNotificationsElement-Text";
    public static final String ManageNotifications_Advanced_push_notifications_toggle_access_id = "devicePushNotificationsElement-Switch";
    public static final String ManageNotifications_Advanced_Screen_logo_access_id = "DeviceNotifications.Header-logo";
    public static final String ManageNotifications_Advanced_Screen_device_name_access_id = "DeviceNotifications.Header-text";
    public static final String ManageNotifications_Advanced_screen_title_access_id = "com.dometicapp:id/header-TitleText";
    public static final String ManageNotifications_Advanced_screen_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";

    public static final String ManageNotifications_Edit_Email_add_new_button_access_id = "com.dometicapp:id/editList-addElement-icon";
    public static final String ManageNotifications_Edit_Email_element_1_access_id = "com.dometicapp:id/editListElement1-subtitleInput";
    public static final String ManageNotifcations_Edit_Email_label_1_access_id = "com.dometicapp:id/editListElement1-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_2_access_id = "com.dometicapp:id/editListElement2-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_2_access_id = "com.dometicapp:id/editListElement2-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_3_access_id = "com.dometicapp:id/editListElement3-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_3_access_id = "com.dometicapp:id/editListElement3-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_4_access_id = "com.dometicapp:id/editListElement4-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_4_access_id = "com.dometicapp:id/editListElement4-titleInput";
    public static final String ManageNotifactions_Edit_Email_element_5_access_id = "com.dometicapp:id/editListElement5-subtitleInput";
    public static final String ManageNotifications_Edit_Email_label_5_access_id = "com.dometicapp:id/editListElement5-titleInput";
    public static final String ManageNotifications_Edit_Email_valid_input = "srinidi98@yopmail.com";
    public static final String ManageNotifications_Edit_Email_label_valid_input = "Srinidi";
    public static final String ManageNotifications_Edit_Email_invalid_input = "$%&*()@";
    public static final String ManageNotifications_Edit_Email_label_invalid_input = "^^^^^";

    public static final String ManageNotifications_Edit_Email_remove_access_id = "com.dometicapp:id/editListElement4-removeIcon";
    public static final String ManageNotifications_Edit_Email_save_button_xpath = "(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-save-button\"])[2]";
    public static final String ManageNotifications_Edit_Email_close_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-header-backButton\"]/android.widget.TextView";
    public static final String ManageNotifications_Edit_Email_delete_xpath = "//*[contains(@content-desc,'-removeIcon')]";
    public static final String ManageNotifications_Edit_sms_save_button_xpath = "(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-save-button\"])[2]";
    public static final String ManageNotifications_Edit_sms_close_button_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/editList-header-backButton\"]/android.widget.TextView";
    public static final String ManageNotifications_sms_showmore_text_xpath="(//*[@content-desc='undefined-cardTitle'])[3]";
    public static final String ManageNotifications_Email_showmore_text_xpath="(//*[@content-desc='undefined-cardTitle'])[2]";
    public static final String ManageNotifications_Email_toggle_xpath="(//*[@content-desc='undefined-switchComponent'])[1]";
    public static final String ManageNotifications_Push_toggle_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/notification-pushNotificationContainer-switchComponent\"]/android.view.ViewGroup";
    public static final String ManageNotifications_Push_alerts_toggle_xpath =  "(//*[@content-desc='undefinedSwitch'])[1]";
    public static final String ManageNotifications_sms_toggle_xpath="(//*[@content-desc='undefined-switchComponent'])[2]";
    public static final String managePushNotification_Alert_Text_xpath="(//*[@content-desc='undefinedText'])[1]";
    public static final String managePushNotification_Alert_Toggle_xpath="(//*[@content-desc='undefinedSwitch'])[1]";
    public static final String managePushNotification_Warning_Text_xpath="(//*[@content-desc='undefinedText'])[2]";
    public static final String managePushNotification_Warning_Toggle_xpath="(//*[@content-desc='undefinedSwitch'])[2]";

}
