package com.dometic.L2.qa.Pages;

public class Constant_settings {
    // --------------Accessibility_id-------------------//
    public static final String Settings_Back_Button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_languageContainer_access_id="com.dometicapp:id/setting-languageContainer";
    public static final String Settings_versionContainer_access_id="com.dometicapp:id/setting-versionContainer";
    public static final String Settings_language_text_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_language_text_expected="Sprachen";
    public static final String Settings_language_Spanish_text_expected="Idioma";
    public static final String Settings_temperature_Spanish_text_expected="Unidad de temperatura";
    public static final String Settings_version_Spanish_text_expected="Versión 1.3";
    public static final String Settings_logout_Spanish_text_expected="Cerrar sesión";
    public static final String Settings_language_French_text_expected="Langue";
    public static final String Settings_temperature_French_text_expected="Unité de température";
    public static final String Settings_version_French_text_expected="Version 1.3";
    public static final String Settings_logout_French_text_expected="Déconnexion";
    public static final String Settings_language_selectedName_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String Settings_languages_navigation_button_access_id="com.dometicapp:id/setting-languageiconCollapse";
    public static final String Settings_Language_English_tick_access_id="com.dometicapp:id/language-iconTickEnglish";
    public static final String Settings_language_German_access_id="com.dometicapp:id/language-germanText";
    public static final String Settings_Language_German_tick_access_id="com.dometicapp:id/language-iconTickGerman";
    public static final String Settings_Temperature_text_access_id="com.dometicapp:id/setting-temperatureContainer";
    public static final String Settings_Temperature_text_expected="Temperatureinheit";
    public static final String Settings_version_text_access_id="com.dometicapp:id/setting-versionText";
    public static final String Settings_logout_text_access_id="com.dometicapp:id/setting-logOutText";
    public static final String Settings_logout_expected="Abmelden";
    public static final String Settings_fahrenheit_access_id="com.dometicapp:id/setting-fahrenheitText";
    public static final String Settings_Temperature_unit_access_id="com.dometicapp:id/setting-temperatureButtons";
    public static final String Settings_Zone_Management_expected="Zone Management";
    public static final String Settings_Zone_Management_ALL_ZONES_text="ALL ZONES";
    public static final String Settings_Zone_Management_edit_text="Edit";
    public static final String Settings_Zone_Management_LimitedZones_text="Limited to 4 Zones only";
    public static final String Settings_Zone_Management_addZoneIcon_access_id="com.dometicapp:id/zoneManagement-addZoneIcon";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_access_id="com.dometicapp:id/ZoneNumber-selectButton";
    public static final String Settings_Zone_Management_addZoneIcon_Select_text_access_id="com.dometicapp:id/ZoneNumber-selectZoneText";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_text="Zone Name can not be empty";
    public static final String Settings_Zone_Management_10_character_text="10/10 character";
    public static final String Settings_Zone_Management_value="Living Room";
    public static final String Settings_Zone_Management_Living_Room="LivingRoom";
    public static final String Settings_Zone_Management_NewZone_Room="StudyRoom";
    public static final String Settings_Zone_Management_deleteZoneAlert_cancelButton_access_id="com.dometicapp:id/zoneManagement-deleteZoneAlert-saveButton";
    public static final String Settings_Zone_Management_deleteZoneAlert_YES_DELETE_ITButton_access_id="com.dometicapp:id/zoneManagement-deleteZoneAlert-cancelButton";
    public static final String Settings_Zone_Management_new_Zone_access_id="com.dometicapp:id/ZoneNumber-dialog-undefined";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_access_id="com.dometicapp:id/ZoneNumber-dialog-saveButton";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_access_id="com.dometicapp:id/ZoneNumber-dialog-cancelButton";
    public static final String Device_Management_access_id = "com.dometicapp:id/sidemenu-deviceMangagement-text";

    public static final String Device_Management_back_button_access="com.dometicapp:id/DeviceManagementDetailsScreen-header-header-leftComponent";
    public static final String Device_Management_Device_name_access_id ="com.dometicapp:id/DeviceManagementScreen-DeviceManagementButton-Container";
    public static final String Device_Management_header_Xpath_OR_Operator ="//android.widget.TextView[contains(@text,'DEVICE MANAGEMENT') or @content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-header-header-centerTitleText']";
    public static final String Device_Management_back_button_Xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-header-header-leftButton']/android.view.ViewGroup";
    public static final String Device_Management_image_access_id = "com.dometicapp:id/deviceManagement-deviceImage";
    public static final String Device_Management_page_Device_name_access_id = "com.dometicapp:id/deviceManagement-deviceName";
    public static final String Device_Management_Vessel_information_text_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'VESSEL INFORMATION') or @content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-ProductInformationLabel']";
    public static final String Device_Management_Name_text_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'Name') or @content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-NameLabel-Label']";
    public static final String Device_Management_Name_access_id = "com.dometicapp:id/DeviceManagementDetailsScreen-NameLabel-Title";
    public static final String Device_Management_MAC_address_text_access_id = "com.dometicapp:id/deviceManagement-hullIdLabel";
    public static final String Device_Management_MAC_address_access_id = "com.dometicapp:id/deviceManagement-hullIdValue";
    public static final String Device_Management_Edit_vessel_text_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'Edit') or @content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-EditProductInfo-Title']";
    public static final String Device_Management_Edit_vessel_navigation_Xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-EditProductInfo-Container']/android.view.ViewGroup";
    public static final String Device_Management_Edit_vessel_header_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'EDIT VESSEL') or @content-desc='com.dometicapp:id/header-TitleText']";
    public static final String Device_Management_Edit_vessel_image_access_id = "com.dometicapp:id/deviceManagement-deviceImage";

    public static final String Device_Management_Edit_vessel_name_text_OR_Operator = "//android.widget.TextView[contains(@text,'Name') or @content-desc='com.dometicapp:id/editVessel-vesselNameLabel']";
    public static final String Device_Management_Edit_vessel_name_access_id = "com.dometicapp:id/editVessel-vesselNameValue";
    public static final String Device_Management_Edit_vessel_MAC_address_text_access_id = "com.dometicapp:id/editVessel-hullIdLabel";
    public static final String Edit_vessel_Vessel_name_should_not_be_empty_error_message_Xpath="//android.widget.ScrollView[@content-desc='com.dometicapp:id/editVessel-scrollview']/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.TextView[2]";
    public static final String Edit_vessel_Vessel_name_should_not_be_empty_error_message_expected="Vessel name should not be empty";
    public static final String Edit_vessel_Vesse_name_cannot_include_special_characters_error_message_Xpath="//android.widget.ScrollView[@content-desc='com.dometicapp:id/editVessel-scrollview']/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.TextView[2]";
    public static final String Edit_vessel_Vesse_name_cannot_include_special_characters_error_message_expected="Vessel name cannot include special characters";
    public static final String Device_Management_Edit_vessel_MAC_address_text_Xpath = "//android.widget.TextView[contains(@text,'Mac Address') or @content-desc='com.dometicapp:id/editVessel-hullIdLabel']";
    public static final String Device_Management_Edit_vessel_MAC_address_access_id = "com.dometicapp:id/editVessel-hullIdValue";
    public static final String Device_Management_Edit_vessel_Save_text_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'Save') or @content-desc='com.dometicapp:id/editVessel-saveButtonText']";
    public static final String Device_Management_Edit_vessel_Save_button_access_id = "com.dometicapp:id/editVessel-saveButton";
    public static final String Device_Management_1st_device_name_access_id ="com.dometicapp:id/DeviceManagementScreen-DeviceManagementButton-Title";
    public static final String Device_Management_device_name_Home_page_access_id ="com.dometicapp:id/Dashboard-cardText";
    public static final String Device_Management_Advanced_text_Xpath_OR_Operator = "//android.widget.TextView[contains(@text,'ADVANCED') or @content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-AdvancedLabel']";
    public static final String Device_Management_Check_updates_text_Xpath_OR_Operator = "(//android.widget.TextView[contains(@text,'Check updates') or @content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-CheckUpdatesButton-Title'])[1]";
    public static final String Device_Management_Check_updates_navigation_Xpath_OR_Operator = "(//android.view.ViewGroup[@content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-CheckUpdatesButton-Container'])[1]/android.view.ViewGroup[2]";
    public static final String Device_Management_Check_updates_header_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'CHECK UPDATES') or @content-desc='com.dometicapp:id/CheckUpdatesScreen-header-centerTitleText']";
    public static final String Device_Management_Check_updates_Back_button_accessid="com.dometicapp:id/CheckUpdatesScreen-header-leftButtonImage";
    public static final String Device_Management_Check_updates_Refresh_button_accessid="com.dometicapp:id/CheckUpdatesScreen-header-rightButtonImage";
    public static final String Device_Management_Unregister_Delete_offboard_text_Xpath_OR_Operator = "(//android.view.ViewGroup[@content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-CheckUpdatesButton-Container'])[1]/android.view.ViewGroup[2]";
    public static final String Device_Management_Unregister_Delete_offboard_navigation_Xpath_OR_Operator ="(//android.view.ViewGroup[@content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-CheckUpdatesButton-Container'])[2]/android.view.ViewGroup[2]";
    public static final String Settings_Edit_profile_Header_text_accessid="com.dometicapp:id/header-TitleText";
    public static final String Settings_Edit_profile_CloseButton_accessid="com.dometicapp:id/header-leftButtonImage";
    public static final String Device_Management_back_button_access_id = "com.dometicapp:id/DeviceManagementScreen-leftButtonImage";
    public static final String Settings_notificationSettings_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Notification Settings') or @content-desc='com.dometicapp:id/sidemenu-notificationSettings-text']";
    public static final String Settings_viewEditButtonText_xpath_OR_operator = "//android.widget.TextView[contains(@text,'View/Edit Account') or @content-desc=\"com.dometicapp:id/sidemenu-viewEditButtonText\"]";
    public static final String Settings_home_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Home') or @content-desc=\"com.dometicapp:id/sidemenu-home-text\"]";
    public static final String Settings_deviceMangagement_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Device Management') or @content-desc=\"com.dometicapp:id/sidemenu-deviceMangagement-text\"]";
    public static final String Settings_appSettings_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'App Settings') or @content-desc=\"com.dometicapp:id/sidemenu-appSettings-text\"]";
    public static final String Settings_Logout_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Logout') or @content-desc=\"com.dometicapp:id/sidemenu-logout-text\"]";
    public static final String Settings_Version_16_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Version 1.') or @content-desc='com.dometicapp:id/sidemenu-versionText']";
    public static final String App_settings_header_xpath_OR_operator = "//android.widget.TextView[contains(@text,'APP SETTINGS') or @content-desc=\"com.dometicapp:id/header-TitleText\"]";

    public static final String Device_Management_back_button_xpath="android.view.ViewGroup[@content-desc='com.dometicapp:id/DeviceManagementDetailsScreen-header-header-leftButton']/android.view.ViewGroup";
    public static final String Settings_Device_Management_onboardedd_device_back_button_access_id = "com.dometicapp:id/DeviceManagementScreen-leftButtonImage";
    public static final String Settings_Edit_profile_firstname_text_accessid="com.dometicapp:id/editProfile-firstNameLabel";
    public static final String Settings_Edit_profile_firstname_value_accessid="com.dometicapp:id/editProfile-firstNNameValue";
    public static final String Settings_Edit_profile_lastname_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Last name') or @content-desc='com.dometicapp:id/editProfile-lastameLabel']\n";
    public static final String Settings_Edit_profile_lastname_value_accessid="com.dometicapp:id/editProfile-lastNameValue";
    public static final String Settings_Edit_profile_primaryMobile_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Primary mobile') or @content-desc='com.dometicapp:id/editProfile-phoneLabel']\n";
    public static final String Settings_Edit_profile_primaryMobile_value_accessid="com.dometicapp:id/editProfile-phoneValue";
    public static final String Settings_Edit_profile_address_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Address') or @content-desc='com.dometicapp:id/editProfile-addressLabel']\n";
    public static final String Settings_Edit_profile_address_value_accessid="com.dometicapp:id/editProfile-addressValue";
    public static final String Settings_Edit_profile_photo_accessid = "com.dometicapp:id/editProfile-photo";
    public static final String Settings_Edit_profile_emailvalue_accessid="com.dometicapp:id/editProfile-emailValue";
    public static final String Settings_Edit_profile_saveButton_accessid="com.dometicapp:id/editProfile-saveButtonText";
    public static final String Settings_Edit_profile_ok_button_xpath="//*[@text='OK']";
    public static final String Settings_Subscription_Header_xpath_or_operator = "//android.widget.TextView[contains(@text,'SUBSCRIPTIONS') or @content-desc='com.dometicapp:id/header-TitleText']";
    public static final String Settings_Subscription_Header_text = "SUBSCRIPTIONS";
    public static final String Settings_Subsriptions_Back_Button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    //-----------Account Settings--------------------//
    public static final String Settings_ViewEditAccount_accessid="com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String Settings_AccountSettings_header_accessid="com.dometicapp:id/header-TitleText";
    public static final String Settings_AccountSettings_header_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'ACCOUNT SETTINGS') or @content-desc='com.dometicapp:id/header-TitleText']";
    public static final String Settings_AccountSettings_profilePhoto_accessid="com.dometicapp:id/userSettings-profilePhoto";
    public static final String Settings_AccountSettings_userName_accessid="com.dometicapp:id/userSettings-userName";
    public static final String Settings_AccountSettings_user_email_accessid="com.dometicapp:id/userSettings-userEmail";
    public static final String Settings_AccountSettings_profile_Text_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'Profile') or @content-desc='com.dometicapp:id/userSettings-profile-cardTitle']";
    public static final String Settings_AccountSettings_profile_Settings_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'SETTINGS') or @content-desc='com.dometicapp:id/userSettings-settingText']";
    public static final String Settings_AccountSettings_profile_cardicon_accessid="com.dometicapp:id/userSettings-profile-cardIcon";
    public static final String Settings_AccountSettings_Subscription_text_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'Subscriptions') or@content-desc='com.dometicapp:id/userSettings-subscriptions-cardTitle']";
    public static final String Settings_AccountSettings_Subscription_cardicon_accessid="com.dometicapp:id/userSettings-subscriptions-cardIcon";

    //--------------profile page------------//
    public static final String Settings_profile_header_xpath_or_operator = "//android.widget.TextView[contains(@text,'PROFILE') or @content-desc='com.dometicapp:id/header-TitleText']\n";
    public static final String Settings_profile_photo_access_id = "com.dometicapp:id/userProfile-photo";
    public static final String Settings_profile_Persolnal_information_xpath_or_operator = "//android.widget.TextView[contains(@text,'PERSONAL INFORMATION') or @content-desc='com.dometicapp:id/userProfile-personalInfoText']";
    public static final String Settings_profile_Name_label_xpath_or_operator = "//android.widget.TextView[contains(@text,'Name') or @content-desc='com.dometicapp:id/userProfile-nameLabel']";
    public static final String Settings_profile_namevalues_accessid="com.dometicapp:id/userProfile-nameValue";
    public static final String Settings_profile_email_label_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-mail') or @content-desc='com.dometicapp:id/userProfile-emailLabel']\n";
    public static final String Settings_profile_emailvalues_accessid ="com.dometicapp:id/userProfile-emailValue";
    public static final String Settings_profile_mobile_label_xpath_or_operator = "//android.widget.TextView[contains(@text,'Mobile') or @content-desc='com.dometicapp:id/userProfile-phoneLabel']\n";
    public static final String Settings_profile_mobilevalues_accessid="com.dometicapp:id/userProfile-phoneValue";
    public static final String Settings_profile_address_label_xpath_or_operator = "//android.widget.TextView[contains(@text,'Address') or @content-desc='com.dometicapp:id/userProfile-addressLabel']\n";
    public static final String Settings_profile_addressvalues_accessid ="com.dometicapp:id/userProfile-addressValue";
    public static final String Settings_profile_Editprofile_label_xpath_or_operator = "//android.widget.TextView[contains(@text,'Edit Profile') or @content-desc='com.dometicapp:id/userProfile-EditProfileButton-cardTitle']\n";
    public static final String Settings_profile_Editprofile_cardicon_accessid ="com.dometicapp:id/userProfile-EditProfileButton-cardIcon";
    public static final String Settings_profile_Security_text_xpath_or_operator  = "//android.widget.TextView[contains(@text,'SECURITY') or @content-desc='com.dometicapp:id/userProfile-securityText']\n";
    public static final String Settings_profile_Password_text_xpath_or_operator= " //android.widget.TextView[contains(@text,'Password') or @content-desc='com.dometicapp:id/userProfile-resetPasswordText']\n";
    public static final String Settings_profile_Renew_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Renew') or @content-desc='com.dometicapp:id/userProfile-renew-cardTitle']\n";
    public static final String Settings_Profile_Renew_card_icon_access_id = "com.dometicapp:id/userProfile-renew-cardIcon";
    public static final String Settings_Profile_Back_Button_xpath  = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String Settings_profile_renew_cardicon_accessid ="com.dometicapp:id/userProfile-renew-cardIcon";


    public static final String Settings_App_settings_App_Setting_name_on_settings_page="com.dometicapp:id/sidemenu-appSettings-text";
    public static final String Settings_App_settings_App_setting_header_tile_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Settings_App_settings_App_setting_page_back_button_icon_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_App_settings_App_language_text_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_App_settings_language_text_collapse_button_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_App_settings_Temperature_text_access_id="com.dometicapp:id/setting-temperatureContainer";
    public static final String Settings_App_settings_Temperature_celcius_text_access_id="com.dometicapp:id/setting-celsiusText";
    public static final String Settings_App_settings_Temperature_fahrenheit_text_access_id="com.dometicapp:id/setting-fahrenheitText";
    public static final String Settings_App_settings_App_version_access_id="com.dometicapp:id/setting-versionText";
    public static final String Settings_App_settings_Language_header_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Settings_App_settings_Language_page_back_button_icon_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_App_settings_english_language_text_access_id="com.dometicapp:id/language-english-cardTitle";
    public static final String Settings_App_settings_spanish_language_text_access_id="com.dometicapp:id/language-spanish-cardTitle";
    public static final String Settings_App_settings_french_language_text_access_id="com.dometicapp:id/language-french-cardTitle";
    public static final String Settings_App_settings_german_language_text_access_id="com.dometicapp:id/language-german-cardTitle";
    public static final String Climate_main_tile_Celcius_unit_access_id="com.dometicapp:id/tile-climate-cardUnitText-0";
    public static final String Climate_main_tile_Fharanite_unit_access_id="com.dometicapp:id/tile-climate-cardUnitText-1";
    public static final String Climate_main_tile_inside_temp="com.dometicapp:id/climate-insideTemp";

    public static final String Settings_App_setting_header_text_expected="APP SETTINGS";
    public static final String Settings_App_setting_language_text_expected="Language";
    public static final String Settings_App_setting_temperature_text_expected="Temperature";
    public static final String Settings_App_setting_app_version_text_expected="App version";
    public static final String Settings_App_setting_Language_page_header_text_expected="LANGUAGE";
    public static final String Settings_App_setting_Language_page_English_text_expected="English";
    public static final String Settings_App_setting_Language_page_Spanish_text_expected="Spanish(US)";
    public static final String Settings_App_setting_Language_page_French_text_expected="French";
    public static final String Settings_App_setting_Language_page_German_text_expected="German";

    //-----------Account Settings Data--------------------//
    public static final String Settings_AccountSettings_header_text="ACCOUNT SETTINGS";
    public static final String Settings_AccountSettings_profile_text="Profile";
    public static final String Settings_AccountSettings_Settings_text="SETTINGS";
    public static final String Settings_AccountSettings_Subscription_text="Subscriptions";
    public static final String Settings_profile_header="PROFILE";
    public static final String Settings_profile_Persolnal_information="PERSONAL INFORMATION";
    public static final String Settings_profile_Name_label="Name";
    public static final String Settings_profile_email_label="E-mail";
    public static final String Settings_profile_mobile_label="Mobile";
    public static final String Settings_profile_address_label="Address";
    public static final String Settings_profile_Editprofile_label="Edit Profile";
    public static final String Settings_profile_Security_text="SECURITY";
    public static final String Settings_profile_Password_text="Password";
    public static final String Settings_profile_Renew_text="Renew";



    //-----------Manage Notifications--------------------//
    public static final String Header_menu_button_access_id = "com.dometicapp:id/header-menuButton";
    public static final String app_Settings_Back_Button_Access_Id = "com.dometicapp:id/header-menuButton";
    public static final String Notification_Settings_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Notification Settings') or @content-desc='com.dometicapp:id/sidemenu-notificationSettings-text']";
    public static final String ManageNotification_Manage_Notification_text_expected = "MANAGE NOTIFICATIONS";
    public static final String ManageNotifications_title_xpath_or_operator = "//android.widget.TextView[contains(@text,'MANAGE NOTIFICATIONS') or @content-desc='com.dometicapp:id/NotificationScreen-header-centerTitleText']";
    public static final String ManageNotifications_Back_button_access_id = "com.dometicapp:id/NotificationScreen-leftButtonImage";
    public static final String ManageNotifications_Logo_access_id = "com.dometicapp:id/notification-header-icon";
    public static final String ManageNotifications_Global_settings_Text_expected = "Global settings";
    public static final String ManageNotifications_Global_Settings_xpath_or_operator = "//android.widget.TextView[contains(@text,'Global settings') or\t @content-desc='com.dometicapp:id/notification-header-text']";
    public static final String ManageNotifications_Push_Notification_text_Expected = "Push notifications";
    public static final String ManageNotifications_PushNotification_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Push notifications') or  @content-desc='com.dometicapp:id/notification-pushNotificationContainer-Title']";
    public static final String manageNotifications_PushNotification_Show_More_Or_Show_Less_Access_ID = "com.dometicapp:id/notification-pushNotificationContainer-Expandable-label";
    public static final String ManageNotifications_PushNotifications_Toggle_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Switch";
    public static final String ManageNotifications_Email_text_expected = "E-mail";
    public static final String ManageNotifications_Email_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-mail') or  @content-desc='com.dometicapp:id/notification-emailNotification-Title']";
    public static final String ManageNotifications_email_toggle_access_id = "com.dometicapp:id/notification-emailNotification-Switch";
    public static final String ManageNotifications_SMS_text_expected = "SMS";
    public static final String ManageNotifications_SMS_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SMS') or  @content-desc='com.dometicapp:id/notification-smsNotification-Title']\n";
    public static final String ManageNotifications_SMS_toggle_access_id = "com.dometicapp:id/notification-smsNotification-Switch";
    public static final String ManageNotifications_Advanced_text_Expected = "ADVANCED";
    public static final String ManageNotifications_Advanced_Text_xpath_or_operator = "//android.widget.TextView[contains(@text,'ADVANCED') or  @content-desc='com.dometicapp:id/notification-advanceText']";
    public static final String ManageNotifications_Back_Button_access_id = "com.dometicapp:id/NotificationScreen-leftButtonImage";
    public static final String push_show_more_text_expected = "Show more";
    public static final String push_show_more_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show more') or  @content-desc='com.dometicapp:id/notification-pushNotificationContainer-Expandable-label']";
    public static final String push_show_more_navigation_icon_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Expandable-icon";
    public static final String push_show_less_text_expected = "Show less";
    public static final String push_show_less_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show less') or  @content-desc='com.dometicapp:id/notification-pushNotificationContainer-Expandable-label']";
    public static final String push_Alerts_text_expected = "Alerts";
    public static final String push_Alerts_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Alerts') or  @content-desc='com.dometicapp:id/notification-pushNotificationAlertText']\n";
    public static final String Manage_Notifications_push_alerts_toggle_access_id = "com.dometicapp:id/notification-pushNotificationAlertSwitch";
    public static final String push_Warnings_text_expected = "Warnings";
    public static final String Manage_Notifications_push_Warnings_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Warnings') or  @content-desc='com.dometicapp:id/notification-pushNotificationWarningText']\n";
    public static final String Manage_Notifications_push_warnings_toggle_access_id = "com.dometicapp:id/notification-pushNotificationWarningSwitch";
    public static final String Manage_Notifications_push_show_less_expand_icon_access_id = "com.dometicapp:id/notification-pushNotificationContainer-Expandable-icon";
    public static final String Email_show_more_text_expected = "Show more";
    public static final String Manage_Notifications_Email_show_more_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show more') or  @content-desc='com.dometicapp:id/notification-emailNotification-Expandable-label']\n";
    public static final String Manage_Notifications_Email_show_more_text_access_id = "com.dometicapp:id/notification-emailNotification-Expandable-label";
    public static final String Manage_Notifications_Email_show_more_navigation_icon_access_id = "com.dometicapp:id/notification-emailNotification-Expandable-icon";
    //    public static final String Manage_Notifications_Email_Show_more_Navigation_icon_access_id = "com.dometicapp:id/notification-emailNotification-Expandable-icon\n";
    public static final String Email_show_less_text_expected = "Show less";
    public static final String Manage_Notifications_Email_show_less_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show less') or  @content-desc='com.dometicapp:id/notification-emailNotification-Expandable-label']\n";
    public static final String Email_List_text_Expected = "E-MAIL LIST";
    public static final String Manage_Notifications_Email_List_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-MAIL LIST') or  @content-desc='com.dometicapp:id/notification-emailList-listTitle']\n";
    public static final String Email_list_Email_text_expected = "E-mail";
    public static final String Manage_Notifications_Email_List_Email_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-mail') or  @content-desc='com.dometicapp:id/notification-emailList0-Title']\n";
    public static final String Manage_Notifications_Email_List_Email_toggle_access_id = "com.dometicapp:id/notification-emailList0-Switch";
    public static final String Email_Edit_list_expected = "Edit list";
    public static final String Manage_Notifications_Email_Editlist_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Edit list') or  @content-desc='com.dometicapp:id/notification-emailList-subTitle']\n";
    public static final String Manage_Notifications_Email_Editlist_Text_Access_ID = "com.dometicapp:id/notification-emailList-subTitle";
    public static final String Notification_Addnew_Button = "com.dometicapp:id/editList-addElement-icon";
    public static final String Manage_Notifications_Email_Edit_List_Expand_icon_access_id = "com.dometicapp:id/notification-emailList-expandIcon";
    public static final String Email_list_title_text_expected = "E-MAIL LIST";
    public static final String Manage_Notifications_Email_List_title_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-MAIL LIST') or  @content-desc='com.dometicapp:id/editList-header-header-centerTitleText']\n";
    public static final String Manage_Notifications_Email_list_cancel_button_access_id = "com.dometicapp:id/editList-header-rightButtonIcon";
    public static final String Manage_Notifications_Email_List_Email_Text_Field_Access_ID = "com.dometicapp:id/editListElement0-subtitleInput";
    public static final String Manage_Notifications_Email_List_Label_Text_Field_Access_ID = "com.dometicapp:id/editListElement0-titleInput";
    public static final String Manage_Notifications_Email_List_Email_Text_Field_Subtitle_Validation = "com.dometicapp:id/editListElement0-subtitleValidation";
    public static final String Manage_Notifications_Email_List_Label_Text_Field_Subtitle_Validation = "com.dometicapp:id/editListElement0-titleValidation";
    public static final String Email_list_Email_Account_text_expected = "E-MAIL (ACCOUNT)";
    public static final String Manage_Notifications_Email_list_Email_Account_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'E-MAIL (ACCOUNT)') or  @content-desc='com.dometicapp:id/editList-mainAccount-title-text']\n";
    public static final String Email_list_Additional_Emails_text_expected = "ADDITIONAL E-MAILS";
    public static final String Manage_Notifications_Email_list_Additional_Emails_text_xpath_or_opertaor = "//android.widget.TextView[contains(@text,'ADDITIONAL E-MAILS') or  @content-desc='com.dometicapp:id/editList-aditionalAccounts-title-text']\n";
    public static final String Manage_Notifications_Email_list_Add_new_symbol_image_access_id = "com.dometicapp:id/editList-addElement-icon";
    public static final String Email_list_save_text_expected = "Save";
    public static final String Manage_Notifications_Email_list_save_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Save') or  @content-desc='com.dometicapp:id/editList-save-button-text']";
    public static final String Manage_Notifications_Email_List_close_button_access_id = "com.dometicapp:id/editList-header-rightButtonIcon";
    public static final String Email_list_Alerts_text_expected = "Alerts";
    public static final String Manage_Notifications_Email_list_Alerts_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Alerts') or  @content-desc='com.dometicapp:id/notification-emailNotificationAlertText']\n";
    public static final String Manage_Notifications_Email_list_Alerts_toggle_access_id = "com.dometicapp:id/notification-emailNotificationAlertSwitch";
    public static final String Email_list_warnings_text_expected = "Warnings";
    public static final String Manage_Notifications_Email_list_Warnings_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Warnings') or  @content-desc='com.dometicapp:id/notification-emailNotificationWarningContainerText']\n";
    public static final String Manage_Notifications_Email_list_Warnings_toggle_access_id = "com.dometicapp:id/notification-emailNotificationWarningContainerSwitch";
    public static final String Manage_Notifications_Email_show_less_expand_icon_access_id = "com.dometicapp:id/notification-emailNotification-Expandable-icon";
    public static final String Manage_Notifications_SMS_toggle_button_access_id = "com.dometicapp:id/notification-smsNotification-Switch";
    public static final String SMS_show_more_text_expected = "Show more";
    public static final String Manage_Notifications_SMS_show_more_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show more') or  @content-desc='com.dometicapp:id/notification-smsNotification-Expandable-label']\n";
    public static final String Manage_Notifications_SMS_show_more_text_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-label";
    public static final String Manage_Notifications_SMS_show_more_expand_icon_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-icon";
    public static final String SMS_Show_less_text_expected = "Show less";
    public static final String Manage_Notifications_SMS_Show_less_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show less') or  @content-desc='com.dometicapp:id/notification-smsNotification-Expandable-label']\n";
    public static final String SMS_show_less_text_expected = "Show less";
    public static final String Manage_Notifications_SMS_show_less_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Show less') or  @content-desc='com.dometicapp:id/notification-smsNotification-Expandable-label']\n";
    public static final String SMS_list_text_expected = "SMS LIST";
    public static final String Manage_Notifications_SMS_list_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SMS LIST') or  @content-desc='com.dometicapp:id/notification-smsList-listTitle']\n";
    public static final String SMS_Edit_list_text_expected = "Edit list";
    public static final String Manage_Notifications_SMS_Edit_list_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Edit list') or  @content-desc='com.dometicapp:id/notification-smsList-subTitle']";
    public static final String Manage_Notifications_SMS_Edit_list_Text_Access_ID = "com.dometicapp:id/notification-smsList-subTitle";
    public static final String Manage_Notifications_SMS_Edit_list_navigation_icon_access_id = "com.dometicapp:id/notification-smsList-expandIcon";
    public static final String SMS_list_title_text_expected = "SMS LIST";
    public static final String Manage_Notifications_SMS_list_title_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'SMS LIST') or @content-desc='com.dometicapp:id/editList-header-header-centerTitleText']";
    public static final String Manage_Notifications_SMS_List_cancel_button_access_id = "com.dometicapp:id/editList-header-rightButtonIcon";
    public static final String SMS_List_Mobile_Account_text_expected = "MOBILE (ACCOUNT)";
    public static final String Manage_Notifications_SMS_List_Mobile_Account_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'MOBILE (ACCOUNT)') or  @content-desc='com.dometicapp:id/editList-mainAccount-title-text']\n";
    public static final String SMS_List_Additional_SMS_text_expected = "ADDITIONAL SMS";
    public static final String Manage_Notifications_SMS_List_Additional_SMS_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'ADDITIONAL SMS') or  @content-desc='com.dometicapp:id/editList-aditionalAccounts-title-text']\n";
    public static final String SMS_list_Mobile_number_text_expected = "Mobile number";
    public static final String Manage_Notifications_SMS_list_Mobile_number_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Mobile number') or  @content-desc='com.dometicapp:id/editListElement0-subtitleLabel']";
    public static final String SMS_List_Label_text_expected = "Label";
    public static final String ManageNotifications_SMS_List_Label_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Label') or  @content-desc='com.dometicapp:id/editListElement0-titleLabel']\n";
    public static final String Manage_Notifications_SMS_Add_Symbol_xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/editList-addElement-icon']";
    public static final String SMS_List_save_text_expected = "Save";
    public static final String Manage_Notifications_SMS_List_save_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Save') or  @content-desc='com.dometicapp:id/editList-save-button-text']\n";
    public static final String Manage_Notifications_SMS_List_cancel_arrow_button_access_id = "com.dometicapp:id/editList-header-rightButtonIcon";
    public static final String SMS_List_Alerts_text_expected = "Alerts";
    public static final String Manage_Notifications_SMS_List_Alerts_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Alerts') or  @content-desc='com.dometicapp:id/notification-smsNotificationAlertText'] \n";
    public static final String Manage_Notifications_SMS_list_Alerts_toggle_access_id = "com.dometicapp:id/notification-smsNotificationAlertSwitch";
    public static final String SMS_List_Warnings_text_expected = "Warnings";
    public static final String Manage_Notifications_SMS_List_Warnings_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Warnings') or  @content-desc='com.dometicapp:id/notification-smsNotificationWarningText']\n";
    public static final String Manage_Notifications_SMS_list_Warnings_toggle_access_id = "com.dometicapp:id/notification-smsNotificationWarningSwitch";
    public static final String Manage_Notifications_SMS_show_less_icon_access_id = "com.dometicapp:id/notification-smsNotification-Expandable-icon";
    public static final String Manage_Notifications_Back_button_access_id = "com.dometicapp:id/NotificationScreen-leftButtonImage";
    public static final String Manage_Notifications_Email_List_Valid_Email_Address_access_id = "com.dometicapp:id/notification-emailList0-Subtitle";
    public static final String Manage_Notifications_Email_List_Valid_Label_access_id = "com.dometicapp:id/notification-emailList0-Title";
    public static final String Manage_Notifications_Email_List_Valid_Phone_Number_access_id = "com.dometicapp:id/notification-smsList0-Subtitle";
    public static final String Manage_Notifications_Email_List_Valid_Phone_Number_Label_access_id = "com.dometicapp:id/notification-smsList0-Title";
    public static final String Manage_Notifications_Email_List_Delete_Icon_Access_ID = "com.dometicapp:id/editListElement0-removeIcon";
    //-------------------Needed Accessibility Id-----------------//
    public static final String Settings_Language_Page_title_access_id="";
    public static final String Settings_language_Back_button_access_id="";
    public static final String Settings_Language_English_access_id="";
    public static final String Settings_back_button_access_id="";
    public static final String Settings_page_title_access_id="";
    public static final String Settings_temperature_unit_C_access_id="";
    public static final String Settings_temperature_unit_F_access_id="";

    // ----------------------xpath-----------------------------//
    public static final String Settings_text_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage'])[1]";
    public static final String Settings_Language_select_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[1]";
    public static final String Settings_Temperature_unit_xpath="(//*[@class='android.view.ViewGroup'])[17]";
    public static final String Settings_Upgrade_Firmware_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[2]";
    public static final String Settings_Version_xpath="//*[@content-desc='com.dometicapp:id/setting-versionContainer']";
    public static final String Settings_Logout_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/setting-logOutContainer']/android.view.ViewGroup";
    public static final String Settings_Language_Page_title_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_language_Back_button_xpath="//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup/android.widget.ImageView";
    public static final String Settings_Language_English_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/language-englishContainer\"]";
    public static final String Settings_back_button_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]";
    public static final String Settings_page_title_xpath= "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_temperature_unit_C_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[1]/android.view.ViewGroup/android.widget.TextView";
    public static final String Settings_temperature_unit_F_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.TextView\n";
    public static final String Settings_language_Spanish_xpath="//*[@text='Spanish (US)']";
    public static final String Settings_language_French_xpath="//*[@text='French']";
    public static final String Settings_language_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageText'])[1]";
    public static final String Settings_Zone_Management_xpath="(//*[@content-desc='com.dometicapp:id/setting-scrollView']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_edit_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_LimitedZones_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_xpath="(//*[@content-desc='com.dometicapp:id/zoneManagement-flatList']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_value_xpath="//android.widget.EditText[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_SAVE_Button_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_CANCEL_Button_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_flatListItem_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-flatListItem-')]//following::android.view.ViewGroup)[2]";
    public static final String Settings_Zone_Management_deleteZoneAlert_description_xpath="//*[@content-desc='com.dometicapp:id/zoneManagement-deleteZoneAlert-description']";
    public static final String Settings_Zone_Management_deleteZone_xpath="//*[@text='YES, DELETE IT']";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-selectButton']";
    public static final String Settings_Zone_Management_new_Zone_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-undefined']";
    public static final String Settings_Zone_Management_Zone_name_already_present_xpath="//*[@text='Zone name already present']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-saveButton']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-cancelButton']";
    public static final String Device_Management_xpath = "//android.widget.TextView[contains(@text,'Device Management') or @content-desc='com.dometicapp:id/sidemenu-deviceMangagement-text']";
    public static final String Device_Management_Edit_vessel_header_xpath = "//*[@content-desc=\"com.dometicapp:id/header-TitleText\"]\n";
    public static final String Device_Management_Edit_vessel_close_button_xpath = "//android.view.ViewGroup[@content-desc='com.dometicapp:id/header-rightButton']/android.widget.TextView";

    // ----------------------Data-----------------------------//
    public static final String Device_Management_header_text = "DEVICE MANAGEMENT";
    public static final String Vessel_information_text = "VESSEL INFORMATION";
    public static final String Name_text = "Name";
    public static final String MAC_address_text = "MAC Address";
    public static final String Edit_vessel_text = "Edit vessel";
    public static final String Edit_vessel_header_text = "EDIT VESSEL";
    public static final String Edit_vessel_name_text = "Name";
    public static final String Edit_vessel_MAC_address_text = "Mac Address";
    public static final String Save_text = "Save";
    public static final String Advanced_text = "ADVANCED";
    public static final String Check_updates_text = "Check updates";
    public static final String Check_updates_header_text = "CHECK UPDATES";
    public static final String Unregister_Offboard_Delete_text = "Unregister/Delete/Offboard";
    public static final String Settings_viewEditButtonText = "View/Edit Account";
    public static final String Settings_home_text = "Home";
    public static final String Settings_notificationSettings_text = "Notification Settings";
    public static final String Settings_deviceMangagement_text = "Device Management";
    public static final String Settings_appSettings_text = "App Settings";
    public static final String Settings_Logout_text = "Logout";
    public static final String Settings_Version_16_text = "Version 1.7.4";
    public static final String Manage_Notifications_Email_List_Email_Text_Field_Subtitle_Validation_Data = "The email 0 field is required.";
    public static final String Manage_Notifications_Email_List_Email_Text_Field_Emojis_Subtitle_Validation_Data ="The email 0 must be a valid email address.";
    public static final String Manage_Notifications_Email_List_Label_Text_Field_Subtitle_Validation_Data = "The label 0 field is required.";
    public static final String Manage_Notifications_Email_List_Valid_Email_Address = "dometic@yopmail.com";
    public static final String Manage_Notifications_Email_List_Valid_Label = "Dometic";
    public static final String Manage_Notifications_Email_List_Valid_Phone_Number = "+448762961653";
    //----------------Edit Profile Data--------------//
    public static final String Settings_Edit_profile_Header_text="EDIT PROFILE";
    public static final String Settings_Edit_profile_firstname_text="First name";
    public static final String Settings_Edit_profile_lastname_text="Last name";
    public static final String Settings_Edit_profile_primaryMobile_text="Primary mobile";
    public static final String Settings_Edit_profile_address_text="Address";
    public static final String editProfile_firstNameValue="RAMESH";
    public static final String editProfile_lastameValue="BABU";
    public static final String editProfile_firstNameValue_SpecialCharacter="!@#$%^&*()_+";
    public static final String editProfile_lastameValue_SpecialCharacter="+_)(*&^%$#@!";
    public static final String grinning_face_with_smiling_eyes = new String(Character.toChars(0x1F601));
    public static final String face_with_tears_of_joy = new String(Character.toChars(0x1F602));
    public static final String smiling_face_with_open_mouth_and_cold_sweat = new String(Character.toChars(0x1F605));
    public static final String smiling_face_with_open_mouth_and_tightly_closed_eyes = new String(Character.toChars(0x1F606));
    public static final String winking_face = new String(Character.toChars(0x1F609));
    public static final String editProfile_phoneValue="+919003034122";
    public static final String editProfile_addressValue="CHENNAI";
    public static final String editProfile_addressValue_SpecialCharacter="!@#$%^&*()_+";
    public static final String Device_name_New_data = "Test12345DevicenamecheckL2Usertest@123byDOM";
    public static final String Device_name_valid_data = "AMTH";
    public static final String Device_name_invalid_data = "%$%***(#@%^&%";
    // public static final String Settings_AccountSettings_Subscription_text_Xpath_OR_Operator="//android.widget.TextView[contains(@text,'Subscriptions') or@content-desc='com.dometicapp:id/userSettings-subscriptions-cardTitle']";

    // public static final String App_settings_header_xpath_OR_operator = "//android.widget.TextView[contains(@text,'APP SETTINGS') or @content-desc=\"com.dometicapp:id/header-TitleText\"]";

    public static final String Language_text_xpath = "(//android.widget.TextView[@content-desc=\"com.dometicapp:id/setting-languageText\"])[1]";

    public static final String Temperature_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'Temperature') or @content-desc=\"com.dometicapp:id/setting-temperatureContainer\"]";

    public static final String App_version_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'App version') or @content-desc=\"com.dometicapp:id/setting-versionText\"]";
    public static final String Language_header_xpath_OR_operator = "//android.widget.TextView[contains(@text,'LANGUAGE') or @content-desc=\"com.dometicapp:id/header-TitleText\"]";

    public static final String Language_English_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'English') or @content-desc=\"com.dometicapp:id/language-english-cardTitle\"]";

    public static final String Language_German_text_xpath_OR_operator = "//android.widget.TextView[contains(@text,'German') or @content-desc=\"com.dometicapp:id/language-german-cardTitle\"]";
    public static final String Language_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String Language_navigation_button_access_id = "com.dometicapp:id/setting-languageExpandIcon";
    public static final String Climate_tile_Units_access_id = "com.dometicapp:id/tile-climate-cardUnitText-0";
    public static final String Selected_Language_text_English_xpath_OR_operator = "//android.widget.TextView[contains(@text,'English') or @content-desc=\"com.dometicapp:id/setting-selectedLanguage\"]";
    public static final String Selected_Language_text_German_xpath_OR_operator = "//android.widget.TextView[contains(@text,'German') or @content-desc=\"com.dometicapp:id/setting-selectedLanguage\"]";
    public static final String Settings_AccountSettings_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String Manage_Notifications_back_button_access_id = "com.dometicapp:id/NotificationScreen-leftButtonImage";
    public static final String App_settings_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";
    public static final String Settings_Account_settings_Back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup";

    public static final String Edit_Profile_Cancel_Button_access_id = "com.dometicapp:id/header-leftButtonImage";

    public static final String advanced_text_expected = "ADVANCED";
    public static final String advanced_text_access_id1 = "com.dometicapp:id/NotificationScreen-header-centerTitleText";
    public static final String AMTH_access_id = "com.dometicapp:id/notification-AdvancedNotificationSettings--Title";
    public static final String AMTH_text_expected = "AMTH";
    public static final String AMTH_text_access_id = "com.dometicapp:id/notification-deviceNotificationHeader-text";
    public static final String pushnotification_text_expected = "Push notifications";
    public static final String pushnotification_text_access_id = "com.dometicapp:id/notification-devicePushNotifications-Title";
    public static final String Email_text_expected = "E-mail";
    public static final String Email_text_access_id = "com.dometicapp:id/notification-deviceEmailNotifications-0-Title";
    public static final String sms_text_expected = "SMS";
    public static final String sms_text_access_id = "com.dometicapp:id/notification-deviceSmsNotifications-1-Title";

    public static final String batteries_text_expected = "Batteries";
    public static final String batteries_text_access_id = "com.dometicapp:id/notification-deviceNotification-Batteries-Title";
    public static final String showmore_navigationbutton_access_id = "com.dometicapp:id/notification-deviceNotification-Batteries-Expandable-icon";
    public static final String batteries_pushnotification_text_expected = "Push notifications";
    public static final String batteries_pushnotification_text_access_id = "com.dometicapp:id/notification-deviceNotification-Batteries-Alerts0-Title";
    public static final String tanks_text_expected = "Tanks";
    public static final String tanks_text_access_id = "com.dometicapp:id/notification-deviceNotification-Tanks-Title";
    public static final String showmore_navigationbutton_access_id1 = "com.dometicapp:id/notification-deviceNotification-Tanks-Expandable-icon";
    public static final String tanks_pushnotification_text_expected = "Push notifications";
    public static final String tanks_pushnotification_text_access_id = "com.dometicapp:id/notification-deviceNotification-Tanks-Alerts0-Title";
    public static final String showmore_navigationbutton_access_id2 = "com.dometicapp:id/notification-deviceNotification-Temperature-Expandable-icon";
    public static final String temperature_pushnotification_text_expected = "Push notifications";
    public static final String temperature_pushnotification_text_access_id = "com.dometicapp:id/notification-deviceNotification-Temperature-Alerts0-Title";
    public static final String temperature_text_expected="Temperature";
    public static final String temperature_text_access_id= "com.dometicapp:id/notification-deviceNotification-Temperature-Title";
    public static final String Advance_back_button_accessid="com.dometicapp:id/NotificationScreen-leftButtonImage";

}


