package com.dometic.L2.qa.Pages;

public class Constant_landingscreen {
    // -------------------------Accesibility_Id---------------//
    public static final String LandingPage_allow_popup_access_id="com.android.packageinstaller:id/permission_allow_button";
    public static final String LandingPage_background_image_access_id="com.dometicapp:id/scanBle-backgroundImage";
    public static final String LandingPage_brand_logo_access_id="com.dometicapp:id/scanBle-brandLogo";
    public static final String LandingPage_search_text_access_id="com.dometicapp:id/scanBle-searchText";
    public static final String LandingPage_add_product_button_access_id="com.dometicapp:id/scanBle-iconAddProduct";
    public static final String LandingPage_add_product_text_access_id="com.dometicapp:id/scanBle-addProduct";
    public static final String LandingPage_back_button_access_id="com.dometicapp:id/gateway-backButtonImage";
    public static final String LandingPage_title_access_id="";
    public static final String LandingPage_serialNumber_inputBox_access_id="com.dometicapp:id/gateway-serialNumberField";
    public static final String LandingPage_serialNumber_format_text_access_id="com.dometicapp:id/gateway-serialFormat";
    public static final String LandingPage_QR_code_scanner_access_id="com.dometicapp:id/gateway-qrIcon";
    public static final String LandingPage_QR_code_text_access_id="com.dometicapp:id/gateway-scanText";
    public static final String LandingPage_popUp_close_button_access_id="com.dometicapp:id/tiles-overlayCloseIcon";
    public static final String LandingPage_popUp_title_access_id="com.dometicapp:id/tiles-successfulPairing";
    public static final String LandingPage_popUp_text_access_id="com.dometicapp:id/tiles-dometicAppText";
    public static final String LandingPage_popUp_unchecked_checkbox_access_id="com.dometicapp:id/tiles-uncheckedIconSuccessfulPairing";
    public static final String LandingPage_popUp_checked_checkbox_access_id="com.dometicapp:id/tiles-checkedIconSuccessfulPairing";
    public static final String LandingPage_updated_time_access_id="com.dometicapp:id/tiles-lastShadowText";
    public static final String LandingPage_Update_Firmware_CANCEL="android:id/button2";
    public static final String LandingPage_Update_Firmware_OK="android:id/button1";
    public static final String LandingPage_hamburger_menu_access_id="com.dometicapp:id/header-menuButton";
    public static final String LandingPage_Climate_Inside_text_access_id="com.dometicapp:id/tiles-Climate-0-Climate";
    public static final String LandingPage_Climate_Aircondition_text_access_id="com.dometicapp:id/tiles-Climate-0-Aircondition";
    public static final String LandingPage_Climate_unit_maincontent_access_id="com.dometicapp:id/tiles-Climate-0-mainContent";
    public static final String LandingPage_Climate_unit_access_id="com.dometicapp:id/tiles-Climate-0-unit";
    public static final String LandingPage_Climate_Inside_FanIcon_access_id="com.dometicapp:id/tiles-Climate-0-fanIcon";
    public static final String LandingPage_Climate_Inside_FanSpeedText_access_id="com.dometicapp:id/tiles-Climate-0-fanSpeedText";
    public static final String LandingPage_Climate_Outside_access_id="com.dometicapp:id/tiles-Climate-1-Climate";
    public static final String LandingPage_Climate_Outside_text_access_id="com.dometicapp:id/tiles-Climate-1-Outside";
    public static final String LandingPage_Climate_outside_unit_maincontent_access_id="com.dometicapp:id/tiles-Climate-1-mainContent";
    public static final String LandingPage_Climate_outside_unit_access_id="com.dometicapp:id/tiles-Climate-1-unit";
    public static final String LandingPage_Power_text_access_id="com.dometicapp:id/tiles-Power-3-Power";
    public static final String LandingPage_Power_HouseBattery_text_access_id="com.dometicapp:id/tiles-Power-3-House Battery";
    public static final String LandingPage_Power_percentage_access_id="com.dometicapp:id/tiles-Power-3-mainContent";
    public static final String LandingPage_Tank_Fresh_text_access_id="com.dometicapp:id/tiles-Tank-6-Tank";
    public static final String LandingPage_Tank_FreshwaterTank_text_access_id="com.dometicapp:id/tiles-Tank-6-Freshwater Tank";
    public static final String LandingPage_Tank_FreshwaterTank_percentage_access_id="com.dometicapp:id/tiles-Tank-6-mainContentView";
    public static final String LandingPage_Tank_Grey_text_access_id="com.dometicapp:id/tiles-Tank-7-Tank";
    public static final String LandingPage_Tank_GreywaterTank_text_access_id="com.dometicapp:id/tiles-Tank-7-Greywater Tank";
    public static final String LandingPage_Tank_GreywaterTank_percentage_access_id="com.dometicapp:id/tiles-Tank-7-mainContentView";
    public static final String LandingPage_Climate_text_expected="Climate";
    public static final String LandingPage_Climate_inside_Aircondition_text_expected="Aircondition";
    public static final String LandingPage_Climate_Outside_text_expected="Outside";
    public static final String LandingPage_Power_text_expected="Power";
    public static final String LandingPage_Power_HouseBattery_text_expected="House Battery";
    public static final String LandingPage_Tank_text_expected="Tank";
    public static final String LandingPage_Tank_Freshwater_Tank_text_expected="Freshwater Tank";
    public static final String LandingPage_Tank_Greywater_Tank_text_expected="Greywater Tank";
    public static final String LandingPage_climate_tile_access_id="com.dometicapp:id/tiles-Climate-0";
    public static final String LandingPage_climate_tile_germen_access_id="com.dometicapp:id/tiles-Klima-0";
    public static final String LandingPage_climate_outSide_tile_access_id="com.dometicapp:id/tiles-Climate-1";
    public static final String LandingPage_power_tile_access_id="com.dometicapp:id/tiles-Power-3";
    public static final String LandingPage_power_germen_tile_access_id="com.dometicapp:id/tiles-Energie-3";
    public static final String LandingPage_freshWater_tank_tile_access_id="com.dometicapp:id/tiles-Tank-6";
    public static final String LandingPage_grayWater_tank_tile_access_id="com.dometicapp:id/tiles-Tank-7";
    public static final String LandingPage_remainder_view_onclick_access_id="com.dometicapp:id/remainderView-onClick";
    public static final String LandingPage_remainderView_iconClose_access_id="com.dometicapp:id/remainderView-iconClose";
    public static final String LandingPage_header_brandLogo_access_id="com.dometicapp:id/header-brandLogo";
    public static final String LandingPage_apply_button_access_id="com.dometicapp:id/climate-applyTemperature";


    //-------------------Needed Accessibility Id-----------------//
    public static final String LandingPage_connect_button_access_id="";
    public static final String LandingPage_popUp_Click_here_link_access_id="";
    public static final String LandingPage_popUp_checkbox_alert_text_access_id="";
    public static final String LandingPage_mainScreen_BrandLogo_access_id="";
    public static final String LandingPage_connection_symbol_access_id="";
    public static final String LandingPage_menu_button_access_id="";
    public static final String LandingPage_Upgrade_Firmware_text_access_id="";
    public static final String LandingPage_New_firmware_is_available_Goto_settings_for_upgrade_text_access_id="";
    public static final String LandingPage_right_side_tile_view_access_id="";
    public static final String LandingPage_1stclimate_tile_access_id="";
    public static final String LandingPage_1stclimate_text_access_id="";
    public static final String LandingPage_1stmainCardText_access_id="";
    public static final String LandingPage_1stcardUnitText_access_id="";
    public static final String LandingPage_1stfanIcon_access_id="";
    public static final String LandingPage_1stfanSpeedText_access_id="";
    public static final String LandingPage_2ndclimate_tile_access_id="";
    public static final String LandingPage_2ndclimate_text_access_id="";
    public static final String LandingPage_2ndmainCardText_access_id="";
    public static final String LandingPage_2ndcardUnitText_access_id="";
    public static final String LandingPage_2ndfanIcon_access_id="";
    public static final String LandingPage_2ndfanSpeedText_access_id="";
    public static final String LandingPage_L2power_tile_access_id="";
    public static final String LandingPage_L2power_text_access_id="";
    public static final String LandingPage_L2Power_HouseBattery_text_access_id="";
    public static final String LandingPage_L2Power_mainCardText_access_id="";
    public static final String LandingPage_L2Power_cardUnitText_access_id="";
    public static final String LandingPage_L2Power_warningText_access_id="";
    public static final String LandingPage_L2light_tile_access_id="";
    public static final String LandingPage_L2light_text_access_id="";
    public static final String LandingPage_L2light_CurentlyOn_text_access_id="";
    public static final String LandingPage_L2light_mainCardText_access_id="";
    public static final String LandingPage_L2AGS_tile_access_id="";
    public static final String LandingPage_L2AGS_text_access_id="";
    public static final String LandingPage_L2AGS_AutoCharger_text_access_id="";
    public static final String LandingPage_L2AGS_mainCardText_access_id="";
    public static final String LandingPage_L2Fuses_tile_access_id="";
    public static final String LandingPage_L2Fuses_text_access_id="";
    public static final String LandingPage_L2Fuses_AllOK_access_id="";
    public static final String LandingPage_L2Fuses_mainCardText_access_id="";
    public static final String LandingPage_L2Mechanical_tile_access_id="";
    public static final String LandingPage_L2Mechanical_text_access_id="";
    public static final String LandingPage_L2Mechanical_Awning_text_access_id="";
    public static final String LandingPage_L2Mechanical_mainCardText_access_id="";
    public static final String LandingPage_L2Tank_Fresh_tile_access_id="";
    public static final String LandingPage_L2Tank_Fresh_text_access_id="";
    public static final String LandingPage_L2Tank_Fresh_Water_text_access_id="";
    public static final String LandingPage_L2Tank_Fresh_mainCardText_access_id="";
    public static final String LandingPage_L2Tank_Fresh_cardUnitText_access_id="";
    public static final String LandingPage_L2Tank_Fresh_warningText_access_id="";
    public static final String LandingPage_L2Tank_Fresh_warningIcon_access_id="";
    public static final String LandingPage_L2Tank_Black_tile_access_id="";
    public static final String LandingPage_L2Tank_Black_text_access_id="";
    public static final String LandingPage_L2Tank_Black_Water_access_id="";
    public static final String LandingPage_L2Tank_Black_mainCardText_access_id="";
    public static final String LandingPage_L2Tank_Black_cardUnitText_access_id="";

    //   --------------------xPath--------------//
    public static final String LandingPage_brand_logo_xpath="//*[@content-desc='com.dometicapp:id/scanBle-brandLogo']";
    public static final String LandingPage_Climate_off_xpath="//android.widget.TextView[@content-desc='com.dometicapp:id/tiles-Climate-0-OFF']";
    public static final String LandingPage_connect_button_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/gateway-connectButton\"]/android.widget.TextView";
    public static final String LandingPage_popUp_Click_here_link_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-clickHereButton\"]/android.widget.TextView";
    public static final String LandingPage_popUp_checkbox_alert_text_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-checkBoxContainerSuccessfulPairing\"]/android.widget.TextView";
    public static final String LandingPage_mainScreen_BrandLogo_xpath="hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.ImageView[3]\n";
    public static final String LandingPage_connection_symbol_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.ImageView[2]";
    public static final String LandingPage_menu_button_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.widget.ImageView\n";
    public static final String LandingPage_climate_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-flatGridItemCard\"])[2]";
    public static final String LandingPage_climate_outSide_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-flatGridItemCard\"])[4]";
    public static final String LandingPage_power_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-flatGridItemCard\"])[6]";
    public static final String LandingPage_freshWater_tank_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-flatGridItemCard\"])[8]/android.view.ViewGroup";
    public static final String LandingPage_grayWater_tank_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tiles-flatGridItemCard\"])[10]/android.view.ViewGroup";
    public static String LandingPage_Update_Firmware_CANCEL_xpath="//*[@resource-id='android:id/button2']";
    public static final String LandingPage_Update_Firmware_OK_xpath="//*[@resource-id='android:id/button1']";
    public static final String LandingPage_Climate_Aircondition_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/tiles-Climate-0']/android.view.ViewGroup";
    public static final String LandingPage_Climate_Outside_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/tiles-Climate-1']/android.view.ViewGroup";
    public static final String LandingPage_Power_House_Battery_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/tiles-Power-3']/android.view.ViewGroup";
    public static final String LandingPage_Tank_Fresh_Water_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/tiles-Tank-6']/android.view.ViewGroup";
    public static final String LandingPage_Tank_grey_water_tank_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/tiles-Tank-7']/android.view.ViewGroup";
    public static final String LandingPage_Firmware_popup_xpath="//*[@resource-id='android:id/parentPanel']";
    public static final String LandingPage_LATER_button_xpath="//*[@resource-id='android:id/button2']";
    public static final String LandingPage_UPGRADE_button_xpath="//*[@resource-id='android:id/button1']";
    public static final String LandingPage_Upgrade_Firmware_text_xpath="//*[@text='Upgrade Firmware']";
    public static final String LandingPage_New_firmware_is_available_Goto_settings_for_upgrade_text_xpath="//*[@text='New firmware is available! Goto settings for upgrade.']";
    public static final String LandingPage_remainderView_iconClose_xpath="//*[@content-desc='com.dometicapp:id/remainderView-iconClose']";
    public static final String LandingPage_right_side_tile_view_xpath="//*[@content-desc='com.dometicapp:id/header-brandLogo']//following::android.view.ViewGroup[1]";
    public static final String LandingPage_remainder_view_onclick_xpath="//*[@content-desc='com.dometicapp:id/remainderView-onClick']";
    public static final String LandingPage_header_connectionType_xpath="//*[@content-desc='com.dometicapp:id/header-connectionType']";
    public static final String LandingPage_header_brandLogo_xpath="//*[@content-desc='com.dometicapp:id/header-brandLogo']";
    public static final String LandingPage_L21stclimate_tile_xpath="(//*[@content-desc='com.dometicapp:id/tiles-refreshControl']//following::android.widget.TextView)[1]";
    public static final String LandingPage_L21stclimate_text_xpath="(//*[@text='Climate'])[1]";
    public static final String Landing_Home_screen_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/Dashboard-card\"]/android.view.ViewGroup/android.view.ViewGroup[1]";
    public static final String LandingPage_L21stcool_text_xpath="(//*[@text='Cool'])[1]";
    public static final String LandingPage_L21stmainCardText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-mainCardText\"])[1]";
    public static final String LandingPage_L21stcardUnitText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-cardUnitText\"])[1]";
    public static final String LandingPage_L21stfanIcon_xpath="(//*[@content-desc='com.dometicapp:id/tile-fanIcon'])[1]";
    public static final String LandingPage_L21stfanSpeedText_xpath="(//*[@text='Low'])[1]";
    public static final String LandingPage_L21stwarningText_xpath="(//*[@text='Temp out of range!'])[1]";
    public static final String LandingPage_L21stwarningIcon_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tile-warningIcon\"])[1]";
    public static final String LandingPage_L22ndclimate_text_xpath="(//*[@text='Climate'])[2]";
    public static final String LandingPage_L22ndcool_text_xpath="(//*[@text='Cool'])[2]";
    public static final String LandingPage_L22ndmainCardText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-mainCardText\"])[2]";
    public static final String LandingPage_L22ndcardUnitText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-cardUnitText\"])[2]";
    public static final String LandingPage_L22ndfanIcon_xpath="(//*[@content-desc='com.dometicapp:id/tile-fanIcon'])[2]";
    public static final String LandingPage_L22ndfanSpeedText_xpath="(//*[@text='Low'])[2]";
    public static final String LandingPage_L22ndwarningText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-warningText\"])[2]";
    public static final String LandingPage_L22ndwarningIcon_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tile-warningIcon\"])[2]";
    public static final String LandingPage_L2power_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tile\"])[3]/android.view.ViewGroup";
    public static final String LandingPage_L2power_text_xpath="//*[@text='Power']";
    public static final String LandingPage_L2HPower_HouseBattery_text_xpath="//*[@text='House Battery']";
    public static final String LandingPage_L2Power_mainCardText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-mainCardText\"])[3]";
    public static final String LandingPage_L2Power_cardUnitText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-cardUnitText\"])[3]";
    public static final String LandingPage_L2Power_warningText_xpath="//*[@text='Charge Battery!']";
    public static final String LandingPage_L2light_tile_xpath="//*[@text='Light']";
    public static final String LandingPage_L2light_text_xpath="//*[@text='Power']";
    public static final String LandingPage_L2light_CurentlyOn_text_xpath="//*[@text='Currently ON']";
    public static final String LandingPage_L2light_mainCardText_xpath="(//*[@content-desc='mainContentView'])[4]";
    public static final String LandingPage_L2AGS_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tile\"])[5]";
    public static final String LandingPage_L2AGS_text_xpath="//*[@text='AGS']";
    public static final String LandingPage_L2AGS_AutoCharger_text_xpath="//*[@text='Auto Charger']";
    public static final String LandingPage_L2AGS_mainCardText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-mainCardText\"])[5]";
    public static final String LandingPage_L2Fuses_tile_xpath="(//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/tile\"])[6]";
    public static final String LandingPage_L2Fuses_text_xpath="//*[@text='Fuses']";
    public static final String LandingPage_L2Fuses_AllOK_xpath="//*[@text='All OK']";
    public static final String LandingPage_L2Fuses_mainCardText_xpath="(//android.widget.TextView[@content-desc=\"com.dometicapp:id/tile-mainCardText\"])[6]";
    public static final String LandingPage_L2Mechanical_tile_xpath="";
    public static final String LandingPage_L2Mechanical_text_xpath="//*[@text='Mechanical']";
    public static final String LandingPage_L2Mechanical_Awning_text_xpath="//*[@text='Awning']";
    public static final String LandingPage_L2Mechanical_mainCardText_xpath="";
    public static final String LandingPage_L2Tank_Fresh_tile_xpath="";
    public static final String LandingPage_L2Tank_Fresh_text_xpath="(//*[@text='Tank'])[1]";
    public static final String LandingPage_L2Tank_Fresh_Water_text_xpath="//*[@text='Fresh Water']";
    public static final String LandingPage_L2Tank_Fresh_mainCardText_xpath="";
    public static final String LandingPage_L2Tank_Fresh_cardUnitText_xpath="";
    public static final String LandingPage_L2Tank_Fresh_warningText_xpath="//*[@text='Fill Fresh Tank!']";
    public static final String LandingPage_L2Tank_Fresh_warningIcon_xpath="";
    public static final String LandingPage_L2Tank_Black_tile_xpath="";
    public static final String LandingPage_L2Tank_Black_text_xpath="(//*[@text='Tank'])[2]";
    public static final String LandingPage_L2Tank_Black_Water_text_xpath="//*[@text='Black Water']";
    public static final String LandingPage_L2Tank_Black_mainCardText_xpath="";
    public static final String LandingPage_L2Tank_Black_cardUnitText_xpath="";
    public static final String LandingPage_BottomLayout_All_icon_access_id="com.dometicapp:id/categoryTabBarItemIcon-All";

    public static final String LandingPage_BottomLayout_All_xpath="//*[@text='All']";
    public static final String LandingPage_BottomLayout_Climate_xpath="//*[@text='Climate']";

    public static final String LandingPage_BottomLayout_Climate_icon_access_id="com.dometicapp:id/categoryTabBarItemIcon-Climate";
    public static final String LandingPage_BottomLayout_Climate_text_xpath="(//*[@text='Climate'])[2]";
    public static final String LandingPage_BottomLayout_Climate2tile_text_xpath="(//*[@text='Climate'])[2]";
    public static final String LandingPage_Climate_text_xpath="(//*[@text='Climate'])[1]";

    public static final String LandingPage_BottomLayout_Device_icon_access_id="com.dometicapp:id/categoryTabBarItemIcon-Devices";
    public static final String LandingPage_BottomLayout_Device_xpath="//*[@text='Devices']";
    public static final String LandingPage_BottomLayout_scenes_icon_access_id="com.dometicapp:id/categoryTabBarItemIcon-Scenes";
    public static final String LandingPage_BottomLayout_Tanks_icon_access_id="com.dometicapp:id/categoryTabBarItemIcon-Tanks";
    public static final String LandingPage_BottomLayout_Tanks_Text_xpath="//*[@text='Tanks']";
    public static final String LandingPage_Tank_text_xpath="(//*[@text='Tank'])[1]";
    public static final String LandingPage_BottomLayout_Scene_xpath="//*[@text='Scenes']";
    public static final String Landingpage_Bottomlayout_Tank_Text="Tank";
    public static final String Landingpage_Bottomlayout_Climate_Text="Climate";
    public static final String Landingpage_Bottomlayout_AGS_Text="AGS";
    public static final String Landingpage_Header_Hamburger_xpath="//*[@content-desc='com.dometicapp:id/header-menuButton']";
    public static final String Landingpage_LastShowText_xpath="//*[@content-desc='com.dometicapp:id/tiles-lastShadowText']";
//    ------------------------------------------------------------------------------------------------------------------------
//    Climate and Tanks

    public static final String Landing_Home_AMTH_icon_access_id = "com.dometicapp:id/Dashboard-cardText";
    public static final String Landing_climate_text_expected = "Climate";
    public static final String Landing_climate_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Climate') or @content-desc='com.dometicapp:id/tile-climate-titleView']\n";
    public static final String Landing_climate_tile_access_id = "com.dometicapp:id/tile-climate-titleView";
    public static final String Climate_back_image_access_id = " , back";
    public static final String Climate_back_image_xpath = "//android.widget.Button[@content-desc=\" , back\"]";
    public static final String Climate_Inside_degree_text_expected = "Inside 0°C";
    public static final String Climate_Inside_degree_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Inside 0°C') or @content-desc='com.dometicapp:id/climate-insideTemp']\n";
    public static final String All_climate_text_expected = "All Climate";
    public static final String All_climate_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'All Climate') or @content-desc='ElementIdConstants.Climate.allClimate-cardTitle']\n";
    public static final String Climate_Allclimate_Off_text_expected = "OFF";
    public static final String Climate_Allclimate_Off_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'OFF') or @content-desc='ElementIdConstants.Climate.allClimate-switchText']";
    public static final String Climate_Allclimate_toggle_access_id = "ElementIdConstants.Climate.allClimate-switchComponent";
    public static final String Climate_Allclimate_toggle_xpath = "//android.view.ViewGroup[@content-desc=\"ElementIdConstants.Climate.allClimate-switchComponent\"]\n";
    public static final String Settings_Hamburger_access_id = "com.dometicapp:id/header-menuButton";
    public static final String Settings_Hamburger_xpath = "//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/header-menuButton\"]";
    public static final String Settings_Home_xpath = "//android.widget.TextView[@content-desc=\"com.dometicapp:id/sidemenu-home-text\"]";
    public static final String Settings_Home_access_id = "com.dometicapp:id/sidemenu-home-text";
    public static final String Landing_tanks_text_expected = "Tank";
    public static final String Landing_tanks_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Tank') or @content-desc='com.dometicapp:id/tile-tank-titleView']";
    public static final String Landing_tanks_tile_access_id = "com.dometicapp:id/tile-tank-titleView";
    public static final String Tanks_back_button_access_id = " , back";
    public static final String Tanks_back_button_xpath = "//android.widget.Button[@content-desc=\" , back\"]";
    public static final String Tanks_circle_carousel_tank_icon_access_id = "com.dometicapp:id/Tank-circleCarousel-tankIcon-0";
    public static final String Tanks_circle_carousel_tank_unit_access_id = "com.dometicapp:id/Tank-circleCarousel-tankUnit-0";
    public static final String Battery_level_text_expected = "Battery Level";
    public static final String Battery_level_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Battery Level') or @content-desc='com.dometicapp:id/Tank-batteryLevel-cardTitle']";
    public static final String Tanks_Battery_level_value_access_id = "com.dometicapp:id/Tank-batteryLevel-cardSubText";
    public static final String Bluetooth_Signal_text_expected = "Bluetooth Signal";
    public static final String Bluetooth_signal_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Bluetooth Signal') or @content-desc='com.dometicapp:id/Tank-bluetoothSignal-cardTitle']\n";
    public static final String Tanks_Bluetooth_signal_value_access_id = "com.dometicapp:id/Tank-bluetoothSignal-cardSubText";
    public static final String MAC_Address_text_expected = "MAC Address";
    public static final String MAC_Address_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'MAC Address') or @content-desc='com.dometicapp:id/Tank-macAddress-cardTitle']\n";
    public static final String  MAC_Address_value_access_id = "com.dometicapp:id/Tank-macAddress-cardSubText";
    public static final String Software_version_text_expected = "Software Version";
    public static final String Software_version_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Software Version') or @content-desc='com.dometicapp:id/Tank-softwareVersion-cardTitle']";
    public static final String Software_version_value_access_id = "com.dometicapp:id/Tank-softwareVersion-cardSubText";
    public static final String Tanks_Back_button_access_id = " , back";

//    ---------------------------------------------------------------------------------------------------------------------
//    Power tile:

    public static final String Landing_Power_Tile_text_expected = "Power";
    public static final String Landing_Power_Tile_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Power') or @content-desc='com.dometicapp:id/tile-power-titleView']";
    public static final String Power_tile_text_access_id = "com.dometicapp:id/tile-power-titleView";

//    ---------------------------------------------------------------------------------------------------------------------------
//    #Landing screen UI#

    public static final String Climate_tile_warning_icon_access_id = "com.dometicapp:id/tile-climate-warningIcon";
    public static final String Climate_tile_card_unit_text_expected = "°C";
    public static final String Climate_tile_card_unit_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'°C') or @content-desc='com.dometicapp:id/tile-climate-cardUnitText-0']";
    public static final String Climate_tile_main_card_access_id = "com.dometicapp:id/tile-climate-mainCardText-0";
    public static final String Climate_tile_page_control_access_id = "com.dometicapp:id/tile-climate-pageControl";
    public static final String Climate_tile_outside_text_expected = "";
    public static final String Climate_tile_outside_text_xpath_or_operator = "";
    public static final String Power_tile_main_card_text_expected = "NaN";
    public static final String Power_tile_main_card_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'NaN') or @content-desc='com.dometicapp:id/tile-power-mainCardText-0']";
    public static final String Power_tile_card_unit_text_expected = "V";
    public static final String Power_tile_card_unit_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'V') or @content-desc='com.dometicapp:id/tile-power-cardUnitText-0']";
    public static final String Power_tile_House_Battery_text_expected = "House Battery";
    public static final String Power_tile_House_Battery_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'House Battery') or @content-desc='com.dometicapp:id/tile-power-mainCardSubText-0']";
    public static final String Tanks_tile_card_unit_access_id = "com.dometicapp:id/tile-tank-cardUnitText-1";
    public static final String Tanks_tile_page_control_access_id = "com.dometicapp:id/tile-tank-pageControl";
    public static final String Bottom_layout_All_text_expected = "All";
    public static final String Bottom_layout_All_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'All') or @content-desc='com.dometicapp:id/categoryTabBarItemText-All']";
    public static final String LandingPage_BottomLayout_All_tab_bar_item_access_id = "com.dometicapp:id/categoryTabBarItem-All";
    public static final String Bottom_Layout_climate_text_expected = "Climate";
    public static final String Bottom_Layout_climate_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Climate') or @content-desc='com.dometicapp:id/categoryTabBarItemText-Climate']";
    public static final String Bottom_layout_climate_tab_bar_item_access_id = "com.dometicapp:id/categoryTabBarItem-Climate";
    public static final String Bottom_layout_Devices_text_expected = "Devices";
    public static final String Bottom_layout_Devices_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Devices') or @content-desc='com.dometicapp:id/categoryTabBarItemText-Devices']";
    public static final String Bottom_Layout_Devices_tab_bar_item_access_id = "com.dometicapp:id/categoryTabBarItem-Devices";
    public static final String Bottom_layout_Tanks_text_expected = "Tanks";
    public static final String Bottom_layout_Tanks_text_xpath_or_operator = "//android.widget.TextView[contains(@text,'Tanks') or @content-desc='com.dometicapp:id/categoryTabBarItemText-Tanks']";
    public static final String Bottom_layout_Tanks_tab_bar_item_access_id = "com.dometicapp:id/categoryTabBarItem-Tanks";
}
