package com.dometic.Apollo.qa.Pages;

public class Constant_AccountSettings {
    // --------------Accessibility_id-------------------//
    public static final String accountSettings_Profile_Text_Access_Id="com.dometicapp:id/userSettings-profile-cardTitle";
    public static final String profile_Header_Text_Access_Id="com.dometicapp:id/header-TitleText";
    public static final String profile_UserProfile_photo_Access_Id="com.dometicapp:id/userProfile-photo";
    public static final String profile_PersonalInfoText_Access_Id="com.dometicapp:id/userProfile-personalInfoText";
    public static final String profile_NameLabel_Access_Id="com.dometicapp:id/userProfile-nameLabel";
    public static final String profile_NameValue_Access_Id="com.dometicapp:id/userProfile-nameValue";
    public static final String profile_emailLabel_Access_Id="com.dometicapp:id/userProfile-emailLabel";
    public static final String profile_emailValue_Access_Id="com.dometicapp:id/userProfile-emailValue";
    public static final String profile_phoneLabel_Access_Id="com.dometicapp:id/userProfile-phoneLabel";
    public static final String profile_phoneValue_Access_Id="com.dometicapp:id/userProfile-phoneValue";
    public static final String profile_addressLabel_Access_Id="com.dometicapp:id/userProfile-addressLabel";
    public static final String profile_addressValue_Access_Id="com.dometicapp:id/userProfile-addressValue";
    public static final String profile_EditProfileButton_cardTitle_Access_Id="com.dometicapp:id/userProfile-EditProfileButton-cardTitle";
    public static final String profile_EditProfileButton_cardIcon_Access_Id="com.dometicapp:id/userProfile-EditProfileButton-cardIcon";
    public static final String profile_securityText_Access_Id="com.dometicapp:id/userProfile-securityText";
    public static final String profile_resetPasswordText_Access_Id="com.dometicapp:id/userProfile-resetPasswordText";
    public static final String profile_renew_cardTitle_Access_Id="com.dometicapp:id/userProfile-renew-cardTitle";
    public static final String profile_renew_cardIcon_Access_Id="com.dometicapp:id/userProfile-renew-cardIcon";
    public static final String editProfile_TitleText_Access_Id="com.dometicapp:id/header-TitleText";
    public static final String editProfile_Photo_Access_Id="com.dometicapp:id/editProfile-photo";
    public static final String editProfile_EmailValue_Access_Id="com.dometicapp:id/editProfile-emailValue";
    public static final String editProfile_firstNameLabel_Access_Id="com.dometicapp:id/editProfile-firstNameLabel";
    public static final String editProfile_firstNNameValue_Access_Id="com.dometicapp:id/editProfile-firstNNameValue";
    public static final String editProfile_lastameLabel_Access_Id="com.dometicapp:id/editProfile-lastameLabel";
    public static final String editProfile_lastNameValue_Access_Id="com.dometicapp:id/editProfile-lastNameValue";
    public static final String editProfile_phoneLabel_Access_Id="com.dometicapp:id/editProfile-phoneLabel";
    public static final String editProfile_phoneValue_Access_Id="com.dometicapp:id/editProfile-phoneValue";
    public static final String editProfile_addressLabel_Access_Id="com.dometicapp:id/editProfile-addressLabel";
    public static final String editProfile_addressValue_Access_Id="com.dometicapp:id/editProfile-addressValue";
    public static final String editProfile_saveButton_Access_Id="com.dometicapp:id/editProfile-saveButton";
    public static final String appSettings_Header_Text_Access_Id="com.dometicapp:id/header-TitleText";
    public static final String appSettings_languageText_Access_Id="com.dometicapp:id/setting-languageText";
    public static final String appSettings_selectedLanguage_Access_Id="com.dometicapp:id/setting-selectedLanguage";
    public static final String appSettings_temperatureContainer_Access_Id="com.dometicapp:id/setting-temperatureContainer";
    public static final String appSettings_celsiusText_Access_Id="com.dometicapp:id/setting-celsiusText";
    public static final String appSettings_fahrenheitText_Access_Id="com.dometicapp:id/setting-fahrenheitText";
    public static final String appSettings_unitText_Access_Id="com.dometicapp:id/setting-unitText";
    public static final String appSettings_selectedUnit_Access_Id="com.dometicapp:id/setting-selectedUnit";
    public static final String appSettings_versionText_Access_Id="com.dometicapp:id/setting-versionText";
    public static final String appSettings_language_header_TitleText_Access_Id="com.dometicapp:id/header-TitleText";
    public static final String appSettings_Back_Button_Access_Id="com.dometicapp:id/tiles-backImage";
    public static final String appSettings_Language_English_CardTitle_Access_Id="com.dometicapp:id/language-english-cardTitle";
    public static final String appSettings_Language_German_CardTitle_Access_Id="com.dometicapp:id/language-german-cardTitle";
    public static final String appSettings_Language_Spanish_CardTitle_Access_Id="com.dometicapp:id/language-spanish-cardTitle";
    public static final String appSettings_Language_French_CardTitle_Access_Id="com.dometicapp:id/language-french-cardTitle";
    public static final String appSettings_Unit_header_TitleText_Access_Id="com.dometicapp:id/header-TitleText";
    public static final String appSettings_Unit_Metric_Access_Id="com.dometicapp:id/unitSelection-metric-cardTitle";
    public static final String appSettings_Unit_Imperial_Access_Id="com.dometicapp:id/unitSelection-imperial-cardTitle";

    //------------------New Access id------------------------------//
    public static final String profile_LandingPage_edit_button_Access_Id = "com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String profile_AccountSetting_Header_Access_Id = "com.dometicapp:id/header-TitleText";
    public static final String profile_AccountSettings_Setting_text_Access_Id = "";
    public static final String profile_accountSetting_profile_text_Access_Id = "com.dometicapp:id/userSettings-profile-cardTitle";
    public static final String profile_AccountSetting_subscription_Access_Id = "com.dometicapp:id/userSettings-subscriptions-cardTitle";
    public static final String profile_AccountSettings_mail_id_Access_Id = "com.dometicapp:id/userSettings-userEmail";
    public static final String profile_AccountSettings_userNAme_Access_Id = "com.dometicapp:id/userSettings-userName";
    public static final String profile_AccountSettings_photo_Access_Id = "com.dometicapp:id/userSettings-profilePhoto";
    public static final String Settings_DeviceManagement_header_accessid = "com.dometicapp:id/header-TitleText";
    public static final String Settings_DeviceManage_AddNew_Button_accessid = "com.dometicapp:id/DeviceManagement-addNewButtonText";
    public static final String Settings_DeviceManage_MarineDevice_logo_accessid = "com.dometicapp:id/DeviceManagement-smallLogo";
    public static final String Settings_DeviceManagement_righticon_Access_Id = "com.dometicapp:id/DeviceManagement-rightIcon";
    public static final String Settings_Onboarding_close_button_Access_Id = "com.dometicapp:id/onBoarding-closeImage";
    public static final String Settings_Onboarding_HeaderText_Access_Id = "com.dometicapp:id/header-TitleText";
    public static final String Settings_Onboarding_Nodevicefound_text_accessid = "com.dometicapp:id/onBoarding-noDeviceTitle";
    public static final String Settings_Onboarding_attention_image_accessid = "com.dometicapp:id/onBoarding-attentionImage";
    public static final String Settings_Onboarding_BluetoothPairing_message_access_id = "com.dometicapp:id/onBoarding-bleMsgText";
    public static final String Settings_Onboarding_SearchAgain_accessid = "com.dometicapp:id/onBoarding-searchAgainButtonText";
    public static final String Settings_Onboarding_close_button = "com.dometicapp:id/onBoarding-closeImage";
    public static final String Subscription_title_accessid = "com.dometicapp:id/header-TitleText";
    public static final String Subscription_backbutton_accessid =  "com.dometicapp:id/tiles-backImage";
    public static final String SDB_Device_Name = "com.dometicapp:id/deviceManagement-deviceName";
    public static final String Given_Device_name = "com.dometicapp:id/deviceManagement-vesselNameValue";
    public static final String Device_Name_text  = "com.dometicapp:id/deviceManagement-vesselNameLabel";
    public static final String Product_information_text = "com.dometicapp:id/deviceManagement-vesseltitleLabel";
    public static final String Edit_button_text = "com.dometicapp:id/deviceManagement-editVessel-cardTitle";
    public static final String Edit_navigation_button = "com.dometicapp:id/deviceManagement-editVessel-cardIcon";
    public static final String Pin_codes_text = "com.dometicapp:id/deviceManagement-pinCodeTitleText";
    public static final String Master_pin_navigation_button = "com.dometicapp:id/deviceManagement-masterPin-cardIcon";
    public static final String Unregister_navigation_button = "com.dometicapp:id/deviceManagement-unregisterDelete-cardIcon";
    public static final String Unregister_text = "com.dometicapp:id/deviceManagement-unregisterDelete-cardTitle";
    public static final String Check_updates_navigation_button = "com.dometicapp:id/deviceManagement-checkForUpdates-cardIcon";
    public static final String Check_updates_text = "com.dometicapp:id/deviceManagement-checkForUpdates-cardTitle";
    public static final String Cooler_settings_navigation_button = "com.dometicapp:id/deviceManagement-coolerSetting-cardIcon";
    public static final String Cooler_settings_text = "com.dometicapp:id/deviceManagement-coolerSetting-cardTitle";
    public static final String Advanced_text = "com.dometicapp:id/deviceManagement-advancedTitleText";
    public static final String Guest_pin_navigation_button = "com.dometicapp:id/deviceManagement-guestPin-cardIcon";
    public static final String Guest_pin_text = "com.dometicapp:id/deviceManagement-guestPin-cardTitle";
    public static final String ManageNotifications_title_access_id = "com.dometicapp:id/header-TitleText";
    public static final String ManageNotifications_back_button_access_id = "com.dometicapp:id/tiles-backImage";
    public static final String ManageNotifications_logo_access_id = "com.dometicapp:id/notification-header-logo";
    public static final String ManageNotifications_Global_settings_access_id = "com.dometicapp:id/notification-header-text";
    public static final String ManageNotifications_Push_Notifications_access_id = "";
    public static final String ManageNotifications_PushNotifications_text_access_id = "com.dometicapp:id/notification-pushNotificationContainer-cardTitle";
    public static final String ManageNotifications_PushNotifications_toggle_access_id = "com.dometicapp:id/notification-pushNotificationContainer-switchComponent";
    public static final String ManageNotifications_push_show_more_text_access_id =  "com.dometicapp:id/notification-pushNotificationShowMore-cardTitle";
    public static final String ManageNotifications_push_show_more_text_navigation_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-expandIcon";
    public static final String ManageNotifications_push_show_less_text_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-cardTitle";
    public static final String ManageNotifications_push_show_less_navigation_access_id = "com.dometicapp:id/notification-pushNotificationShowMore-expandIcon";
    public static final String ManageNotifications_push_alerts_text_access_id = "com.dometicapp:id/notification-pushNotificationAlertText";
    public static final String ManageNotifications_push_alerts_toggle_access_id =  "com.dometicapp:id/notification-pushNotificationAlertSwitch";
    public static final String ManageNotifications_push_warnings_text_access_id = "com.dometicapp:id/notification-pushNotificationWarningText";
    public static final String ManageNotifications_push_warnings_toggle_access_id =  "com.dometicapp:id/notification-pushNotificationWarningSwitch";
    public static final String ManageNotifications_push_alerts_text_xpath =  "(//android.widget.TextView[@content-desc=\"undefinedText\"])[1]";
    public static final String ManageNotifications_push_alerts_toggle_xpath =     "(//android.view.ViewGroup[@content-desc=\"undefinedSwitch\"])[1]";
    public static final String ManageNotifications_push_warnings_text_xpath = "(//android.widget.TextView[@content-desc=\"undefinedText\"])[2]";
    public static final String ManageNotifications_push_warnings_toggle_xpath =  "(//android.view.ViewGroup[@content-desc=\"undefinedSwitch\"])[2]";
    public static final String ManageNotifications_Email_list_header_access_id = "com.dometicapp:id/header-TitleText";
    public static final String ManageNotifications_Email_account_text_access_id = "com.dometicapp:id/editList-mainAccount-title-text";
    public static final String ManageNotifications_Additional_email_text_access_id = "com.dometicapp:id/editList-aditionalAccounts-title-text";
    public static final String ManageNotifications_SMS_list_Mobile_account_text_access_id = "com.dometicapp:id/editList-mainAccount-title-text";
    public static final String ManageNotifications_SMS_List_text_access_id = "com.dometicapp:id/header-TitleText";

    public static final String ManageNotifications_Advanced_Temperature_Alerts_Push_notifications_toggle_access_id = "TemperatureAlertsElement0-Switch";
    public static final String ManageNotifications_Advanced_Temperature_Alerts_Push_notifications_text_access_id = "TemperatureAlertsElement0-Text";
    public static final String ManageNotifications_Advanced_Batteries_Alerts_Push_notifications_toggle_access_id = "BatteriesAlertsElement0-Switch";
    public static final String ManageNotifications_Advanced_Batteries_Alerts_Push_notifications_text_access_id = "BatteriesAlertsElement0-Text";
    public static final String ManageNotifications_Advanced_Tank_show_less_access_id = "ELEMENT-cardTitle";
    public static final String ManageNotifications_Advanced_Tanks_Alerts_Push_notifications_toggle_access_id = "TanksAlertsElement0-Switch";
    public static final String ManageNotifications_Advanced_Tanks_Alerts_Push_notifications_text_access_id = "TanksAlertsElement0-Text";
    public static final String ManageNotifications_Advanced_push_Email_access_id = "deviceEmailNotifications0Element0-Text";
    public static final String ManageNotifications_Advanced_push_notifications_toggle_button_access_id = "devicePushNotificationsElement-Switch";
    public static final String ManageNotifications_Advanced_push_notifications_access_id = "devicePushNotificationsElement-Text";
    public static final String ManageNotifications_Advanced_logo_access_id = "DeviceNotifications.Header-logo";
    public static final String ManageNotifications_Advanced_back_button_access_id = "com.dometicapp:id/tiles-backImage";
    public static final String ManageNotifications_Advanced_header_text_access_id = "com.dometicapp:id/header-TitleText";
    public static final String ManageNotifications_Advanced_Device_SDB_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-Dometic1234-name";
    public static final String ManageNotifications_Advanced_Device_SDB_navigation_button_access_id = "com.dometicapp:id/notification-AdvancedNotificationSetings-Dometic1234-iconCollapse";
    public static final String ManageNotifications_Advanced_Device_SDB_icon_access_id = "AdvancedNotificationSetings-Dometic1234-icon";
    public static final String ManageNotifications_Advanced_text_access_id = "com.dometicapp:id/notification-advanceText";
    public static final String ManageNotifications_Advanced_Email_toggle_button_access_id = "deviceEmailNotifications0Element0-Switch";
    public static final String ManageNotifications_Advanced_device_name_access_id = "DeviceNotifications.Header-text";

    public static final String Settings_english_language_text_selection="com.dometicapp:id/language-english-cardTitle";
    public static final String Settings_english_language_LANGUAGE_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_version_german_language="com.dometicapp:id/language-german-cardTitle";
    public static final String App_setting_main_text_access_id="com.dometicapp:id/sidemenu-appSettings-text";
    public static final String profile_setting_right_icon_access_id="com.dometicapp:id/userProfile-renew-cardIcon";
    public static final String profile_setting_renew_access_id="com.dometicapp:id/userProfile-renew-cardTitle";
    public static final String profile_setting_password_name_access_id="com.dometicapp:id/userProfile-EditProfileButton-cardIcon";
    public static final String profile_setting_security_name_text_access_id="com.dometicapp:id/userProfile-securityText";
    public static final String profile_setting_edit_profile_right_icon_access_id="com.dometicapp:id/userProfile-EditProfileButton-cardIcon";
    public static final String profile_setting_edit_profile_access_id="com.dometicapp:id/userProfile-EditProfileButton-cardTitle";
    public static final String profile_setting_address_text_access_id="com.dometicapp:id/userProfile-addressLabel";
    public static final String profile_setting_mobile_text_access_id="com.dometicapp:id/userProfile-phoneLabel";
    public static final String profile_setting_email_text_access_id="com.dometicapp:id/userProfile-emailLabel";
    public static final String profile_setting_name_text_access_id="com.dometicapp:id/userProfile-nameLabel";
    public static final String profile_setting_personal_information_text_access_id="com.dometicapp:id/userProfile-personalInfoText";
    public static final String profile_settings_right_icon_access_id="com.dometicapp:id/userSettings-profile-cardIcon";
    public static final String view_and_edit_setting_access_id ="com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String App_setting_app_verion_name_card_title="com.dometicapp:id/setting-versionText";
    public static final String App_setting_app_right_icon_access_id="com.dometicapp:id/setting-languageiconCollapse";
    public static final String App_setting_app_setting_main_page_card_title_access_id="com.dometicapp:id/header-TitleText";
    public static final String App_setting_app_setting_language_card_title_access_id="com.dometicapp:id/setting-languageText";
    public static final String Device_manegement_cooler_setting_right_back_button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Device_manegement_cooler_setting_temperature__right_icon_access_id="com.dometicapp:id/sdbCoolerSettings-temperature-cardIcon";
    public static final String Device_manegement_cooler_setting_temperature_card_title_access_id="com.dometicapp:id/sdbCoolerSettings-temperature-cardTitle";
    public static final String Device_manegement_cooler_setting_scheduled_at_right_icon_access_id="com.dometicapp:id/sdbCoolerSettings-scheduledAt-cardIcon";
    public static final String Device_manegement_cooler_setting_scheduled_at_card_title_access_id="com.dometicapp:id/sdbCoolerSettings-scheduledAt-cardTitle";
    public static final String Device_manegement_cooler_setting_scheduler_toggel_button_access_id="com.dometicapp:id/sdbCoolerSettings-scheduler-switchComponent";
    public static final String Device_manegement_cooler_setting_scheduler_card_title_access_id="com.dometicapp:id/sdbCoolerSettings-scheduler-cardTitle";
    public static final String Device_manegement_cooler_setting_cooler_Status_toggel_button_access_id="com.dometicapp:id/sdbCoolerSettings-coolerStatus-switchComponent";
    public static final String Device_manegement_cooler_setting_cooler_Status_name_access_id="com.dometicapp:id/sdbCoolerSettings-coolerStatus-cardTitle";
    public static final String Device_manegement_cooler_setting_page_header_text="com.dometicapp:id/header-TitleText";
    public static final String Device_manegement_cooler_setting_right_icon_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardIcon";
    public static final String Device_manegement_cooler_setting_main_text_access_id="com.dometicapp:id/deviceManagement-coolerSetting-cardTitle";

    // ----------------------xpath----------------------//
    public static final String Device_Management_MasterPin_xpath = "//*[@content-desc='com.dometicapp:id/deviceManagement-masterPin-cardTitle']";
    public static final String Device_Management_sdb_xpath = "(//*[@content-desc='com.dometicapp:id/DeviceManagement-deviceName'])[1]";


    // ----------------------Data----------------------//
    public static final String profile_AccountSetting_Header = "ACCOUNT SETTINGS";
    public static final String profile_AccountSettings_Setting_tex = "";
    public static final String profile_accountSetting_profile_text = "Profile";
    public static final String profile_AccountSetting_subscription = "Subscriptions";
    public static final String Settings_DeviceManagement_header = "DEVICE MANAGEMENT";
    public static final String Settings_DeviceManage_AddNew_Button = "Add new";
    public static final String Settings_Onboarding_HeaderText = "ONBOARDING";
    public static final String Subscription_title = "SUBSCRIPTIONS";
    public static final String profile_Header_Text="PROFILE";
    public static final String profile_PersonalInfoText="PERSONAL INFORMATION";
    public static final String profile_NameLabel="Name";
    public static final String profile_emailLabel="E-mail";
    public static final String profile_phoneLabel="Mobile";
    public static final String profile_addressLabel="Address";
    public static final String profile_EditProfileButton_cardTitle="Edit Profile";
    public static final String profile_securityText="SECURITY";
    public static final String profile_resetPasswordText="Password";
    public static final String profile_renew_cardTitle="Renew";
    public static final String editProfile_TitleText="EDIT PROFILE";
    public static final String editProfile_firstNameLabel="First name";
    public static final String editProfile_lastameLabel="Last name";
    public static final String editProfile_phoneLabel="Primary mobile";
    public static final String editProfile_addressLabel="Address";
    public static final String editProfile_firstNameValue="RAMESH";
    public static final String editProfile_lastameValue="BABU";
    public static final String editProfile_firstNameValue_SpecialCharacter="!@#$%^&*()_+";
    public static final String editProfile_lastameValue_SpecialCharacter="+_)(*&^%$#@!";
    public static final String grinning_face_with_smiling_eyes = new String(Character.toChars(0x1F601));
    public static final String face_with_tears_of_joy = new String(Character.toChars(0x1F602));
    public static final String smiling_face_with_open_mouth_and_cold_sweat = new String(Character.toChars(0x1F605));
    public static final String smiling_face_with_open_mouth_and_tightly_closed_eyes = new String(Character.toChars(0x1F606));
    public static final String winking_face = new String(Character.toChars(0x1F609));
    public static final String editProfile_phoneValue="+919003034122";
    public static final String editProfile_addressValue="CHENNAI";
    public static final String editProfile_addressValue_SpecialCharacter="!@#$%^&*()_+";
    public static final String appSettings_Header_Text="APP SETTINGS";
    public static final String appSettings_languageText="Language";
    public static final String appSettings_temperatureContainer="Temperature";
    public static final String appSettings_unitText="Units";
    public static final String appSettings_versionText="App version";
    public static final String appSettings_language_header_TitleText="LANGUAGE";
    public static final String appSettings_Language_English_CardTitle_Text="English";
    public static final String appSettings_Language_German_CardTitle_Text="German";
    public static final String appSettings_Language_Spanish_CardTitle_Text="Spanish (US)";
    public static final String appSettings_Language_French_CardTitle_Text="French";
    public static final String appSettings_Unit_header_TitleText_Text="UNIT";
    public static final String appSettings_Unit_Metric_Text="Metric";
    public static final String appSettings_Unit_Imperial_Text="Imperial";

    // ----------------------Objects created by Rishu----------------------//
    public static final String DeviceManagement_MasterPin_accessid="com.dometicapp:id/deviceManagement-masterPin-cardTitle";
    public static final String DeviceManagement_SDB_password_required_text_xpath="//*[@text='Password Required']";
    public static final String DeviceManagement_SDB_password_requiredInValid_password="4678";
    public static final String DeviceManagement_SDB_password_requiredValid_password="5678";
    public static final String DeviceManagement_SDB_PasswordAlertField_EnterButton_xpath="//*[@text='ENTER']";
    public static final String DeviceManagement_SDB_PasswordAlertField_CancelButton_xpath="//*[@text='CANCEL']";
    public static final String DeviceManagement_SDBDevice_wrongPassword_alert="android:id/alertTitle";
    public static final String DeviceManagement_SDBDevice_wrongPassword_alert_text="Alert";
    public static final String DeviceManagement_SDBDevice_wrongPassword_alert_OkButton_xpath="//*[@text='OK']";
    public static final String DeviceManagement_SDBDevice_masterPin_PasswordRequired_inputField_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.appcompat.widget.LinearLayoutCompat/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.EditText";
    public static final String DeviceManagement_SDBDevice_MasterPin_Closebutton_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/header-rightButton\"]/android.widget.TextView";
    public static final String DeviceManagement_SDBDevice_masterPin_SetMasterPin_Reenter_Message_xpath="//*[@text='Re-enter your PIN']";
    public static final String DeviceManagement_SDBDevice_masterPin_SetMasterPin_InputField_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText";
    public static final String DeviceManagement_SDBDevice_masterPin_SetMasterPin_invalidPassword="123";
    public static final String DeviceManagement_SDBDevice_masterPin_SetMasterPin_ValidPassword="2345";
    public static final String Settings_DeviceManagement_Accessid ="com.dometicapp:id/sidemenu-deviceMangagement-text";
    public static final String Settings_DeviceManagement_MasterPIN_Header="com.dometicapp:id/header-TitleText";
    public static final String Settings_DeviceManagement_SetMasterPIN_text_xpath="//*[@text='SET MASTER PIN']";
    public static final String Settings_DeviceManagement_SEtMasterPIN_Message_xpath="//*[@text='PIN must be 4 digits']";
    public static final String SDB_MainScreen_Doo_access_toggle_one_xpath="";
    public static final String SDB_MainScreen_Doo_access_toggle_two_xpath="";
    public static final String SDB_MainScreen_Doo_access_TemperatureScroller_xpath="";
    public static final String SDB_MainScreen_Doo_access_minusButton_xpath="//*[@content-desc='undefined-leftButton']";
    public static final String SDB_MainScreen_Doo_access_Plusbutton_xpath="//*[@content-desc='undefined-rightButtonIcon']";
    public static final String Product_info = "PRODUCT INFORMATION";
    public static final String Edit = "Edit";
    public static final String Unreg_Del_Off = "Unregister/Delete/Offboard";
    public static final String Check_updates = "Check updates";
    public static final String Cooler_settings = "Cooler settings";
    public static final String Advanced = "ADVANCED";
    public static final String GuestPin_list = "Guest PIN list";
    public static final String Master_pin = "Master PIN";
    public static final String PinCodes = "PIN CODES";
    public static final String Name = "Name";

}
